from pathlib import Path
D='2026-04-29'
root=Path('.')
engstd=root/'knowledge/wikis/engineering-standards/wiki'
eng=root/'knowledge/wikis/engineering/wiki'
for d in [engstd/'sources', engstd/'standards', eng/'sources', eng/'concepts']:
    d.mkdir(parents=True, exist_ok=True)

def write(path, text):
    path.write_text(text.strip()+"\n", encoding='utf-8')

std_sources=[
('doris-codes-specs-faceted-index','DORIS Codes and Specs faceted metadata index','Faceted pointer for the Elements DORIS codes/specs corpus.','/mnt/ace/doris/codes','35,197 files; approximate family counts regenerated from Elements metadata, not raw extraction.'),
('doris-techstreet-drop','DORIS TechStreet Drop metadata pointer','Licensed-aggregator drop: metadata-only existence pointer.','/mnt/ace/doris/codes/TechStreet Drop','License posture: CRITICAL. No publisher list, titles, clauses, or copied standard text emitted.'),
('doris-company-specs','DORIS Company Specs metadata pointer','Confidential company/client specifications bucket: metadata-only existence pointer.','/mnt/ace/doris/codes/Company Specs','Confidentiality posture: CRITICAL. No subfolder enumeration, client list, clauses, or copied content emitted.'),
('doris-deepstar','DORIS DeepStar metadata pointer','DeepStar/JIP deliverables bucket: metadata-only existence pointer.','/mnt/ace/doris/codes/DeepStar','JIP membership posture: HIGH. No deliverable text, titles beyond bucket name, or technical findings emitted.'),
]
for slug,title,summary,src,notes in std_sources:
    write(engstd/f'sources/{slug}.md', f'''---
title: "{title}"
tags: ["elements-ingest", "doris", "standards", "metadata-only"]
added: {D}
last_updated: {D}
domain: engineering-standards
sources:
  - {src}
extraction_policy: metadata-only
raw_copy_allowed: false
---

# {title}

## Summary
{summary}

## Source of record
- `{src}`

## No-extraction boundary
No raw standards text is copied, extracted, quoted, summarized, or stored in git/wiki. This page is a pointer created for workspace-hub#2543 from metadata generated by #2535/#2540.

## Metadata notes
{notes}

## Cross-links
- [Elements ingest catalog — doris-codes-specs](elements-doris-codes-specs.md)
- [DORIS Codes and Specs faceted metadata index](doris-codes-specs-faceted-index.md)
''')
faceted=engstd/'sources/doris-codes-specs-faceted-index.md'
faceted.write_text(faceted.read_text(encoding='utf-8')+'''
## Approximate family histogram
Counts are approximate planning metadata regenerated from `.planning/intel/elements-to-llm-wiki/elements-ingested-files.jsonl` and should not be treated as authoritative standard inventories.

| Family / bucket | Approximate count or signal | Policy |
|---|---:|---|
| Company Specs | 15,864 | confidential pointer only |
| TechStreet Drop | 12,266 | licensed pointer only |
| BV Ship and Offshore Rules | 5,325 | public portal metadata only; BV publisher stub deferred unless revision_source/public_url verified |
| API mentions | 7,516 | metadata signal only |
| ASME mentions | 5,221 | metadata signal only |
| OCIMF / CSA | 0 / 0 | boundary belongs to acma-codes, #2227/#2471 |

## Corpus boundary
`Codes and Regulations` / `acma-codes` is not represented here. OCIMF and CSA promotion remains tracked by #2227/#2471, not this DORIS codes/specs corpus.

BV publisher stub deferred: public revision metadata was not independently verified during this metadata-only pass.
''', encoding='utf-8')
idx=engstd/'index.md'
idx_text=idx.read_text(encoding='utf-8')
for slug,title,summary,src,notes in std_sources:
    row=f'| [[{title}]](sources/{slug}.md) | {summary} | {D} |'
    if slug not in idx_text:
        idx_text += row+'\n'
idx_text=idx_text.replace('last_updated: 2026-04-28','last_updated: 2026-04-29').replace('page_count: 1','page_count: 5').replace('source_count: 1','source_count: 5')
idx.write_text(idx_text, encoding='utf-8')
log=engstd/'log.md'
log.write_text(log.read_text(encoding='utf-8')+f'''\n## [{D}] ingest | DORIS Codes metadata-only standards pointer pass (#2543)\n- Pages created: `sources/doris-codes-specs-faceted-index.md`, `sources/doris-techstreet-drop.md`, `sources/doris-company-specs.md`, `sources/doris-deepstar.md`.\n- Source of record: `/mnt/ace/doris/codes`; no raw standards text copied or extracted.\n- Notes: BV publisher stub deferred pending public revision/source/date evidence; #2534 cleanup remains blocked.\n''', encoding='utf-8')

source_pages=[
('doris-university-module-1-00-subsea-production-systems-overview','Doris University Module 1.00 — Subsea Production Systems Overview','Rows 1; metadata-first overview of SPS curriculum context.'),
('doris-university-module-1-01-production-control-systems','Doris University Module 1.01 — Production Control Systems','Rows 2-3; metadata-first pointer to control-system curriculum materials.'),
('doris-university-module-1-02-umbilical-systems','Doris University Module 1.02 — Umbilical Systems','Rows 4-6; metadata-first pointer to umbilical systems training materials.'),
('doris-university-module-1-03-installation-workover-control','Doris University Module 1.03 — Installation/Workover Control','Rows 7-8; metadata-first pointer to IWOCS training materials.'),
('doris-university-lunch-and-learn-control-systems','Doris University Lunch and Learn — Control Systems','Rows 13-14; metadata-first pointer to Doris-authored lunch-and-learn content.'),
('doris-university-lunch-and-learn-umbilical-systems','Doris University Lunch and Learn — Umbilical Systems','Rows 15-17; metadata-first pointer to umbilical lunch-and-learn content.'),
('doris-university-syllabus-snapshot','Doris University syllabus snapshot','Row 18; syllabus/taxonomy validation pointer.'),
]
for slug,title,summary in source_pages:
    write(eng/f'sources/{slug}.md', f'''---
title: "{title}"
tags: ["elements-ingest", "doris", "training", "metadata-first"]
added: {D}
last_updated: {D}
domain: engineering
sources:
  - /mnt/ace/doris/training
extraction_policy: metadata-first
raw_copy_allowed: false
ocr_allowed: false
---

# {title}

## Summary
{summary}

## Source of record
- `/mnt/ace/doris/training`

## Extraction boundary
Full text was not extracted. No slide text, speaker notes, figures, standard excerpts, OCR output, or raw file bytes were copied into git/wiki. This page is a curated metadata/source pointer for workspace-hub#2542.

## Cross-links
- [Elements ingest catalog — doris-university](elements-doris-university.md)
''')
concepts=[
('subsea-production-system-overview','Subsea production system overview','Connects Doris University SPS overview material to reusable subsea production system concepts.'),
('subsea-production-control-system','Subsea production control system','Metadata-first synthesis hook for production control system curriculum.'),
('subsea-umbilical-system','Subsea umbilical system','Metadata-first synthesis hook for umbilical system curriculum.'),
('installation-workover-control-system','Installation/workover control system','Metadata-first synthesis hook for IWOCS curriculum.'),
('methanol-injection-analysis','Methanol injection analysis','Calculation concept placeholder; no formulas or standard-derived text extracted.'),
('umbilical-tube-sizing-api-17e','Umbilical tube sizing and API 17E citation boundary','Calculation concept placeholder linked to API 17E public metadata stub.'),
('hydrostatic-pressure-depth','Hydrostatic pressure with depth','Calculation concept placeholder; no formula extraction in tranche 1.'),
('subsea-accumulator-sizing','Subsea accumulator sizing','Calculation concept placeholder; API 17G/API 16D resolution deferred until public metadata verified.'),
]
for slug,title,summary in concepts:
    write(eng/f'concepts/{slug}.md', f'''---
title: "{title}"
tags: ["doris-university", "training", "curated-summary"]
added: {D}
last_updated: {D}
domain: engineering
sources:
  - /mnt/ace/doris/training
curated_summary_only: true
full_text_extracted: false
---

# {title}

## Summary
{summary}

## Boundary
This is a curated summary shell created from tranche metadata only. Full text was not extracted, OCR was not used, and no standard clause text or training figures were copied.

## Source pointers
- `/mnt/ace/doris/training`
- [Elements ingest catalog — doris-university](../sources/elements-doris-university.md)
''')
write(engstd/'standards/api-17e.md', f'''---
title: "API 17E — Subsea umbilicals metadata stub"
tags: ["api", "standards", "metadata-only"]
added: {D}
last_updated: {D}
domain: engineering-standards
code_id: api-17e
publisher: API
revision: public-metadata-required-before-citation-use
revision_source: public publisher metadata not bundled with Elements corpus
verified_on: {D}
public_url: https://www.api.org/products-and-services/standards
sources:
  - public API standards catalog pointer
extraction_policy: metadata-only
raw_copy_allowed: false
---

# API 17E — Subsea umbilicals metadata stub

This page is a resolver placeholder for Doris University calc-citation routing. It contains public metadata only and no standard clause text.
''')
idx=eng/'index.md'
idx_text=idx.read_text(encoding='utf-8')
for slug,title,summary in source_pages:
    row=f'| [{title}](sources/{slug}.md) | {summary} | {D} |'
    if slug not in idx_text: idx_text+='\n'+row
for slug,title,summary in concepts:
    row=f'| [{title}](concepts/{slug}.md) | {summary} | {D} |'
    if slug not in idx_text: idx_text+='\n'+row
idx_text=idx_text.replace('last_updated: 2026-04-28','last_updated: 2026-04-29')
idx.write_text(idx_text, encoding='utf-8')
log=eng/'log.md'
log.write_text(log.read_text(encoding='utf-8')+f'''\n## [{D}] ingest | Doris University metadata-first tranche 1 (#2542)\n- Pages created: 7 source pointers and 8 curated concept shells.\n- Standards resolver: `engineering-standards/wiki/standards/api-17e.md` public-metadata-only stub.\n- Source of record: `/mnt/ace/doris/training`; no raw training decks, figures, full text, OCR output, or standards excerpts copied.\n''', encoding='utf-8')
cat=eng/'sources/elements-doris-university.md'
cat_text=cat.read_text(encoding='utf-8')
if '## Tranche 1 children' not in cat_text:
    cat_text += '\n\n## Tranche 1 children\n' + '\n'.join(f'- [{title}]({slug}.md)' for slug,title,_ in source_pages) + '\n'
cat.write_text(cat_text, encoding='utf-8')
