#!/usr/bin/env bash
# bootstrap-machine.sh — One-time setup for any new machine joining the workspace
#
# Creates ~/.claude/CLAUDE.md pointing at .claude/memory/ in this repo.
# Safe to re-run — idempotent (only writes if content differs).
#
# Usage (from repo root):
#   bash scripts/memory/bootstrap-machine.sh
#
# Works on: Linux, macOS, Windows (MINGW64/Git Bash)
# Issue: #1894

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
CLAUDE_DIR="${HOME}/.claude"
CLAUDE_MD="${CLAUDE_DIR}/CLAUDE.md"
TIMESTAMP="$(date +%Y-%m-%d)"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

# Detect OS
OS="linux"
case "$(uname -s)" in
    MINGW*|CYGWIN*|MSYS*) OS="windows" ;;
    Darwin) OS="macos" ;;
esac

echo ""
echo -e "${CYAN}=== Workspace-Hub Machine Bootstrap ===${NC}"
echo "  Detected OS   : ${OS}"
echo "  Repo root     : ${REPO_ROOT}"
echo "  CLAUDE.md     : ${CLAUDE_MD}"
echo ""

# ---------------------------------------------------------------------------
# 1. Create ~/.claude/CLAUDE.md
# ---------------------------------------------------------------------------
mkdir -p "${CLAUDE_DIR}"

# Resolve repo path for Windows (MINGW: /d/workspace-hub → D:\workspace-hub)
if [[ "${OS}" == "windows" ]]; then
    WIN_REPO="$(cygpath -w "${REPO_ROOT}" 2>/dev/null || echo "${REPO_ROOT}")"
    MEMORY_PATH="${WIN_REPO}\\.claude\\memory\\"
else
    MEMORY_PATH="${REPO_ROOT}/.claude/memory/"
fi

DESIRED_CONTENT="# CLAUDE.md — Workspace-Hub Bootstrap
# Generated by scripts/memory/bootstrap-machine.sh on ${TIMESTAMP}

## Memory Is In The Repo

Read \`.claude/memory/\` for all session context — git-tracked, same on every machine:
- \`context.md\`      — machine conventions, paths, Python rules, workspace layout
- \`agents.md\`       — user profile, AI subscriptions, workflow rules
- \`KNOWLEDGE.md\`    — engineering lessons, tool quirks
- \`topics/\`         — Claude auto-memory feedback files (mirrored from ace-linux-1)

Repo memory path: ${MEMORY_PATH}

## Quick Reference

| Rule | Linux | Windows |
|------|-------|---------|
| Python | \`uv run\` | \`python\` |
| Workspace | \`/mnt/local-analysis/workspace-hub\` | \`D:\\workspace-hub\` |
| Sparse overlay | \`~/workspace-hub\` may be overlay — write to \`/tmp/\` first | n/a |
| digitalmodel/ | Separate git repo — cd in before committing | Same |

For full context, read the \`.claude/memory/\` files listed above.
"

# Write only if content differs (idempotent)
if [[ -f "${CLAUDE_MD}" ]]; then
    existing="$(cat "${CLAUDE_MD}")"
    if [[ "${existing}" == "${DESIRED_CONTENT}" ]]; then
        echo -e "${GREEN}✅  ~/.claude/CLAUDE.md already up to date — nothing to do.${NC}"
    else
        echo -e "${YELLOW}⚠️   ~/.claude/CLAUDE.md exists but differs — updating.${NC}"
        echo "${DESIRED_CONTENT}" > "${CLAUDE_MD}"
        echo -e "${GREEN}✅  Updated ~/.claude/CLAUDE.md${NC}"
    fi
else
    echo "${DESIRED_CONTENT}" > "${CLAUDE_MD}"
    echo -e "${GREEN}✅  Created ~/.claude/CLAUDE.md${NC}"
fi

# ---------------------------------------------------------------------------
# 2. Windows-specific: set WORKSPACE_HUB env var hint
# ---------------------------------------------------------------------------
if [[ "${OS}" == "windows" ]]; then
    WIN_ROOT="$(cygpath -w "${REPO_ROOT}" 2>/dev/null || echo "D:\\workspace-hub")"
    echo ""
    echo -e "${CYAN}Windows detected — additional steps:${NC}"
    echo ""
    echo "  Add this to your ~/.bashrc or ~/.profile to set WORKSPACE_HUB:"
    echo "    export WORKSPACE_HUB=\"/d/workspace-hub\""
    echo ""
    echo "  Or in PowerShell (run once):"
    echo "    [Environment]::SetEnvironmentVariable('WORKSPACE_HUB', '${WIN_ROOT}', 'User')"
    echo ""
fi

# ---------------------------------------------------------------------------
# 3. Remind about bridge script (Linux/Hermes machines only)
# ---------------------------------------------------------------------------
if [[ -d "${HOME}/.hermes" ]]; then
    echo ""
    echo -e "${CYAN}Hermes detected — keep memory in sync:${NC}"
    echo "  bash scripts/memory/check-memory-drift.sh"
    echo "  bash scripts/memory/bridge-hermes-claude.sh --commit && git push"
fi

echo ""
echo -e "${GREEN}Bootstrap complete.${NC}"
echo "Run 'git pull' in ${REPO_ROOT} to get the latest memory files."
echo ""
