#!/usr/bin/env bash
# bridge-hermes-claude.sh — Sync Hermes memory into .claude/memory/ (git-tracked)
#
# Architecture: Memory travels with the repository via git.
#   Hermes (Linux) writes memory → .hermes/memories/  → this script extracts
#   canonical facts → .claude/memory/agents.md + context.md → git commit + push
#   Windows clones/pulls → gets same context automatically.
#
# Usage:  cd /path/to/workspace-hub && bash scripts/memory/bridge-hermes-claude.sh
# Run on ace-linux-1 (the machine with Hermes). Safe to run on any machine —
# just skips Hermes source if not found.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"
MEMORY_DIR="${REPO_ROOT}/.claude/memory"
HERMES_MEM_DIR="${HOME}/.hermes/memories"
TIMESTAMP="$(date +%Y-%m-%d)"
CHANGES=0

mkdir -p "${MEMORY_DIR}"

# ---------------------------------------------------------------------------
# 1. Read Hermes MEMORY.md and extract machine/context facts
# ---------------------------------------------------------------------------
HERMES_MEMORY=""
HERMES_USER=""
if [[ -f "${HERMES_MEM_DIR}/MEMORY.md" ]]; then
    HERMES_MEMORY="$(cat "${HERMES_MEM_DIR}/MEMORY.md" 2>/dev/null || true)"
fi
if [[ -f "${HERMES_MEM_DIR}/USER.md" ]]; then
    HERMES_USER="$(cat "${HERMES_MEM_DIR}/USER.md" 2>/dev/null || true)"
fi

has_hermes=false
if [[ -n "${HERMES_MEMORY}" || -n "${HERMES_USER}" ]]; then
    has_hermes=true
    echo "[bridge] Found Hermes memory at ${HERMES_MEM_DIR}"
fi

# ---------------------------------------------------------------------------
# 2. Read Claude Code auto-memory (per-session memory files)
# ---------------------------------------------------------------------------
CLAUDE_AUTO_MEMORY=""
# Find Claude auto-memory — try common locations
for pattern in \
    "${HOME}/.claude/projects/-mnt-local-analysis-workspace-hub/memory/MEMORY.md" \
    "${REPO_ROOT}/.claude/MEMORY.md" \
    "${HOME}/.claude/projects/*/memory/MEMORY.md"
do
    # Expand the glob
    for f in ${pattern}; do
        if [[ -f "$f" ]]; then
            echo "[bridge] Found Claude auto-memory: $f"
            CLAUDE_AUTO_MEMORY="$(cat "$f" 2>/dev/null || true)"
            if [[ -n "${CLAUDE_AUTO_MEMORY}" ]]; then
                break 2
            fi
        fi
    done
done

# ---------------------------------------------------------------------------
# 3. Generate .claude/memory/agents.md
# ---------------------------------------------------------------------------
AGENTS_FILE="${MEMORY_DIR}/agents.md"
AGENTS_EXISTS=false
if [[ -f "${AGENTS_FILE}" ]]; then
    AGENTS_EXISTS=true
    AGENTS_EXISTING="$(cat "${AGENTS_FILE}")"
fi

cat > "${AGENTS_FILE}" << 'AGENTS_HEADER'
# Agent Workflow Facts

> Git-tracked. Applies to all AI agents working in this repo on any machine.
# Auto-generated by scripts/memory/bridge-hermes-claude.sh

AGENTS_HEADER

if [[ -n "${HERMES_MEMORY}" && "${has_hermes}" = true ]]; then
    {
        echo "## Extracted from Hermes Memory (${TIMESTAMP})"
        echo ""
        # Copy non-empty sections verbatim as bullet points
        echo "${HERMES_MEMORY}" | while IFS= read -r line; do
            [[ -z "${line}" ]] && continue
            [[ "${line}" == "§" ]] && echo "" && continue
            echo "- ${line}"
        done
        echo ""
    } >> "${AGENTS_FILE}"
fi

if [[ -n "${HERMES_USER}" ]]; then
    {
        echo "## Extracted from Hermes User Profile (${TIMESTAMP})"
        echo ""
        echo "${HERMES_USER}" | while IFS= read -r line; do
            [[ -z "${line}" ]] && continue
            [[ "${line}" == "§" ]] && echo "" && continue
            echo "- ${line}"
        done
        echo ""
    } >> "${AGENTS_FILE}"
fi

cat >> "${AGENTS_FILE}" << 'AGENTS_FOOTER'
---

## User

Vamsee Achanta — Professional Engineer (P.E.), 23 years experience.
Runs ACE Engineer consulting (aceengineer.com).
Target: $120K/yr retainers, 3-5 clients = $360-600K ARR.
GTM: offshore engineering firms with 10-50 engineers.
Core expertise: OrcaFlex, mooring/riser, FEA, cathodic protection, API 579, Python automation.

## AI Subscriptions (budget context)

| Agent | Cost | Notes |
|-------|------|-------|
| Claude Max | $200/mo | Primary; Claude Code CLI |
| Codex / OpenAI #1 | $20/mo | Cross-review, overnight batch |
| Codex / OpenAI #2 | $20/mo | Parallel overnight runs |
| Gemini Google AI Pro | $19.99/mo | Cross-review; needs `--yolo` flag |
| **Total** | **$269/mo** | Maximize all — no unused slots |

Context parity = compute parity. Zero waste everywhere.

## Workflow Rules

- **Overnight batch**: 3 self-contained prompts, one per terminal, zero git contention.
  Always include a git contention avoidance map (which terminal writes which files).
- **Adversarial review**: BOTH stages — plan review AND code/artifact review.
  Minimum: Claude + Codex + Gemini all review.
- **Context parity**: Corrections made in one agent must propagate to all others.
- **No local task IDs**: Use GitHub issues directly (`gh issue list`).
- **Issue comments**: Always post a summary comment on every implemented GitHub issue.
- **Parallel work check**: Scan for in-flight sessions before starting GSD work.

## GSD Workflow

GSD is the sole workflow system since 2026-03-25.
- Plans live in `.planning/` within each repo
- Long-duration plans live in `docs/plans/`
- Use `/gsd:*` commands for task management

## Skill System (Hermes)

Hermes maintains 691+ skills at `~/.hermes/skills/` on ace-linux-1.
On non-Hermes machines, consult `.claude/skills/` in this repo for equivalent procedures.

## ACE Engineer GTM Context

- `aceengineer-strategy/` — private nested repo with full GTM strategy
- 20+ prospects identified; ICP: offshore firms 10-50 engineers
- Demo reports: `digitalmodel/examples/demos/gtm/` (5 demos, `report_template.py`)
- Job market scanner: `scripts/gtm/job-market-scanner.py` (runs Monday cron)
AGENTS_FOOTER

CHANGES=1

# ---------------------------------------------------------------------------
# 4. Generate .claude/memory/context.md
# ---------------------------------------------------------------------------
cat > "${MEMORY_DIR}/context.md" << 'CONTEXT_EOF'
# Cross-Machine Context

> Git-tracked. Travels with the repo.
> Source of truth for environment conventions on every machine that clones workspace-hub.

## Machines

| Machine | OS | Hermes | Python cmd | Workspace root |
|---------|----|--------|------------|----------------|
| ace-linux-1 | Linux | YES | `uv run` | `/mnt/local-analysis/workspace-hub` |
| licensed-win-1 | Windows | NO | `python` | `D:\workspace-hub` |

## Python Command Rule

- **Linux**: ALWAYS `uv run` — never bare `python3` or `pip`
- **Windows**: Use `python` — uv is NOT installed on licensed-win-1

## Workspace Layout (Linux)

- `/mnt/local-analysis/workspace-hub/` — the real git repo mount
- `~/workspace-hub` — **sparse overlay** on ace-linux-1; writes may fail silently
  - If a write via tool fails: write to `/tmp/` first, then `mv` via terminal to the real mount
- `digitalmodel/` — **separate git repo** (vamseeachanta/digitalmodel.git), gitignored by parent
  - Commits MUST be made from inside `digitalmodel/` — not from workspace-hub root
- `aceengineer-strategy/` — private GTM strategy repo, nested, gitignored by parent
- `worldenergydata/` — energy data sub-repo

## Windows Path Conventions

- MINGW64 bash: paths use `/d/workspace-hub/` (not `D:\workspace-hub`)
- `core.symlinks=false` — git treats junctions as dirs; never commit symlinks cross-platform
- Shell scripts: `#!/usr/bin/env bash`, LF line endings

## Memory Sync Model

Memory travels with the repo via git. No Hermes needed on Windows.

1. **Hermes (ace-linux-1)**: Writes authoritative facts to `~/.hermes/memories/`
2. **Bridge script** (`scripts/memory/bridge-hermes-claude.sh`): Reads Hermes memory,
   writes canonical entries into `.claude/memory/` files in this repo, commits and pushes
3. **Windows (licensed-win-1)**: `git pull` — gets updated `.claude/memory/` automatically.
   Claude Code reads these files at session start.
4. **Return enrichment**: Any new lessons learned on Windows go into `.claude/memory/KNOWLEDGE.md`
   or topic files, committed and pushed. Next `git pull` on Linux picks them up.

There is no special sync tool. Git IS the sync mechanism.

## Legal Compliance

- `.legal-deny-list.yaml` — 15 client name patterns, repo root
- Run `scripts/legal/legal-sanity-scan.sh` before committing any generated documents
- Catalogs (`dde-*`, `conference-*`) are excluded from scanning (they legitimately reference client folders)
- MANDATORY for all document-intelligence and resource work
CONTEXT_EOF

CHANGES=1

# ---------------------------------------------------------------------------
# 5. Generate .claude/memory/claude-auto-memory.md (snapshot of Claude's memory)
# ---------------------------------------------------------------------------
if [[ -n "${CLAUDE_AUTO_MEMORY}" ]]; then
    cat > "${MEMORY_DIR}/claude-auto-memory.md" << CLAUDE_HEADER
# Claude Code Auto-Memory Snapshot

> Git-tracked snapshot of Claude Code's auto-generated MEMORY.md.
> Last captured: ${TIMESTAMP}
> Source: Claude Code session memory directory (~/.claude/projects/*/memory/)
>
> This file exists because Claude Code's auto-memory (40+ topic files per project)
> contains feedback, preferences, and project context that may not exist in Hermes
# memory. The bridge captures it so all machines have the same baseline.

## What This Is

Claude Code automatically creates memory files for:
- User feedback (e.g., "don't use local IDs", "use uv run")
- Project context (e.g., "GSD migration completed", "new solver queue")
- Working style preferences
- Reference information

These are captured here so machines WITHOUT Claude Code auto-memory (or different
Claude sessions) can still access this context.

## Claude Auto-Memory Index

The source directory contains topic-specific .md files. See below for the
full MEMORY.md index from Claude Code.

CLAUDE_HEADER
    echo "${CLAUDE_AUTO_MEMORY}" >> "${MEMORY_DIR}/claude-auto-memory.md"
    CHANGES=1
else
    echo "[bridge] No Claude auto-memory found — skipping snapshot"
fi

# ---------------------------------------------------------------------------
# 6. Report
# ---------------------------------------------------------------------------
echo ""
echo "[bridge] Files updated in ${MEMORY_DIR}:"
for file in agents.md context.md claude-auto-memory.md; do
    if [[ -f "${MEMORY_DIR}/${file}" ]]; then
        lines=$(wc -l < "${MEMORY_DIR}/${file}")
        echo "  ✅ ${file} (${lines} lines)"
    fi
done
echo ""

# ---------------------------------------------------------------------------
# 7. Commit if there are changes (only run if --commit flag passed)
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--commit" ]]; then
    cd "${REPO_ROOT}"
    if git diff --quiet -- .claude/memory/; then
        echo "[bridge] No changes detected — nothing to commit"
    else
        echo "[bridge] Staging and committing changes..."
        git add .claude/memory/
        git commit -m "chore(memory): auto-refresh memory bridge (${TIMESTAMP})"
        echo "[bridge] Committed. Run 'git push' to sync to remote."
    fi
else
    echo "[bridge] Review above. Run with --commit to auto-commit."
    echo "[bridge] Or manually: git add .claude/memory/ && git commit -m '...'"
fi
