#!/usr/bin/env python3
"""curate-memory.py — Rule-based memory curation for workspace-hub context files.

Classifies each bullet in memory files into one of:
  memory-keep   — foundational invariant; stays in memory
  domain-doc    — belongs in a domain spec/doc, not memory
  skill-update  — should update a skill file
  archive       — stale or low-signal; archive candidate

Generates promotion candidates file only — does NOT modify memory files.

Usage:
    uv run --no-project python scripts/memory/curate-memory.py \\
        --memory-root ~/.claude/projects/.../memory/ \\
        [--candidates-dir .claude/state/candidates]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# ── Classification rules (ordered — first match wins) ────────────────────────

# memory-keep: foundational invariants — legal rules, confirmed arch decisions,
# test invocation commands, known gotchas with # keep marker
_MEMORY_KEEP_PATTERNS = [
    r"#\s*keep\b",                        # explicit keep marker
    r"\bNEVER\s+reference\b",             # legal prohibition
    r"\bNEVER\s+commit\b",                # security rule
    r"\blegal\b.*\bprohibit",             # legal compliance
    r"deny.?list",                         # deny list reference
    r"\buv run\b.*\bpytest\b",            # confirmed test invocation
    r"\bconfirmed\b.*\binvariant\b",
]

# domain-doc: module-specific refactor candidates, file path details,
# large codebase metrics
_DOMAIN_DOC_PATTERNS = [
    r"\d{3,}\s+lines?\b",                 # line count detail (e.g. "2700 lines")
    r"benchmark_plotter|report_generator|public_dataset",  # large file names
    r"P1 refactor candid",
    r"refactor candidate",
]

# skill-update: patterns, workflows, tool invocations that belong in skills
_SKILL_UPDATE_PATTERNS = [
    r"\bphase \d+\b.*\bskill\b",
    r"cron.*(skill|pipeline)",
    r"\bworkflow\b.*\bstep\b",
]

# archive: stale, done-WRK references, old sprint notes
_ARCHIVE_PATTERNS = [
    r"\bWRK-\d+\b.*(archived|done|closed|complete)",
    r"\bSPRINT\b.*\d{4}",
    r"(2025|2024)-\d{2}-\d{2}.*\bsprint\b",
]


def _classify(bullet: str) -> str:
    """Return classification string for a bullet line."""
    for pattern in _MEMORY_KEEP_PATTERNS:
        if re.search(pattern, bullet, re.IGNORECASE):
            return "memory-keep"
    for pattern in _ARCHIVE_PATTERNS:
        if re.search(pattern, bullet, re.IGNORECASE):
            return "archive"
    for pattern in _DOMAIN_DOC_PATTERNS:
        if re.search(pattern, bullet, re.IGNORECASE):
            return "domain-doc"
    for pattern in _SKILL_UPDATE_PATTERNS:
        if re.search(pattern, bullet, re.IGNORECASE):
            return "skill-update"
    return "memory-keep"  # conservative default — don't evict unknown bullets


def _read_topic_files(memory_root: Path) -> dict[Path, list[str]]:
    files: dict[Path, list[str]] = {}
    for f in sorted(memory_root.glob("*.md")):
        if f.name.startswith("compact-audit"):
            continue
        files[f] = f.read_text(encoding="utf-8").splitlines(keepends=True)
    return files


def curate(memory_root: Path, candidates_dir: Path) -> str:
    """Classify all bullets and write promotion-candidates.md. Returns report text."""
    topic_files = _read_topic_files(memory_root)
    lines_out: list[str] = [
        "# Memory Promotion Candidates\n\n",
        "Generated by curate-memory.py. Review and convert to WRK items as needed.\n\n",
    ]

    for fpath, lines in topic_files.items():
        file_entries: list[str] = []
        for line in lines:
            stripped = line.strip()
            if not stripped.startswith("-"):
                continue
            classification = _classify(stripped)
            if classification != "memory-keep":
                file_entries.append(
                    f"- Classification: **{classification}**\n"
                    f"  Source: {fpath.name}\n"
                    f"  Bullet: {stripped}\n\n"
                )
        if file_entries:
            lines_out.append(f"## {fpath.name}\n\n")
            lines_out.extend(file_entries)

    if len(lines_out) == 2:
        lines_out.append("_No promotion candidates found._\n")

    report = "".join(lines_out)

    candidates_dir.mkdir(parents=True, exist_ok=True)
    out_file = candidates_dir / "memory-promotion-candidates.md"
    tmp = out_file.with_suffix(".tmp")
    tmp.write_text(report, encoding="utf-8")
    tmp.replace(out_file)

    return report


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Classify memory bullets and generate promotion candidates."
    )
    parser.add_argument("--memory-root", required=True)
    parser.add_argument(
        "--candidates-dir",
        default=None,
        help="Directory for memory-promotion-candidates.md",
    )
    args = parser.parse_args()

    memory_root = Path(args.memory_root).expanduser()
    if not memory_root.exists():
        print(f"ERROR: memory root does not exist: {memory_root}", file=sys.stderr)
        return 1

    if args.candidates_dir:
        candidates_dir = Path(args.candidates_dir).expanduser()
    else:
        # Default: .claude/state/candidates relative to workspace root
        candidates_dir = memory_root.parents[3] / ".claude" / "state" / "candidates"

    report = curate(memory_root, candidates_dir)
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
