"""Constants promoter — extracts name=value pairs and renders a Python module."""

import re
from pathlib import Path
from typing import List, Optional

from scripts.data.doc_intelligence.promoters.coordinator import (
    PromoteResult,
    register_promoter,
)
from scripts.data.doc_intelligence.promoters.text_utils import (
    content_hash,
    sanitize_identifier,
    source_citation,
    write_atomic,
)

# Regex: "name = value unit" with optional negative/scientific notation
_CONSTANT_RE = re.compile(
    r"^(.*?)\s*=\s*(-?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*(\S+)?"
)

OUTPUT_REL = Path(
    "digitalmodel/src/digitalmodel/naval_architecture/constants.py"
)


def _parse_constant(record: dict) -> Optional[dict]:
    """Extract name, value, unit from a record's text field.

    Returns a dict with keys: name, value, unit, text, source, domain.
    Returns None if the text does not match the expected pattern.
    """
    text = record.get("text", "")
    match = _CONSTANT_RE.search(text)
    if not match:
        return None

    raw_name = match.group(1).strip()
    value = match.group(2)
    unit = match.group(3) or ""

    name = sanitize_identifier(raw_name).upper()
    if not name:
        return None

    return {
        "name": name,
        "value": value,
        "unit": unit,
        "text": text,
        "source": record.get("source", {}),
        "domain": record.get("domain", ""),
    }


def _render_module(parsed: List[dict]) -> str:
    """Render parsed constants into a Python module string.

    Output format mirrors digitalmodel dynacard/constants.py:
    - content-hash header for idempotency
    - SCREAMING_SNAKE_CASE assignments
    - Docstrings with unit and source citation
    """
    if not parsed:
        return ""

    lines: list[str] = []

    # Module docstring
    lines.append('"""')
    lines.append("Naval Architecture Constants")
    lines.append("")
    lines.append("Auto-generated by doc-intelligence constants promoter.")
    lines.append("Do not edit manually — re-run the promoter to update.")
    lines.append('"""')
    lines.append("")

    # Group by domain (currently single domain, but future-proof)
    domains: dict[str, list[dict]] = {}
    for entry in parsed:
        d = entry.get("domain", "general")
        domains.setdefault(d, []).append(entry)

    for domain, entries in domains.items():
        header = domain.replace("-", " ").upper()
        lines.append(f"# {'=' * 77}")
        lines.append(f"# {header}")
        lines.append(f"# {'=' * 77}")
        lines.append("")

        for entry in entries:
            lines.append(f"{entry['name']} = {entry['value']}")
            doc_parts = [f'"""{entry["text"]}']
            if entry["unit"]:
                doc_parts.append(f"Unit: {entry['unit']}")
            citation = source_citation(entry["source"])
            doc_parts.append(f"Source: {citation}")
            doc_parts.append('"""')
            lines.append("\n".join(doc_parts))
            lines.append("")

    body = "\n".join(lines)

    # Prepend content-hash (computed over body without the hash line)
    h = content_hash(body)
    return f"# content-hash: {h}\n{body}"


def promote_constants(
    records: List[dict], project_root: Path, dry_run: bool = False
) -> PromoteResult:
    """Parse constant records and write a Python constants module.

    Args:
        records: JSONL records from constants.jsonl.
        project_root: Workspace root for output path resolution.
        dry_run: If True, report what would be written without writing.

    Returns:
        PromoteResult with written/skipped/error lists.
    """
    result = PromoteResult()

    parsed = []
    for rec in records:
        entry = _parse_constant(rec)
        if entry is not None:
            parsed.append(entry)

    if not parsed:
        return result

    content = _render_module(parsed)
    out_path = project_root / OUTPUT_REL

    written = write_atomic(out_path, content, dry_run=dry_run)
    target = str(out_path)
    if written:
        result.files_written.append(target)
    else:
        result.files_skipped.append(target)

    return result


register_promoter("constants", promote_constants)
