#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""catalog_delta.py — compute the weekly delta of Deckhand API paths (workflows).

Resolves the current public-safe API-path list from one of two sources and diffs
it against a saved snapshot (`state/api-catalog-snapshot.json`). Prints the weekly
delta as JSON.

Source resolution (`--source`, default `auto`):
  - canonical : read Deckhand's PUBLISHED public-safe catalog
                `deckhand/docs/deckhand/api-catalog.json` (generated by deckhand#501).
                This is the SINGLE SOURCE OF TRUTH — it is already projected to
                live_public + roadmap rows with private/internal reduced to a count.
  - derive    : derive the public-safe view from the routing catalog
                `domain-workflows.yaml` (legacy behaviour; used when the canonical
                artifact is absent).
  - auto      : PREFER `canonical` when the published artifact exists; otherwise
                FALL BACK to `derive`.

Both sources yield the SAME public-safe shape the rest of the skill consumes:
live_public + roadmap rows only (whitelisted generic fields), with private/internal
paths reduced to a de-identified `private_internal_count`. No client codenames are
ever parsed, persisted, or printed.

This is the read/compute helper for the `deckhand-api-presence-sync` skill. It has
NO side effects by default (does not write the snapshot, does not touch git/PRs).
Pass `--update-snapshot` ONLY after HITL draft PRs have been opened, per the skill.

Status derivation (single source of the live-vs-roadmap rule):
  - live_public  : artifact_residency == public-sandbox  -> publicly claimable
                   (has a public report.html on deckhand-sandbox)
  - live_private : artifact_residency == client-wiki      -> real delivery, NOT
                   publicly claimable (client-private)
  - internal     : artifact_residency == none             -> router/escalation only
  - roadmap      : a bound channel_domain with NO workflow row yet
                   ("owed later"; escalate-only). Listed, never claimed as capability.

Only `live_public` paths may be claimed on public presence surfaces
(resume / LinkedIn / website / README catalog counts).

Usage:
    uv run --no-project --with pyyaml python catalog_delta.py            # print delta JSON
    uv run --script catalog_delta.py --emit-current                     # print current paths only
    uv run --script catalog_delta.py --source canonical                 # force published catalog
    uv run --script catalog_delta.py --source derive                    # force derive-from-yaml
    uv run --script catalog_delta.py --canonical <path> --snapshot <p>  # override canonical input
    uv run --script catalog_delta.py --catalog <path> --snapshot <path> # override derive input
    uv run --script catalog_delta.py --update-snapshot                  # persist current (post-PR)
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

# --- Locations (no hardcoded absolute paths; resolve relative to this file) ---
# file -> deckhand-api-presence-sync(0) -> business-marketing(1) -> skills(2)
#      -> .claude(3) -> workspace-hub root(4)
THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_SNAPSHOT = THIS_DIR / "state" / "api-catalog-snapshot.json"
# Public report URL scheme for live_public paths (deckhand-sandbox GitHub Pages).
REPORT_URL_BASE = "https://vamseeachanta.github.io/deckhand-sandbox"

STATUS_BY_RESIDENCY = {
    "public-sandbox": "live_public",
    "client-wiki": "live_private",
    "none": "internal",
}

# This file lives in the PUBLIC workspace-hub repo. Only generic, publicly-safe
# rows may be persisted or printed: `live_public` paths (open public report URL)
# and `roadmap` domains (generic community names). Private/internal rows carry
# client scope codenames in their `ref`/`scope`/`description` and MUST NOT be
# written here — they are reduced to a de-identified aggregate count.
PUBLIC_SAFE_STATUSES = {"live_public", "roadmap"}
# Whitelisted keys for persisted/printed records — defense-in-depth against any
# future field that could carry a client identifier.
PUBLIC_SAFE_KEYS = (
    "ref", "kind", "channel_domain", "subdomains",
    "status", "claimable_public", "report_url_hint",
)


def public_safe(paths: list[dict]) -> list[dict]:
    """Project to publicly-safe records: drop private/internal rows entirely,
    and keep only whitelisted (generic) fields on the rows that remain."""
    out = []
    for p in paths:
        if p.get("status") not in PUBLIC_SAFE_STATUSES:
            continue
        out.append({k: p[k] for k in PUBLIC_SAFE_KEYS if k in p})
    return out


def private_internal_count(paths: list[dict]) -> int:
    """De-identified aggregate: how many paths exist that are NOT publicly safe."""
    return sum(1 for p in paths if p.get("status") not in PUBLIC_SAFE_STATUSES)


def _default_catalog() -> Path:
    """Resolve the Deckhand routing catalog without hardcoding an absolute path.

    Precedence: $DECKHAND_CATALOG > $DECKHAND_REPO/... > sibling ../deckhand.
    """
    import os

    if env := os.environ.get("DECKHAND_CATALOG"):
        return Path(env)
    rel = Path("config") / "deckhand" / "routing" / "domain-workflows.yaml"
    if repo := os.environ.get("DECKHAND_REPO"):
        return Path(repo) / rel
    return REPO_ROOT.parent / "deckhand" / rel


def _default_canonical() -> Path:
    """Resolve Deckhand's PUBLISHED public-safe catalog without hardcoding a path.

    Precedence: $DECKHAND_API_CATALOG > $DECKHAND_REPO/... > sibling ../deckhand.
    This is the canonical artifact `deckhand/docs/deckhand/api-catalog.json`
    generated by deckhand#501.
    """
    import os

    if env := os.environ.get("DECKHAND_API_CATALOG"):
        return Path(env)
    rel = Path("docs") / "deckhand" / "api-catalog.json"
    if repo := os.environ.get("DECKHAND_REPO"):
        return Path(repo) / rel
    return REPO_ROOT.parent / "deckhand" / rel


def load_catalog(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def extract_paths(catalog: dict) -> list[dict]:
    """Normalize workflow rows + uncovered bound domains into API-path records."""
    paths: list[dict] = []
    workflows = catalog.get("workflows", {}) or {}
    covered_domains: set[str] = set()

    for ref, wf in workflows.items():
        route = wf.get("route", {}) or {}
        residency = wf.get("artifact_residency", "none")
        status = STATUS_BY_RESIDENCY.get(residency, "internal")
        channel_domain = route.get("channel_domain")
        if channel_domain:
            covered_domains.add(channel_domain)
        desc = (wf.get("description") or "").strip().splitlines()
        record = {
            "ref": ref,
            "kind": "workflow",
            "scope": route.get("scope"),
            "channel_domain": channel_domain,
            "subdomains": route.get("subdomains"),
            "residency": residency,
            "status": status,
            "claimable_public": status == "live_public",
            "owner_repo": wf.get("owner_repo"),
            "description": desc[0] if desc else "",
        }
        if status == "live_public":
            record["report_url_hint"] = (
                f"{REPORT_URL_BASE}/.../{ref}/report.html"
            )
        paths.append(record)

    # Roadmap rows: bound channel domains with no workflow row yet ("owed later").
    bound = catalog.get("channel_domain_subdomains", {}) or {}
    for domain, subdomains in bound.items():
        if domain in covered_domains:
            continue
        paths.append({
            "ref": f"roadmap:{domain}",
            "kind": "roadmap",
            "scope": None,
            "channel_domain": domain,
            "subdomains": subdomains or [],
            "residency": "none",
            "status": "roadmap",
            "claimable_public": False,
            "owner_repo": "deckhand",
            "description": f"Bound channel domain '{domain}' — escalate-only, workflow row owed later.",
        })

    paths.sort(key=lambda r: r["ref"])
    return paths


def load_canonical(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def extract_paths_from_canonical(catalog: dict) -> list[dict]:
    """Normalize Deckhand's published public-safe catalog into the skill's internal
    path-record shape.

    The published artifact (`deckhand/docs/deckhand/api-catalog.json`) is ALREADY
    public-safe: it contains only `live_public` + `roadmap` rows and reduces every
    private/internal path to `private_internal_count`. We only re-key its generic
    fields onto the same internal names the rest of the skill consumes
    (`channel_domain`, `report_url_hint`). The downstream `public_safe()` projection
    still runs over these rows as defense-in-depth (status filter + key whitelist).
    """
    paths: list[dict] = []
    for rec in catalog.get("records", []) or []:
        record = {
            "ref": rec.get("ref"),
            "kind": rec.get("kind"),
            "scope": None,
            "channel_domain": rec.get("domain"),
            "subdomains": rec.get("subdomains") or [],
            "residency": None,
            "status": rec.get("status"),
            "claimable_public": bool(rec.get("claimable_public")),
            "owner_repo": rec.get("owner_repo"),
            "description": (rec.get("description") or "").strip(),
        }
        # Published live_public rows carry a `report_url_example`; map it onto the
        # internal `report_url_hint` key the rest of the skill references.
        if rec.get("report_url_example"):
            record["report_url_hint"] = rec["report_url_example"]
        paths.append(record)
    paths.sort(key=lambda r: r["ref"])
    return paths


def load_snapshot(path: Path) -> dict:
    if not path.exists():
        return {"paths": []}
    with open(path) as f:
        return json.load(f)


def compute_delta(current: list[dict], snapshot: dict) -> dict:
    prev_by_ref = {p["ref"]: p for p in snapshot.get("paths", [])}
    cur_by_ref = {p["ref"]: p for p in current}

    new_refs = [r for r in cur_by_ref if r not in prev_by_ref]
    removed_refs = [r for r in prev_by_ref if r not in cur_by_ref]
    # Status transitions (e.g., a roadmap row that became live_public).
    changed = []
    for r in cur_by_ref:
        if r in prev_by_ref and cur_by_ref[r]["status"] != prev_by_ref[r].get("status"):
            changed.append({
                "ref": r,
                "from": prev_by_ref[r].get("status"),
                "to": cur_by_ref[r]["status"],
            })

    new_paths = [cur_by_ref[r] for r in sorted(new_refs)]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "snapshot_as_of": snapshot.get("generated_at"),
        "counts": {
            "current_total": len(current),
            "current_live_public": sum(1 for p in current if p["status"] == "live_public"),
            "new": len(new_refs),
            "removed": len(removed_refs),
            "status_changed": len(changed),
        },
        "new_paths": new_paths,
        "new_live_public": [p for p in new_paths if p["status"] == "live_public"],
        "new_roadmap": [p for p in new_paths if p["status"] == "roadmap"],
        "removed_paths": [prev_by_ref[r] for r in sorted(removed_refs)],
        "status_changed": changed,
    }


SNAPSHOT_SOURCE_LABEL = {
    "canonical": "deckhand/docs/deckhand/api-catalog.json",
    "derive": "deckhand/config/deckhand/routing/domain-workflows.yaml",
}


def write_snapshot(path: Path, current_public: list[dict], *, private_count: int,
                   source_used: str = "derive") -> None:
    """Persist ONLY the publicly-safe projection (see PUBLIC_SAFE_STATUSES).
    `current_public` must already be the output of public_safe()."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": SNAPSHOT_SOURCE_LABEL.get(source_used, source_used),
        "note": "Public-safe projection — live_public + roadmap only; private/internal "
                "client paths are reduced to private_internal_count (no codenames).",
        "private_internal_count": private_count,
        "paths": current_public,
    }
    with open(path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")


def resolve_current(args) -> tuple[list[dict], int, str, Path]:
    """Resolve the current public-safe path list per `--source`.

    Returns (current_public, private_internal_count, source_used, source_path).
    Raises FileNotFoundError if the requested source artifact is absent.

    `auto` PREFERS the canonical published catalog and FALLS BACK to derive when
    that artifact is absent.
    """
    canonical_path = args.canonical or _default_canonical()
    catalog_path = args.catalog or _default_catalog()

    source = args.source
    if source == "auto":
        source = "canonical" if canonical_path.exists() else "derive"

    if source == "canonical":
        if not canonical_path.exists():
            raise FileNotFoundError(f"canonical catalog not found: {canonical_path}")
        catalog = load_canonical(canonical_path)
        current_full = extract_paths_from_canonical(catalog)
        # public_safe() is defense-in-depth: the published artifact is already
        # projected, but we still enforce the status filter + key whitelist.
        current = public_safe(current_full)
        # The published artifact carries the de-identified count directly; the raw
        # private/internal rows are intentionally absent (never published).
        priv_count = int(catalog.get("private_internal_count", 0))
        return current, priv_count, "canonical", canonical_path

    # derive (legacy): build the public-safe view from the routing catalog.
    if not catalog_path.exists():
        raise FileNotFoundError(f"routing catalog not found: {catalog_path}")
    catalog = load_catalog(catalog_path)
    current_full = extract_paths(catalog)
    current = public_safe(current_full)
    priv_count = private_internal_count(current_full)
    return current, priv_count, "derive", catalog_path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", choices=("canonical", "derive", "auto"), default="auto",
                    help="Where to read the current catalog from. 'canonical' = Deckhand's "
                         "published api-catalog.json (single source of truth); 'derive' = "
                         "build from domain-workflows.yaml; 'auto' (default) = prefer canonical, "
                         "fall back to derive.")
    ap.add_argument("--canonical", type=Path, default=None,
                    help="Path to the published api-catalog.json (default: sibling deckhand repo).")
    ap.add_argument("--catalog", type=Path, default=None,
                    help="Path to domain-workflows.yaml (default: sibling deckhand repo).")
    ap.add_argument("--snapshot", type=Path, default=DEFAULT_SNAPSHOT,
                    help="Path to api-catalog-snapshot.json.")
    ap.add_argument("--emit-current", action="store_true",
                    help="Print the current normalized path list and exit (no diff).")
    ap.add_argument("--update-snapshot", action="store_true",
                    help="Persist current paths to the snapshot. Use ONLY after PRs are opened.")
    args = ap.parse_args(argv)

    try:
        current, priv_count, source_used, source_path = resolve_current(args)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.emit_current:
        json.dump(
            {
                "source": source_used,
                "source_path": str(source_path),
                "private_internal_count": priv_count,
                "paths": current,
            },
            sys.stdout, indent=2,
        )
        sys.stdout.write("\n")
        return 0

    snapshot = load_snapshot(args.snapshot)
    delta = compute_delta(current, snapshot)
    delta["counts"]["private_internal_count"] = priv_count
    json.dump(delta, sys.stdout, indent=2)
    sys.stdout.write("\n")

    c = delta["counts"]
    print(
        f"\n[delta] source={source_used} public={c['current_total']} "
        f"live_public={c['current_live_public']} private_internal={priv_count} "
        f"new={c['new']} removed={c['removed']} status_changed={c['status_changed']}",
        file=sys.stderr,
    )

    if args.update_snapshot:
        write_snapshot(args.snapshot, current, private_count=priv_count,
                       source_used=source_used)
        print(f"[snapshot] updated {args.snapshot} (source={source_used})", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
