#!/usr/bin/env bash
# consistency-weekly-check.sh — weekly orchestrator-consistency matrix + rolling drift
# issue (#2841 Phase C, the standing check). Runs the per-machine probe + dream/read-back/
# SOUL/bridge checks, renders an orchestrators×dimensions matrix to a git-tracked docs path,
# and on any FAIL upserts ONE rolling `consistency-drift` issue (never duplicates).
#
# Declared in config/scheduled-tasks/schedule-tasks.yaml (id: consistency-weekly-check,
# dev-primary only, Sun 06:00). Exits non-zero on drift so cron-health flags it.
#
# Test seams: GH_CMD (mock gh), CONSISTENCY_SELFTEST_FAILS (bypass real checks).
set -uo pipefail

REPO_ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel 2>/dev/null || echo /mnt/local-analysis/workspace-hub)"
GH_CMD="${GH_CMD:-gh}"
DRIFT_LABEL="consistency-drift"
DATE="$(date -u +%Y-%m-%d)"
OUT_DIR="${REPO_ROOT}/docs/orchestrator-consistency"      # git-tracked (NOT reports/ — gitignored)
MATRIX="${OUT_DIR}/${DATE}-matrix.md"
DEADLETTER="${HOME:-/nonexistent}/.claude/projects/-mnt-local-analysis-workspace-hub/memory/.provider-bridge-deadletter.jsonl"
BRIDGE_LOG_DIR="${REPO_ROOT}/logs/orchestrator/memory-bridge"
SCHED="${REPO_ROOT}/config/scheduled-tasks/schedule-tasks.yaml"

fails=0
declare -a ROWS
row() { ROWS+=("| ${1} | ${2} | ${3} |"); [[ "${2}" == FAIL ]] && fails=$((fails+1)); return 0; }

run_checks() {
    # 1. Per-machine probe (Hermes lane: harness/memory/routing/skills/auth/bridges)
    if bash "${REPO_ROOT}/scripts/readiness/hermes-consistency-check.sh" >/dev/null 2>&1; then
        row "Hermes probe (#2860)" PASS "harness/memory/routing/skills/auth/bridges all PASS"
    else
        row "Hermes probe (#2860)" FAIL "hermes-consistency-check.sh reported FAIL — run it for detail"
    fi
    # 2. SOUL runtime drift across all providers
    if bash "${REPO_ROOT}/scripts/enforcement/check-soul-runtime-drift.sh" --quiet >/dev/null 2>&1; then
        row "SOUL runtime drift" PASS "committed runtimes match rebuild"
    else
        row "SOUL runtime drift" FAIL "runtimes != rebuild — bash scripts/agents/build-soul-runtime.sh && commit"
    fi
    # 3. Dream dead-letters (#2845): any line = silently-lost-before-fix sessions
    if [[ -f "${DEADLETTER}" ]] && [[ -s "${DEADLETTER}" ]]; then
        local n; n=$(wc -l < "${DEADLETTER}" | tr -d ' ')
        row "Dream dead-letters (#2845)" FAIL "${n} dead-lettered batch(es) — inspect .provider-bridge-deadletter.jsonl"
    else
        row "Dream dead-letters (#2845)" PASS "none"
    fi
    # 4. Read-back freshness (F8: bridge cron-LOG recency, NOT artifact mtime — a fresh
    #    git pull resets file mtime). A bridge log written within 8 days = slice regenerated.
    if find "${BRIDGE_LOG_DIR}" -name '*.log' -mtime -8 2>/dev/null | grep -q .; then
        row "Read-back freshness" PASS "memory bridge ran within 8 days"
    else
        row "Read-back freshness" FAIL "no memory-bridge run in 8 days — read-back slices may be stale"
    fi
    # 5. Bridges + this check declared in the single-source schedule
    local missing=""
    for id in provider-dream-bridge hermes-claude-bridge consistency-weekly-check; do
        grep -qE "id:[[:space:]]*${id}\b" "${SCHED}" 2>/dev/null || missing="${missing} ${id}"
    done
    if [[ -z "${missing}" ]]; then
        row "Cron declared in schedule-tasks.yaml" PASS "provider-dream-bridge, hermes-claude-bridge, consistency-weekly-check"
    else
        row "Cron declared in schedule-tasks.yaml" FAIL "undeclared:${missing}"
    fi
}

# Test seam: bypass real checks with a forced fail count. GATED on an explicit
# CONSISTENCY_SELFTEST=1 marker (F7) so a leaked/inherited CONSISTENCY_SELFTEST_FAILS
# can NEVER silently neuter a real run into a falsely-clean matrix.
if [[ "${CONSISTENCY_SELFTEST:-}" == "1" && -n "${CONSISTENCY_SELFTEST_FAILS:-}" ]]; then
    fails="${CONSISTENCY_SELFTEST_FAILS}"
    if [[ "${fails}" -gt 0 ]]; then row "selftest" FAIL "forced ${fails}"; else row "selftest" PASS "forced clean"; fi
else
    run_checks
fi

# ── Render the matrix (always; git-tracked) ──
mkdir -p "${OUT_DIR}"
{
    echo "# Orchestrator consistency matrix — ${DATE}"
    echo
    echo "> Auto-generated by scripts/cron/consistency-weekly-check.sh (#2841). Lanes: Claude / Codex+Hermes (2 quota-independent lanes)."
    echo
    echo "| Check | Result | Detail |"
    echo "|---|---|---|"
    printf '%s\n' "${ROWS[@]}"
    echo
    echo "**Overall: $([[ ${fails} -eq 0 ]] && echo PASS || echo "DRIFT — ${fails} failing check(s)")**"
} > "${MATRIX}"
echo "[consistency-check] matrix → ${MATRIX#${REPO_ROOT}/} (fails=${fails})"

# ── On drift: upsert ONE rolling issue ──
if [[ "${fails}" -gt 0 ]]; then
    # ensure label exists BEFORE --label use (F6)
    if ! ${GH_CMD} label list --json name -q '.[].name' 2>/dev/null | grep -qx "${DRIFT_LABEL}"; then
        ${GH_CMD} label create "${DRIFT_LABEL}" --description "weekly orchestrator-consistency drift (#2841)" --color D93F0B >/dev/null 2>&1 || true
    fi
    existing="$(${GH_CMD} issue list --label "${DRIFT_LABEL}" --state open --json number -q '.[0].number' 2>/dev/null || true)"
    if [[ -n "${existing}" ]]; then
        ${GH_CMD} issue edit "${existing}" --body-file "${MATRIX}" >/dev/null 2>&1 || true
        echo "[consistency-check] DRIFT — updated rolling issue #${existing}"
    else
        ${GH_CMD} issue create --title "Orchestrator consistency drift (${DATE})" \
            --label "${DRIFT_LABEL}" --body-file "${MATRIX}" >/dev/null 2>&1 || true
        echo "[consistency-check] DRIFT — opened rolling consistency-drift issue"
    fi
    exit 1
fi

echo "[consistency-check] all consistent."
exit 0
