#!/usr/bin/env bash
# control-plane-drift.sh — Quarterly audit of control-plane contract drift.
# Issue: #2317 (https://github.com/vamseeachanta/workspace-hub/issues/2317)
# Companion: #1525 (canonical repo control-plane contract)
# Contract: docs/standards/CONTROL_PLANE_CONTRACT.md
#
# Walks child repos under the scan root and checks each for the required
# control-plane artifacts (AGENTS.md, CLAUDE.md, .claude/, .codex/, .gemini/).
# Repos missing any required artifact are flagged for remediation.
#
# Env overrides (testing):
#   CONTROL_PLANE_OUT_DIR       — override docs/reports output dir
#   CONTROL_PLANE_QUARTER       — override quarter (e.g. 2026-Q2)
#   CONTROL_PLANE_SCAN_ROOT     — override scan root (default REPO_ROOT)
#   CONTROL_PLANE_WARN_COUNT    — warn threshold (default 0; band is value>warn)
#   CONTROL_PLANE_BLOCK_COUNT   — block threshold (default 5; band is value>block)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/cadence-common.sh"
cadence_init_repo_root

QUARTER="${CONTROL_PLANE_QUARTER:-$(cadence_period quarterly)}"
OUT_DIR="${CONTROL_PLANE_OUT_DIR:-${REPO_ROOT}/docs/reports}"
OUT="${OUT_DIR}/control-plane-drift-${QUARTER}.md"
SCAN_ROOT="${CONTROL_PLANE_SCAN_ROOT:-${REPO_ROOT}}"
WARN_COUNT="${CONTROL_PLANE_WARN_COUNT:-0}"
BLOCK_COUNT="${CONTROL_PLANE_BLOCK_COUNT:-5}"

# Required artifacts per CONTROL_PLANE_CONTRACT.md v1.0.0 (section: Provider Adapters).
REQUIRED=(AGENTS.md CLAUDE.md .claude .codex .gemini)

mkdir -p "$OUT_DIR"

TMP_ROWS="$(mktemp)"
TMP_REMED="$(mktemp)"
trap 'rm -f "$TMP_ROWS" "$TMP_REMED"' EXIT

drift_count=0
repo_count=0

for dir in "$SCAN_ROOT"/*/; do
    [[ -d "${dir}.git" ]] || continue
    name="$(basename "$dir")"
    repo_count=$((repo_count + 1))

    cells=""
    missing=()
    for f in "${REQUIRED[@]}"; do
        if [[ -e "${dir}${f}" ]]; then
            cells+="| ✅ "
        else
            cells+="| ❌ "
            missing+=("$f")
        fi
    done

    if (( ${#missing[@]} == ${#REQUIRED[@]} )); then
        summary="uninitialized"
        drift_count=$((drift_count + 1))
    elif (( ${#missing[@]} > 0 )); then
        summary="missing: $(IFS=,; echo "${missing[*]}")"
        drift_count=$((drift_count + 1))
    else
        summary="OK"
    fi

    printf "| %s %s| %s |\n" "$name" "$cells" "$summary" >> "$TMP_ROWS"

    if [[ "$summary" != "OK" ]]; then
        for m in "${missing[@]}"; do
            case "$m" in
                AGENTS.md)  fix="create \`AGENTS.md\` using template from CONTROL_PLANE_CONTRACT.md §Entry Point" ;;
                CLAUDE.md)  fix="create root \`CLAUDE.md\` (may be a short adapter importing AGENTS.md)" ;;
                .claude)    fix="scaffold \`.claude/\` with rules/, skills/, CLAUDE.md" ;;
                .codex)     fix="scaffold \`.codex/\` (minimal acceptable: empty dir)" ;;
                .gemini)    fix="scaffold \`.gemini/\` (minimal acceptable: empty dir)" ;;
                *)          fix="add \`$m\`" ;;
            esac
            printf "| %s | %s | %s |\n" "$name" "$m" "$fix" >> "$TMP_REMED"
        done
    fi
done

status="$(compute_status_band "$drift_count" "$WARN_COUNT" "$BLOCK_COUNT")"
summary="${drift_count}/${repo_count} child repos drift from canonical contract (warn ${WARN_COUNT}, block ${BLOCK_COUNT})"

# ── Write report ─────────────────────────────────────────────────────────
{
    emit_report_header "control-plane-drift" "$QUARTER" "$status" "$summary"
    echo "Contract: [\`docs/standards/CONTROL_PLANE_CONTRACT.md\`](../standards/CONTROL_PLANE_CONTRACT.md) v1.0.0"
    echo "Scan root: \`${SCAN_ROOT}\`"
    echo

    echo "## Per-repo drift status"
    echo
    echo "| Repo | AGENTS.md | CLAUDE.md | .claude | .codex | .gemini | Drift summary |"
    echo "|------|:---------:|:---------:|:-------:|:------:|:-------:|---------------|"
    if [[ -s "$TMP_ROWS" ]]; then
        cat "$TMP_ROWS"
    else
        echo "| — | — | — | — | — | — | _(no child repos found)_ |"
    fi
    echo

    echo "## Remediation plan (per drifted repo)"
    echo
    if [[ -s "$TMP_REMED" ]]; then
        echo "| Repo | Missing | Suggested fix |"
        echo "|------|---------|---------------|"
        cat "$TMP_REMED"
    else
        echo "_All child repos match the canonical contract._"
    fi
    echo

    echo "## Source"
    echo
    echo "Generated by \`scripts/cron/control-plane-drift.sh\` (#2317, companion #1525)."
} > "$OUT"

echo "[control-plane-drift] wrote $OUT (status: $status, drift ${drift_count}/${repo_count})"
