"""Cron managed-block parsing, preservation fingerprints, and line classification."""
from __future__ import annotations

import re
import shlex
from pathlib import Path

MARKER_BEGIN_RE = re.compile(
    r"^# >>> workspace-hub managed \(role: (?P<roles>.*?)\) — generated by "
    r"setup-cron\.sh, do not edit >>>$"
)
MARKER_END = "# <<< workspace-hub managed <<<"
_ENV_LINE_RE = re.compile(r"^[A-Z_]+=")
_FINGERPRINT_KEYS = {
    "command_contains", "command_tokens", "cwd_contains", "cwd_basename",
    "script_basename",
}


def marker_begin(roles: list[str]) -> str:
    joined = "+".join(roles)
    return (
        f"# >>> workspace-hub managed (role: {joined}) — generated by "
        f"setup-cron.sh, do not edit >>>"
    )


def parse_crontab(text: str) -> dict:
    """Split a crontab around one balanced managed block."""
    lines = text.split("\n")
    trailing = bool(lines and lines[-1] == "")
    if trailing:
        lines = lines[:-1]
    begin = [i for i, line in enumerate(lines) if MARKER_BEGIN_RE.match(line)]
    end = [i for i, line in enumerate(lines) if line == MARKER_END]
    error = _marker_error(begin, end)
    if error:
        return _parse_result(lines, [], [], None, error, trailing)
    if not begin:
        return _parse_result(lines, [], [], None, None, trailing)
    b, e = begin[0], end[0]
    if e < b:
        return _parse_result(lines, [], [], None, "end marker appears before begin marker", trailing)
    match = MARKER_BEGIN_RE.match(lines[b])
    return _parse_result(
        lines[:b], lines[b + 1:e], lines[e + 1:],
        match.group("roles") if match else None, None, trailing,
    )


def _marker_error(begin: list[int], end: list[int]) -> str | None:
    if len(begin) > 1:
        return "multiple begin markers found"
    if len(end) > 1:
        return "multiple end markers found"
    if len(begin) != len(end):
        return "unbalanced markers: begin without matching end (or vice versa)"
    return None


def _parse_result(before, managed, after, roles, error, trailing) -> dict:
    return {
        "before": before, "managed": managed, "after": after, "roles": roles,
        "error": error, "_trailing_newline": trailing,
    }


def match_fingerprint(line: str, fingerprint: dict) -> bool:
    """Return true only when every declared fingerprint component matches."""
    if not fingerprint:
        return False
    checks = []
    if "command_contains" in fingerprint:
        checks.append(_all_substrings(line, fingerprint["command_contains"]))
    if "command_tokens" in fingerprint:
        checks.append(_tokens_match(line, fingerprint["command_tokens"]))
    if "cwd_contains" in fingerprint:
        checks.append(fingerprint["cwd_contains"] in line)
    if "cwd_basename" in fingerprint:
        checks.append(_cwd_matches(line, fingerprint["cwd_basename"]))
    if "script_basename" in fingerprint:
        checks.append(fingerprint["script_basename"] in line)
    return bool(checks) and all(checks)


def _all_substrings(line: str, value) -> bool:
    items = value if isinstance(value, (list, tuple)) else [value]
    return all(item in line for item in items)


def _tokens_match(line: str, wanted: list[str]) -> bool:
    try:
        tokens = shlex.split(line)
    except ValueError:
        return False
    width = len(wanted)
    return bool(width) and any(
        tokens[index:index + width] == wanted
        for index in range(len(tokens) - width + 1)
    )


def _cwd_matches(line: str, expected: str) -> bool:
    match = re.search(r"(?:^|\s)cd\s+([^;&\s]+)", line)
    token = match.group(1).strip("'\"") if match else ""
    return token in ("$WORKSPACE_HUB", "${WORKSPACE_HUB}") or Path(token).name == expected


def normalize_preserved_entries(entries: list[dict] | None) -> list[dict]:
    """Normalize nested and legacy bare preservation fingerprints."""
    normalized = []
    for entry in entries or []:
        if not entry:
            continue
        if "fingerprint" in entry:
            fingerprint = entry.get("fingerprint") or {}
            record = dict(entry)
        else:
            fingerprint = {key: entry[key] for key in _FINGERPRINT_KEYS if key in entry}
            record = {key: value for key, value in entry.items() if key not in _FINGERPRINT_KEYS}
        if not fingerprint:
            continue
        record["fingerprint"] = dict(fingerprint)
        for key, value in fingerprint.items():
            record.setdefault(key, value)
        normalized.append(record)
    return normalized


def classify_line_detail(
    line: str,
    catalog_commands: list[str] | None = None,
    external_fingerprints: list[dict] | None = None,
    selected_task_ids: set[str] | None = None,
    catalog_fingerprints: list[dict] | None = None,
    ownership_context: dict | None = None,
) -> dict:
    """Classify one line without granting substring deletion authority."""
    if _is_ignore_line(line):
        return {"line": line, "class": "ignore", "reason": "ignore"}
    if ownership_context is not None:
        identity = ownership_context.get("line_identities", {}).get(line)
        if identity:
            return {
                "line": line, "class": "cataloged", "reason": identity["source"],
                "catalog_task_id": identity["catalog_task_id"],
                "variant_id": identity.get("variant_id", ""),
            }
        external_fingerprints = ownership_context.get("preservation_fingerprints", [])
    return _classify_preserved(line, external_fingerprints)


def _is_ignore_line(line: str) -> bool:
    stripped = line.strip()
    return not stripped or stripped.startswith("#") or bool(_ENV_LINE_RE.match(line))


def _classify_preserved(line: str, fingerprints) -> dict:
    for entry in normalize_preserved_entries(fingerprints):
        if match_fingerprint(line, entry.get("fingerprint", {})):
            return {
                "line": line, "class": "preserved_external",
                "reason": "preserved-fingerprint",
                "catalog_task_id": entry.get("catalog_task_id"),
                "preserved_entry": entry,
            }
    return {"line": line, "class": "uncataloged", "reason": "no-match"}


def classify_line(
    line: str, catalog_commands: list[str], external_fingerprints: list[dict],
    catalog_fingerprints: list[dict] | None = None,
) -> str:
    return classify_line_detail(
        line, catalog_commands, external_fingerprints,
        catalog_fingerprints=catalog_fingerprints,
    )["class"]
