#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Pure, testable core for the workspace-hub fail-closed crontab transaction.

This module contains NO file IO (except an optional __main__ self-check). All
functions take dict/str in and return dict/str/tuple out, so they are trivially
unit-testable and safe to wire into setup-cron.sh and cron-audit.py.

See issue #2969 — "F2: role-tagged cron catalog + safe cutover".
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from cron_render import render_cron_line

# --- Marker constants ------------------------------------------------------

# Begin marker e.g.:
#   # >>> workspace-hub managed (role: a+b) — generated by setup-cron.sh, do not edit >>>
MARKER_BEGIN_RE = re.compile(
    r"^# >>> workspace-hub managed \(role: (?P<roles>.*?)\) — generated by "
    r"setup-cron\.sh, do not edit >>>$"
)
MARKER_END = "# <<< workspace-hub managed <<<"

# An env/header line such as MAILTO=, SHELL=, PATH= at the start of the line.
_ENV_LINE_RE = re.compile(r"^[A-Z_]+=")
_SCRIPT_PATH_RE = re.compile(r"scripts/[\w./-]+\.(?:sh|py)")
_FINGERPRINT_KEYS = {
    "command_contains",
    "cwd_contains",
    "script_basename",
    "owner_repo",
}


def marker_begin(roles: list[str]) -> str:
    """Render the begin marker line for the given roles (joined by '+')."""
    joined = "+".join(roles)
    return (
        f"# >>> workspace-hub managed (role: {joined}) — generated by "
        f"setup-cron.sh, do not edit >>>"
    )


# --- Parsing ---------------------------------------------------------------


def parse_crontab(text: str) -> dict:
    """Split a crontab into before / managed / after around the managed block.

    Returns a dict with keys:
      before: list[str]   lines before the managed block (or all lines if none)
      managed: list[str]  lines strictly inside the block (markers excluded)
      after: list[str]    lines after the managed block
      roles: str | None   the roles string captured from the begin marker
      error: str | None   non-None means FAIL CLOSED — caller must not proceed

    Fail-closed conditions: more than one begin marker, a begin without a
    matching end (or vice-versa), or an end appearing before a begin.
    Zero markers is valid (block absent): everything goes in `before`.
    Every non-marker line is preserved verbatim (blanks, comments, env lines).
    """
    lines = text.split("\n")
    # Avoid a spurious trailing empty element from a final newline; we will
    # rejoin with "\n" so this preserves byte content faithfully.
    if lines and lines[-1] == "":
        lines = lines[:-1]
        had_trailing_newline = True
    else:
        had_trailing_newline = False

    begin_idxs: list[int] = []
    end_idxs: list[int] = []
    for i, line in enumerate(lines):
        if MARKER_BEGIN_RE.match(line):
            begin_idxs.append(i)
        elif line == MARKER_END:
            end_idxs.append(i)

    def _err(msg: str) -> dict:
        return {
            "before": lines,
            "managed": [],
            "after": [],
            "roles": None,
            "error": msg,
            "_trailing_newline": had_trailing_newline,
        }

    if len(begin_idxs) > 1:
        return _err("multiple begin markers found")
    if len(end_idxs) > 1:
        return _err("multiple end markers found")
    if len(begin_idxs) != len(end_idxs):
        return _err("unbalanced markers: begin without matching end (or vice versa)")

    if not begin_idxs:  # zero markers — valid, block absent
        return {
            "before": lines,
            "managed": [],
            "after": [],
            "roles": None,
            "error": None,
            "_trailing_newline": had_trailing_newline,
        }

    b = begin_idxs[0]
    e = end_idxs[0]
    if e < b:
        return _err("end marker appears before begin marker")

    m = MARKER_BEGIN_RE.match(lines[b])
    roles = m.group("roles") if m else None
    return {
        "before": lines[:b],
        "managed": lines[b + 1 : e],
        "after": lines[e + 1 :],
        "roles": roles,
        "error": None,
        "_trailing_newline": had_trailing_newline,
    }


# --- Fingerprinting & classification --------------------------------------


def match_fingerprint(line: str, fp: dict) -> bool:
    """Return True iff every specified fingerprint key matches `line`.

    Recognised keys (all optional; ALL present keys must match):
      command_contains: str | list[str]  every item must be a substring of line
      cwd_contains: str                   substring of line
      script_basename: str                substring of line
      owner_repo: str | list[str]         treated like command_contains
    An empty fingerprint never matches (returns False).
    """
    if not fp:
        return False

    checked_any = False

    def _all_substrings(value) -> bool:
        items = value if isinstance(value, (list, tuple)) else [value]
        return all(item in line for item in items)

    if "command_contains" in fp:
        checked_any = True
        if not _all_substrings(fp["command_contains"]):
            return False
    if "owner_repo" in fp:
        checked_any = True
        if not _all_substrings(fp["owner_repo"]):
            return False
    if "cwd_contains" in fp:
        checked_any = True
        if fp["cwd_contains"] not in line:
            return False
    if "script_basename" in fp:
        checked_any = True
        if fp["script_basename"] not in line:
            return False

    return checked_any


def normalize_preserved_entries(entries: list[dict] | None) -> list[dict]:
    """Return preserved-entry records while retaining owner/catalog metadata.

    Callers historically passed a bare fingerprint list. Newer state-class rows
    carry metadata beside a nested `fingerprint`. This normalizer accepts both
    forms and duplicates fingerprint keys at top level for older tests/callers
    that inspect them directly.
    """
    normalized: list[dict] = []
    for entry in entries or []:
        if not entry:
            continue
        if "fingerprint" in entry:
            fp = entry.get("fingerprint") or {}
            record = dict(entry)
        else:
            fp = {key: entry[key] for key in _FINGERPRINT_KEYS if key in entry}
            record = {key: value for key, value in entry.items() if key not in _FINGERPRINT_KEYS}
        if not fp:
            continue
        record["fingerprint"] = dict(fp)
        for key, value in fp.items():
            record.setdefault(key, value)
        normalized.append(record)
    return normalized


def _is_ignore_line(line: str) -> bool:
    stripped = line.strip()
    if stripped == "":
        return True
    if stripped.startswith("#"):
        return True
    if _ENV_LINE_RE.match(line):
        return True
    return False


def classify_line_detail(
    line: str,
    catalog_commands: list[str],
    external_fingerprints: list[dict],
    selected_task_ids: set[str] | None = None,
) -> dict:
    """Classify a crontab line with metadata for audit/cutover callers."""
    if _is_ignore_line(line):
        return {"line": line, "class": "ignore", "reason": "ignore"}

    selected = set(selected_task_ids or set())
    for entry in normalize_preserved_entries(external_fingerprints):
        if match_fingerprint(line, entry.get("fingerprint", {})):
            catalog_task_id = entry.get("catalog_task_id")
            if catalog_task_id and catalog_task_id in selected:
                return {
                    "line": line,
                    "class": "cataloged",
                    "reason": "catalog-owned-preserved-entry",
                    "catalog_task_id": catalog_task_id,
                    "preserved_entry": entry,
                }
            return {
                "line": line,
                "class": "preserved_external",
                "reason": "preserved-fingerprint",
                "catalog_task_id": catalog_task_id,
                "preserved_entry": entry,
            }

    for cmd in catalog_commands or []:
        if cmd and cmd in line:
            return {
                "line": line,
                "class": "cataloged",
                "reason": "catalog-command",
                "catalog_key": cmd,
            }
    return {"line": line, "class": "uncataloged", "reason": "no-match"}


def classify_line(
    line: str,
    catalog_commands: list[str],
    external_fingerprints: list[dict],
) -> str:
    """Classify a single crontab line.

    Returns one of:
      "ignore"             blank / comment / env-header line — callers skip it
      "preserved_external" an external fingerprint matches the line
      "cataloged"          a catalog command is a substring of the line
      "uncataloged"        none of the above (a live line we don't recognise)

    SAFETY ORDERING (#2969 code-review MAJOR): preserved_external is checked BEFORE
    cataloged. An externally-owned line (e.g. a deckhand cron) whose command happens to
    contain a catalog script-path substring must still be PRESERVED, never pulled into the
    managed block and dropped. Ownership (fingerprint) dominates substring coincidence.
    """
    return classify_line_detail(line, catalog_commands, external_fingerprints)["class"]


# --- Task selection --------------------------------------------------------


def select_tasks(
    tasks: list[dict],
    machine_roles: list[str],
    machine_id: str | set[str] | list[str] | tuple[str, ...],
) -> tuple[list[dict], list[dict]]:
    """Select catalog tasks for this machine by role and/or legacy machine pin.

    A task is selected if its `roles` intersect `machine_roles`, OR `machine_id`
    is in its legacy `machines` list. Deduped by task['id'].

    Conflict: role-match selects it, but a non-empty legacy `machines` list
    EXCLUDES this machine_id. Resolution: roles win iff
    `task.get('roles_authoritative')` is True; otherwise legacy wins (not
    selected). Conflicts are reported for auditing regardless of outcome.

    Returns (selected_tasks_sorted_by_id, conflicts) where each conflict is
    {"id": ..., "reason": ...}.
    """
    role_set = set(machine_roles or [])
    if isinstance(machine_id, str):
        machine_tokens = {machine_id}
    else:
        machine_tokens = set(machine_id or set())
    machine_tokens = {str(token).lower() for token in machine_tokens if str(token).strip()}
    selected_by_id: dict = {}
    conflicts: list[dict] = []

    for task in tasks or []:
        if task.get("scheduler", "cron") != "cron":
            continue
        tid = task.get("id")
        task_roles = set(task.get("roles", []) or [])
        machines = task.get("machines", None)
        has_machines = isinstance(machines, list) and len(machines) > 0
        machine_pin_tokens = {str(machine).lower() for machine in machines or []}

        role_match = bool(task_roles & role_set)
        legacy_match = bool(machine_pin_tokens & machine_tokens)
        legacy_excludes = has_machines and not legacy_match

        if role_match and legacy_excludes:
            # Conflict: roles say yes, legacy pin says no.
            authoritative = bool(task.get("roles_authoritative"))
            if authoritative:
                conflicts.append(
                    {
                        "id": tid,
                        "reason": "role-match vs legacy machines exclusion; "
                        "roles_authoritative=True → roles win (selected)",
                    }
                )
                selected_by_id[tid] = task
            else:
                conflicts.append(
                    {
                        "id": tid,
                        "reason": "role-match vs legacy machines exclusion; "
                        "roles_authoritative not set → legacy wins (not selected)",
                    }
                )
            continue

        if role_match or legacy_match:
            selected_by_id[tid] = task

    selected = sorted(selected_by_id.values(), key=lambda t: t.get("id"))
    return selected, conflicts


def _normalize_command(command: str) -> str:
    return " ".join(str(command).split())


def catalog_command_keys(
    tasks: list[dict],
    fallback_mode: str = "full-command",
) -> list[str]:
    """Return stable catalog keys for matching live cron lines.

    Prefer a repository-relative script token. When no script token exists, use
    the full normalized command. Do not truncate fallback keys: truncated keys
    collide and misclassify unrelated live lines.
    """
    keys: list[str] = []
    seen: set[str] = set()
    for task in tasks or []:
        command = _normalize_command(task.get("command", ""))
        if not command:
            continue
        match = _SCRIPT_PATH_RE.search(command)
        key = match.group(0) if match else command if fallback_mode == "full-command" else ""
        if key and key not in seen:
            keys.append(key)
            seen.add(key)
    return keys


# --- Rendering -------------------------------------------------------------


def render_block(tasks: list[dict], roles: list[str]) -> list[str]:
    """Render the managed block (begin marker + task lines + end marker).

    Task lines are "{schedule} {command}", sorted by id for determinism.
    Idempotent: same input → same output.
    """
    sorted_tasks = sorted(tasks or [], key=lambda t: t.get("id"))
    lines = [marker_begin(roles)]
    for task in sorted_tasks:
        lines.append(render_cron_line(task["schedule"], task["command"]))
    lines.append(MARKER_END)
    return lines


# --- Cutover planning ------------------------------------------------------


def plan_cutover(
    current_text: str,
    selected_tasks: list[dict],
    roles: list[str],
    catalog_commands: list[str],
    external_fingerprints: list[dict],
    selected_task_ids: set[str] | None = None,
) -> dict:
    """Plan a fail-closed crontab cutover.

    Steps:
      1. parse_crontab; on parse error abort.
      2. classify every non-managed line; abort on any "uncataloged" line.
      3. Rebuild: before-lines + freshly-rendered managed block + after-lines,
         preserving the old block's position (appended if no block existed).

    Returns:
      {
        "new_text": str | None,
        "preserved": list[str],   non-block lines that survive verbatim
        "uncataloged": list[str], offending lines (only when aborting on step 2)
        "conflicts": list,        reserved (select_tasks owns conflicts; [])
        "abort_reason": str | None,
      }

    Idempotent: plan_cutover applied to its own output yields byte-identical
    new_text.
    """
    parsed = parse_crontab(current_text)
    if parsed["error"]:
        return {
            "new_text": None,
            "preserved": [],
            "uncataloged": [],
            "conflicts": [],
            "abort_reason": parsed["error"],
        }

    had_block = bool(parsed["before"]) or bool(parsed["after"]) or bool(
        parsed["managed"]
    ) or parsed["roles"] is not None
    # We detect whether a block existed by whether parse split anything into
    # `after` or whether roles is not None (a real begin marker was seen).
    block_existed = parsed["roles"] is not None

    non_managed = list(parsed["before"]) + list(parsed["after"])

    uncataloged: list[str] = []
    preserved: list[str] = []
    for line in non_managed:
        cls = classify_line_detail(
            line,
            catalog_commands,
            external_fingerprints,
            selected_task_ids=selected_task_ids,
        )["class"]
        if cls == "ignore":
            preserved.append(line)
        elif cls == "preserved_external":
            preserved.append(line)
        elif cls == "cataloged":
            # Cataloged lines outside the block are dropped — they belong inside
            # the freshly-rendered managed block. (Stale duplicate.)
            continue
        else:  # uncataloged
            uncataloged.append(line)

    if uncataloged:
        return {
            "new_text": None,
            "preserved": preserved,
            "uncataloged": uncataloged,
            "conflicts": [],
            "abort_reason": f"uncataloged live cron line(s): {uncataloged}",
        }

    block = render_block(selected_tasks, roles)

    # Reconstruct, keeping the block in its prior position. `before` keeps only
    # preserved/ignore lines (cataloged stale lines removed); same for `after`.
    def _filter(lines: list[str]) -> list[str]:
        out = []
        for line in lines:
            cls = classify_line_detail(
                line,
                catalog_commands,
                external_fingerprints,
                selected_task_ids=selected_task_ids,
            )["class"]
            if cls == "cataloged":
                continue
            out.append(line)
        return out

    if block_existed:
        new_lines = _filter(parsed["before"]) + block + _filter(parsed["after"])
    else:
        # No prior block — append the block after all existing (filtered) lines.
        new_lines = _filter(parsed["before"]) + block

    new_text = "\n".join(new_lines)
    if parsed.get("_trailing_newline"):
        new_text += "\n"

    return {
        "new_text": new_text,
        "preserved": preserved,
        "uncataloged": [],
        "conflicts": [],
        "abort_reason": None,
    }


if __name__ == "__main__":
    # Optional thin self-check (no external IO).
    sample = "MAILTO=ops@example.com\n0 * * * * echo hi\n"
    tasks = [{"id": "b", "schedule": "0 1 * * *", "command": "run-b"},
             {"id": "a", "schedule": "0 2 * * *", "command": "run-a"}]
    sel, conflicts = select_tasks(tasks, ["worker"], "host1")
    plan = plan_cutover(
        sample,
        tasks,
        ["worker"],
        catalog_commands=["echo hi"],
        external_fingerprints=[],
    )
    print("self-check abort_reason:", plan["abort_reason"])
    print(plan["new_text"])
    # Idempotency probe.
    plan2 = plan_cutover(
        plan["new_text"], tasks, ["worker"],
        catalog_commands=["echo hi"], external_fingerprints=[],
    )
    print("idempotent:", plan["new_text"] == plan2["new_text"])
