#!/usr/bin/env bash
# external-doc-reingest.sh — Quarterly report on vendor documentation freshness.
# Issue: #2318 (https://github.com/vamseeachanta/workspace-hub/issues/2318)
# Companion: vamseeachanta/digitalmodel#503 (ingest Orcina/OrcaWave webhelp)
#
# Reads data/document-index/online-resource-registry.yaml and reports the
# inventory of vendor sources. When dm#503's ingest manifest exists, diffs
# last-ingested timestamps against the registry's `generated` timestamp to
# flag vendors whose doc pages may have moved since last ingest.
#
# Until dm#503 lands, runs in placeholder mode: renders vendor inventory +
# a note that the ingest pipeline is not yet initialized.
#
# Env overrides (testing):
#   EXTDOC_OUT_DIR       — override docs/reports output dir
#   EXTDOC_QUARTER       — override quarter (e.g. 2026-Q2)
#   EXTDOC_PREV_QUARTER  — override previous quarter
#   EXTDOC_REGISTRY      — override registry yaml path
#   EXTDOC_MANIFEST      — override ingest manifest path
#   EXTDOC_WARN_COUNT    — warn threshold (default 0)
#   EXTDOC_BLOCK_COUNT   — block threshold (default 5)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/cadence-common.sh"
cadence_init_repo_root

QUARTER="${EXTDOC_QUARTER:-$(cadence_period quarterly)}"
OUT_DIR="${EXTDOC_OUT_DIR:-${REPO_ROOT}/docs/reports}"
OUT="${OUT_DIR}/external-doc-reingest-${QUARTER}.md"
REGISTRY="${EXTDOC_REGISTRY:-${REPO_ROOT}/data/document-index/online-resource-registry.yaml}"
MANIFEST="${EXTDOC_MANIFEST:-${REPO_ROOT}/data/document-index/ingest-manifest.yaml}"
WARN_COUNT="${EXTDOC_WARN_COUNT:-0}"
BLOCK_COUNT="${EXTDOC_BLOCK_COUNT:-5}"

mkdir -p "$OUT_DIR"

# ── If registry missing, emit placeholder report ─────────────────────────
if [[ ! -f "$REGISTRY" ]]; then
    {
        emit_report_header "external-doc-reingest" "$QUARTER" "GREEN" "no registry — placeholder"
        echo "Registry not found at \`${REGISTRY}\`. This cadence depends on"
        echo "\`data/document-index/online-resource-registry.yaml\` (maintained by dm#503)."
        echo
        echo "## Source"
        echo
        echo "Generated by \`scripts/cron/external-doc-reingest.sh\` (#2318, companion dm#503)."
    } > "$OUT"
    echo "[external-doc-reingest] wrote $OUT (status: GREEN, placeholder — registry missing)"
    exit 0
fi

# ── Parse registry entries (flat yaml list expected) ─────────────────────
# Row format extracted: name <TAB> url <TAB> domain
TMP_VENDORS="$(mktemp)"
trap 'rm -f "$TMP_VENDORS"' EXIT

awk '
    function flush() {
        # Prefer display name; fall back to id when name absent.
        key = (name != "") ? name : id
        if (key != "") print key "\t" url "\t" domain
        id=""; name=""; url=""; domain=""
    }
    /^entries:/ { in_entries=1; next }
    # Entry boundary: any "- " at start (possibly indented) signals new record.
    in_entries && /^[[:space:]]*- / {
        flush()
        line=$0
        sub(/^[[:space:]]*- /, "", line)
        if (line ~ /^id: /)        { sub(/^id: */,     "", line); id=line }
        else if (line ~ /^name: /) { sub(/^name: */,   "", line); name=line }
        else if (line ~ /^url: /)  { sub(/^url: */,    "", line); url=line }
        next
    }
    in_entries && /^[[:space:]]+id: /     { sub(/^[[:space:]]+id: */,     "", $0); id=$0;     next }
    in_entries && /^[[:space:]]+name: /   { sub(/^[[:space:]]+name: */,   "", $0); name=$0;   next }
    in_entries && /^[[:space:]]+url: /    { sub(/^[[:space:]]+url: */,    "", $0); url=$0;    next }
    in_entries && /^[[:space:]]+domain: / { sub(/^[[:space:]]+domain: */, "", $0); domain=$0; next }
    END { flush() }
' "$REGISTRY" | sort -u > "$TMP_VENDORS"

vendor_count=$(wc -l < "$TMP_VENDORS" | tr -d ' ')
registry_generated=$(awk '/^generated:/ {sub(/^generated: */, "", $0); gsub(/['\''"]/, "", $0); print; exit}' "$REGISTRY")
registry_generated="${registry_generated:-unknown}"

# ── Manifest state (from dm#503). If absent → placeholder mode. ──────────
changed_count=0
if [[ -f "$MANIFEST" ]]; then
    mode="live"
    # last_ingested timestamps per vendor; if < registry_generated, consider "changed"
    reg_epoch=$(date -d "$registry_generated" +%s 2>/dev/null || echo 0)
    TMP_CHANGED="$(mktemp)"
    trap 'rm -f "$TMP_VENDORS" "$TMP_CHANGED"' EXIT
    while IFS=$'\t' read -r name url domain; do
        [[ -z "$name" ]] && continue
        last_ts=$(awk -v n="$name" '
            $0 ~ ("- name: " n "$") {found=1; next}
            found && /last_ingested:/ {
                sub(/^ *last_ingested: */, "", $0); gsub(/['\''"]/, "", $0); print; exit
            }
        ' "$MANIFEST")
        if [[ -z "$last_ts" ]]; then
            echo -e "${name}\t${url}\tnever\tinitial ingest\tpending" >> "$TMP_CHANGED"
            changed_count=$((changed_count + 1))
            continue
        fi
        last_epoch=$(date -d "$last_ts" +%s 2>/dev/null || echo 0)
        if (( last_epoch < reg_epoch )); then
            delta_days=$(( (reg_epoch - last_epoch) / 86400 ))
            echo -e "${name}\t${url}\t${last_ts}\t${delta_days}d since\tpending" >> "$TMP_CHANGED"
            changed_count=$((changed_count + 1))
        else
            echo -e "${name}\t${url}\t${last_ts}\tunchanged\tskipped" >> "$TMP_CHANGED"
        fi
    done < "$TMP_VENDORS"
else
    mode="placeholder"
fi

status="$(compute_status_band "$changed_count" "$WARN_COUNT" "$BLOCK_COUNT")"
if [[ "$mode" == "placeholder" ]]; then
    summary="placeholder — no ingest manifest yet (dm#503 pending); ${vendor_count} vendors in registry"
else
    summary="${changed_count} of ${vendor_count} vendors changed since last ingest (warn ${WARN_COUNT}, block ${BLOCK_COUNT})"
fi

# ── Build consumer-impact rows (orcaflex/cfd domains → dm#503) ──────────
orcina_vendors=$(awk -F'\t' '$3 ~ /orcaflex|orcina|cfd|naval/' "$TMP_VENDORS" | head -5)

# ── Write report ─────────────────────────────────────────────────────────
{
    emit_report_header "external-doc-reingest" "$QUARTER" "$status" "$summary"
    echo "Registry: \`${REGISTRY#$REPO_ROOT/}\` (generated ${registry_generated})"
    echo "Manifest: \`${MANIFEST#$REPO_ROOT/}\`"
    if [[ "$mode" == "placeholder" ]]; then
        echo
        echo "> ⚠️ **Placeholder mode** — ingest manifest not found. The cadence"
        echo "> reports vendor inventory only until dm#503 lands the pipeline."
    fi
    echo

    echo "## Per-vendor change log"
    echo
    echo "| Vendor | Source URL | Last modified | Δ since last ingest | Re-ingested |"
    echo "|--------|-----------|---------------|---------------------|-------------|"
    if [[ "$mode" == "live" ]]; then
        awk -F'\t' '{
            url = ($2 == "") ? "_(no url)_" : "`" $2 "`"
            printf "| %s | %s | %s | %s | %s |\n", $1, url, $3, $4, $5
        }' "$TMP_CHANGED"
    else
        awk -F'\t' '{
            url = ($2 == "") ? "_(no url)_" : "`" $2 "`"
            printf "| %s | %s | — | n/a | placeholder |\n", $1, url
        }' "$TMP_VENDORS"
    fi
    echo

    echo "## Consumer impact (issues that might benefit from the refresh)"
    echo
    if [[ -n "$orcina_vendors" ]]; then
        echo "| Issue | Reason |"
        echo "|-------|--------|"
        echo "| vamseeachanta/digitalmodel#503 | Orcina/OrcaWave/CFD vendor entries present in registry — ingest refresh would benefit. |"
    else
        echo "_No cross-repo consumers flagged for this quarter._"
    fi
    echo

    echo "## Source"
    echo
    echo "Generated by \`scripts/cron/external-doc-reingest.sh\` (#2318, companion digitalmodel#503)."
} > "$OUT"

echo "[external-doc-reingest] wrote $OUT (status: $status, mode: $mode, ${vendor_count} vendors)"
