#!/usr/bin/env python3
"""flywheel-review.py — periodic re-derivation of the ecosystem flywheel (epic #3085).

Recomputes the MEASURABLE flywheel-scorecard metrics from the merged artifacts
(mission-map, workflow-inventory, schedule-tasks) + a live scoped-memory scan,
and writes a dated review report. This is what makes the flywheel a *loop* rather
than a one-time pass: mission → workflow → metrics → marketing re-derive on a cadence.

Usage: flywheel-review.py [--root <workspace-hub>] [--repos-root <siblings>] [--print-only]
Exit 0 on success; non-zero if a required artifact is missing.
"""
from __future__ import annotations
import argparse
import datetime as _dt
import pathlib
import sys

import yaml

HUB_DEFAULT = "/mnt/local-analysis/workspace-hub"
REPOS_DEFAULT = "/mnt/local-analysis"


def _load(p: pathlib.Path):
    if not p.exists():
        raise FileNotFoundError(p)
    return yaml.safe_load(p.read_text())


def compute(hub: pathlib.Path, repos_root: pathlib.Path) -> dict:
    sched = _load(hub / "config/scheduled-tasks/schedule-tasks.yaml")
    inv = _load(hub / "config/mission/workflow-inventory.yaml")
    mm = _load(hub / "config/mission/mission-map.yaml")

    workflow_total = len(sched.get("tasks", []))

    wf = inv.get("workflows", [])
    o4 = sum(1 for w in wf if "O4" in (w.get("serves") or []))
    business = sum(1 for w in wf if set(w.get("serves") or []) & {"O1", "O2", "O3"})
    orphans = len(inv.get("orphans", []))

    repos, scoped = [], []
    for c in sorted(repos_root.iterdir()):
        try:
            if not (c / ".git").exists():
                continue
            repos.append(c.name)
            if (c / ".claude" / "memory").is_dir():
                scoped.append(c.name)
        except (PermissionError, OSError):
            continue  # cron must not die on one unreadable sibling

    repos_laddered = len(mm.get("repos", []))

    return {
        "workflow_total": workflow_total,
        "workflow_o4": o4,
        "workflow_business": business,
        "inventory_sampled": len(wf),
        "orphan_workflows": orphans,
        "repos_total": len(repos),
        "repos_scoped": len(scoped),
        "scoped_list": scoped,
        "repos_in_mission": repos_laddered,
    }


def render(m: dict, stamp: str) -> str:
    o4_pct = round(100 * m["workflow_o4"] / m["inventory_sampled"]) if m["inventory_sampled"] else 0
    return f"""# Flywheel review — {stamp}

Periodic re-derivation of epic #3078's flywheel (auto-generated by scripts/cron/flywheel-review.py).

| Metric | Value |
|---|---|
| Scheduled workflows (SSoT) | {m['workflow_total']} |
| Inventory O4 (self-health) | {m['workflow_o4']} / {m['inventory_sampled']} sampled (~{o4_pct}%) |
| Inventory O1-O3 (business) | {m['workflow_business']} / {m['inventory_sampled']} sampled |
| Orphan/dead workflows | {m['orphan_workflows']} |
| Repos with scoped memory | {m['repos_scoped']} / {m['repos_total']} |
| Repos in mission map | {m['repos_in_mission']} |

Scoped-memory repos: {', '.join(m['scoped_list']) or '(none)'}

**Watch:** O4-vs-business skew — the flywheel is turning toward output as the business
share (O1-O3) rises relative to self-health (O4). Scoped-memory coverage tracks #3084 rollout.
"""


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=HUB_DEFAULT)
    ap.add_argument("--repos-root", default=REPOS_DEFAULT)
    ap.add_argument("--print-only", action="store_true", help="print report, don't write a file")
    args = ap.parse_args(argv)

    hub = pathlib.Path(args.root)
    try:
        m = compute(hub, pathlib.Path(args.repos_root))
    except FileNotFoundError as e:
        print(f"missing required artifact: {e}", file=sys.stderr)
        return 1

    stamp = _dt.datetime.now().strftime("%Y-%m-%d")
    report = render(m, stamp)

    if args.print_only:
        print(report)
        return 0

    out_dir = hub / "logs" / "flywheel"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"flywheel-review-{stamp}.md"
    out.write_text(report)
    print(f"wrote {out}")
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
