#!/usr/bin/env bash
# harness-lean-out.sh — Weekly audit of harness files for bloat.
# Checks line counts, flags stale memory, identifies rules promotable to scripts/hooks.
# Called by cron weekly; produces a report + optionally invokes claude for fixes.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_HUB="${WORKSPACE_HUB:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
cd "$WORKSPACE_HUB"

REPORT="logs/quality/harness-lean-out-$(date +%Y%m%d).md"
mkdir -p "$(dirname "$REPORT")"

echo "# Harness Lean-Out Report — $(date +%Y-%m-%d)" > "$REPORT"
echo "" >> "$REPORT"

# ── 1. Line budget check ────────────────────────────────────────────────────
echo "## Line Budget" >> "$REPORT"
echo "| File | Lines | Budget | Status |" >> "$REPORT"
echo "|------|-------|--------|--------|" >> "$REPORT"

check_budget() {
  local file="$1" budget="$2"
  if [[ -f "$file" ]]; then
    local lines
    lines=$(wc -l < "$file")
    local status="OK"
    [[ "$lines" -gt "$budget" ]] && status="OVER (+$((lines - budget)))"
    echo "| $file | $lines | $budget | $status |" >> "$REPORT"
  fi
}

check_budget "CLAUDE.md" 20
check_budget "AGENTS.md" 20
check_budget "GEMINI.md" 20
check_budget "MEMORY.md" 20
check_budget ".claude/rules/coding-style.md" 40
check_budget ".claude/rules/patterns.md" 40

# ── 2. Memory staleness ────────────────────────────────────────────────────
MEMORY_DIR="$HOME/.claude/projects/-mnt-local-analysis-workspace-hub/memory"
echo "" >> "$REPORT"
echo "## Stale Memory Files (>90 days)" >> "$REPORT"
if [[ -d "$MEMORY_DIR" ]]; then
  stale=$(find "$MEMORY_DIR" -name "*.md" -mtime +90 ! -name "MEMORY.md" 2>/dev/null)
  if [[ -n "$stale" ]]; then
    echo "$stale" | while read -r f; do
      echo "- $(basename "$f") ($(stat -c %y "$f" | cut -d' ' -f1))" >> "$REPORT"
    done
  else
    echo "None found." >> "$REPORT"
  fi
else
  echo "Memory directory not found." >> "$REPORT"
fi

# ── 3. Feedback files count ────────────────────────────────────────────────
echo "" >> "$REPORT"
echo "## Feedback File Count" >> "$REPORT"
if [[ -d "$MEMORY_DIR" ]]; then
  fb_count=$(find "$MEMORY_DIR" -name "feedback_*.md" 2>/dev/null | wc -l)
  echo "Total feedback files: $fb_count" >> "$REPORT"
  [[ "$fb_count" -gt 15 ]] && echo "WARNING: >15 feedback files — consider consolidating or promoting to hooks" >> "$REPORT"
fi

# ── 4. Rules promotable to scripts ─────────────────────────────────────────
echo "" >> "$REPORT"
echo "## Promotion Candidates (prose rules → scripts/hooks)" >> "$REPORT"
echo "Run manually: review .claude/rules/*.md for binary checks expressible as exit 0/1" >> "$REPORT"

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "Generated by harness-lean-out.sh" >> "$REPORT"

cat "$REPORT"
