#!/usr/bin/env bash
# state-size-report.sh — Weekly markdown report of tracked .claude/state/* sizes.
# Issue: #2070 (https://github.com/vamseeachanta/workspace-hub/issues/2070)
#
# Output: docs/reports/state-size-YYYY-WW.md (one per ISO week)
# Cron suggestion: 0 6 * * 1   (Mondays 06:00 local)
#
# Lists the 10 largest tracked files under .claude/state/, flags any over WARN_MB,
# and emits a green/yellow/red health status against the BLOCK_MB threshold.
#
# Env overrides (testing):
#   STATE_REPORT_OUT_DIR    — override docs/reports output dir
#   STATE_REPORT_WEEK       — override ISO week (e.g., 2026-W16)
#   STATE_SIZE_WARN_MB      — warn threshold (default 50)
#   STATE_SIZE_BLOCK_MB     — block threshold (default 75) — same as guard hooks
#   STATE_REPORT_REPO_ROOT  — override repo root (for tests)
set -uo pipefail

REPO_ROOT="${STATE_REPORT_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
OUT_DIR="${STATE_REPORT_OUT_DIR:-${REPO_ROOT}/docs/reports}"
WEEK="${STATE_REPORT_WEEK:-$(date +%Y-W%V)}"
WARN_MB="${STATE_SIZE_WARN_MB:-50}"
BLOCK_MB="${STATE_SIZE_BLOCK_MB:-75}"

cd "$REPO_ROOT" || exit 1

mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/state-size-$WEEK.md"

# Collect tracked files under .claude/state/, sized in bytes
# Only files actually tracked by git — ignored files don't matter for push risk.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

git ls-files .claude/state/ 2>/dev/null | while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    size=$(stat -c %s "$f" 2>/dev/null || stat -f %z "$f" 2>/dev/null || echo 0)
    printf "%d\t%s\n" "$size" "$f"
done | sort -rn > "$TMP"

TOTAL_FILES=$(wc -l < "$TMP")
TOTAL_BYTES=$(awk '{s+=$1} END {print s+0}' "$TMP")
TOTAL_MB=$(( TOTAL_BYTES / 1048576 ))
LARGEST_MB=$(head -1 "$TMP" 2>/dev/null | awk '{print int($1/1048576)}')
LARGEST_MB="${LARGEST_MB:-0}"

# Health
if (( LARGEST_MB > BLOCK_MB )); then
    STATUS="RED"
elif (( LARGEST_MB > WARN_MB )); then
    STATUS="YELLOW"
else
    STATUS="GREEN"
fi

{
    echo "# State-file size report — $WEEK"
    echo
    echo "**Status:** $STATUS — largest tracked file is ${LARGEST_MB}MB (warn ${WARN_MB}MB, block ${BLOCK_MB}MB)."
    echo
    echo "Total tracked under .claude/state/: $TOTAL_FILES files, ${TOTAL_MB}MB."
    echo
    echo "## Top 10 largest tracked files"
    echo
    echo "| Size (MB) | Path | Flag |"
    echo "|-----------|------|------|"
    head -10 "$TMP" | while IFS=$'\t' read -r bytes path; do
        mb=$(( bytes / 1048576 ))
        flag=""
        if (( mb > BLOCK_MB )); then
            flag="🔴 OVER BLOCK"
        elif (( mb > WARN_MB )); then
            flag="🟡 over warn"
        fi
        printf "| %d | \`%s\` | %s |\n" "$mb" "$path" "$flag"
    done
    echo
    echo "## Source"
    echo
    echo "Generated by \`scripts/cron/state-size-report.sh\` (#2070)."
} > "$OUT"

echo "[state-size-report] wrote $OUT (status: $STATUS)"
