#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


def gather(work_queue_root: Path) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    for name in ("pending", "working", "done"):
        bucket = work_queue_root / name
        if bucket.exists():
            sections[name] = sorted(p.stem for p in bucket.glob("*.md"))
        else:
            sections[name] = []
    return sections


def render(work_queue_root: Path, sections: dict[str, list[str]]) -> str:
    total = sum(len(v) for v in sections.values())
    lines = [
        "# Legacy Work Queue Index",
        "",
        "> Compatibility output for historical callers of `.claude/work-queue/scripts/generate-index.py`.",
        "> Canonical current queue surface: `notes/agent-work-queue.md` regenerated by `scripts/refresh-agent-work-queue.py`.",
        "",
        f"- work_queue_root: `{work_queue_root}`",
        f"- total_local_items: {total}",
        "",
    ]
    for name, items in sections.items():
        lines.append(f"## {name.title()} ({len(items)})")
        if items:
            for item in items[:50]:
                lines.append(f"- {item}")
        else:
            lines.append("- none")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[3]
    work_queue_root = repo_root / ".claude" / "work-queue"
    index_path = work_queue_root / "INDEX.md"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    sections = gather(work_queue_root)
    index_path.write_text(render(work_queue_root, sections) + "\n", encoding="utf-8")
    sys.stderr.write(
        "[legacy] generated .claude/work-queue/INDEX.md for compatibility; canonical queue is notes/agent-work-queue.md\n"
    )
    print(index_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
