"""
Regression tests for DNV RP F105 free-span VIV — MATLAB example data.

Test vectors extracted from the sample input file generated by the
legacy MATLAB implementation. The sample represents a 6-inch rigid
jumper configuration with these parameters:

    OD = 0.1683 m (6" pipe), ID = 0.1317 m, WT = 0.0183 m
    Span length = 30 m
    Seawater density = 1025 kg/m³
    Contents density = 319 kg/m³
    Seabed proximity = 2.63 m
    Total damping = 0.005
    Safety class = Low
    S-N curve: A1=5.808e11, k1=3, A2=4.03645e15, k2=5
    Transfer cycles = 1.0e6 (bilinear S-N curve transition)

    Current profiles (out-of-plane = in-plane):
        Speed [m/s]   Probability
        0.04          0.80
        0.20          0.10
        0.40          0.05
        0.60          0.04
        1.00          0.01

Reference: DNV-RP-F105 (2006), "Free Spanning Pipelines".
"""
import math
import pytest

from digitalmodel.subsea.pipeline.free_span.models import (
    PipeSpanInput,
    BoundaryConditionF105,
    EnvironmentType,
)
from digitalmodel.subsea.pipeline.free_span.span_natural_frequency import (
    SpanNaturalFrequency,
    _added_mass_coefficient,
)
from digitalmodel.subsea.pipeline.free_span.span_onset_screening import (
    SpanOnsetScreening,
)
from digitalmodel.subsea.pipeline.free_span.span_viv_response import (
    SpanVIVAmplitude,
)
from digitalmodel.subsea.pipeline.free_span.span_fatigue_damage import (
    SpanFatigueDamage,
)
from digitalmodel.subsea.pipeline.free_span import FreespanVIVFatigue
from digitalmodel.subsea.pipeline.free_span.weibull_current import (
    fit_weibull_current,
    extrapolate_current,
)




# ---------------------------------------------------------------------------
# MATLAB example fixture — 6" jumper configuration
# ---------------------------------------------------------------------------

@pytest.fixture
def jumper_input():
    """6-inch jumper — MATLAB sample input file defaults.

    OD = 0.1683 m, ID = 0.1317 m → WT = (0.1683 - 0.1317)/2 = 0.0183 m
    Span = 30 m, seabed gap = 2.63 m, damping = 0.005
    Contents = 319 kg/m³ (gas), seawater = 1025 kg/m³
    Safety class Low → gamma_on_IL=1.1, gamma_on_CF=1.3, gamma_k=1.0
    """
    return PipeSpanInput(
        od_m=0.1683,
        wt_m=0.0183,
        span_length_m=30.0,
        e_modulus_pa=207e9,
        steel_density_kgm3=7850.0,
        content_density_kgm3=319.0,
        water_density_kgm3=1025.0,
        current_velocity_ms=1.0,  # 100-yr screening velocity
        wave_velocity_ms=0.0,
        seabed_gap_m=2.63,
        bc=BoundaryConditionF105.PINNED_PINNED,
        sag_m=0.0,
        structural_damping=0.005,
        hydrodynamic_damping=0.0,  # MATLAB uses single total damping
        sn_curve_class="F",
        environment=EnvironmentType.SEAWATER_CP,
        gamma_on_IL=1.1,
        gamma_on_CF=1.3,
        gamma_k=1.0,  # Low safety class → gamma_k = 1.0
    )


@pytest.fixture
def matlab_current_profile():
    """Current speed vs probability from MATLAB sample input.

    Probabilities are occurrence probabilities (sum = 1.0).
    Convert to exceedance for Weibull fitting.
    """
    return {
        "speeds": [0.04, 0.20, 0.40, 0.60, 1.00],
        "occurrence_probs": [0.80, 0.10, 0.05, 0.04, 0.01],
    }


# ---------------------------------------------------------------------------
# WeibullCurrentFit tests — ported from MATLAB WeibullCurrentFit.m
# ---------------------------------------------------------------------------

class TestWeibullCurrentFit:
    """Tests for Weibull current profile fitting (DNV-RP-F105 Sec 3.3)."""

    def test_fit_returns_positive_shape_parameters(self, matlab_current_profile):
        """Weibull shape k > 0 for well-behaved current data."""
        speeds = matlab_current_profile["speeds"]
        occ = matlab_current_profile["occurrence_probs"]
        # Convert occurrence to exceedance
        import numpy as np
        cum = np.cumsum(occ)
        exc = list(np.round(1e8 * (1 - cum)) / 1e8)  # match MATLAB rounding

        fit = fit_weibull_current(exc, speeds)
        assert fit.k_upper > 0, f"k_upper={fit.k_upper} should be > 0"
        assert fit.k_lower > 0, f"k_lower={fit.k_lower} should be > 0"

    def test_100yr_current_exceeds_max_observed(self, matlab_current_profile):
        """100-year return period current > max observed (1.0 m/s)."""
        speeds = matlab_current_profile["speeds"]
        occ = matlab_current_profile["occurrence_probs"]
        import numpy as np
        cum = np.cumsum(occ)
        exc = list(np.round(1e8 * (1 - cum)) / 1e8)

        # 100-year exceedance probability for 24-hr duration
        T_duration = 24  # hours
        p_100yr = T_duration / (24 * 365.25 * 100)

        u_100yr = extrapolate_current(exc, speeds, p_100yr)
        assert u_100yr > 1.0, (
            f"100-yr current {u_100yr:.3f} should exceed max observed 1.0 m/s"
        )

    def test_10yr_between_1yr_and_100yr(self, matlab_current_profile):
        """10-year return current is between 1-year and 100-year."""
        speeds = matlab_current_profile["speeds"]
        occ = matlab_current_profile["occurrence_probs"]
        import numpy as np
        cum = np.cumsum(occ)
        exc = list(np.round(1e8 * (1 - cum)) / 1e8)

        T_duration = 24
        p_1yr = T_duration / (24 * 365.25 * 1)
        p_10yr = T_duration / (24 * 365.25 * 10)
        p_100yr = T_duration / (24 * 365.25 * 100)

        u_1yr, u_10yr, u_100yr = extrapolate_current(
            exc, speeds, [p_1yr, p_10yr, p_100yr]
        )
        assert u_1yr < u_10yr < u_100yr

    def test_extrapolation_monotonic(self, matlab_current_profile):
        """Current speed increases monotonically as exceedance decreases."""
        speeds = matlab_current_profile["speeds"]
        occ = matlab_current_profile["occurrence_probs"]
        import numpy as np
        cum = np.cumsum(occ)
        exc = list(np.round(1e8 * (1 - cum)) / 1e8)

        probs = [0.15, 0.10, 0.05, 0.01, 0.005, 0.001]
        results = extrapolate_current(exc, speeds, probs)
        for i in range(len(results) - 1):
            assert results[i] <= results[i + 1], (
                f"Non-monotonic: U({probs[i]})={results[i]:.3f} > "
                f"U({probs[i+1]})={results[i+1]:.3f}"
            )

    def test_known_points_reproduced(self, matlab_current_profile):
        """Extrapolating at a known data point reproduces the input speed."""
        speeds = matlab_current_profile["speeds"]
        occ = matlab_current_profile["occurrence_probs"]
        import numpy as np
        cum = np.cumsum(occ)
        exc = list(np.round(1e8 * (1 - cum)) / 1e8)

        # The highest-speed data point should be reproduced exactly
        # p_exc for 1.0 m/s is exc[-1] (should be ~0.0)
        # Use the second-highest instead (exc[-2] = 0.01)
        u_at_p01 = extrapolate_current(exc, speeds, exc[-2])
        assert abs(u_at_p01 - speeds[-2]) < 0.05, (
            f"At P_exc={exc[-2]}: got {u_at_p01:.3f}, expected ~{speeds[-2]}"
        )

    def test_two_point_minimum(self):
        """Weibull fit works with exactly 2 data points."""
        speeds = [0.5, 1.0]
        exc = [0.10, 0.01]
        fit = fit_weibull_current(exc, speeds)
        assert fit.k_upper != 0
        u = extrapolate_current(exc, speeds, 0.001)
        assert u > 1.0

    def test_raises_on_single_point(self):
        """Must have ≥ 2 points."""
        with pytest.raises(ValueError, match="At least 2"):
            fit_weibull_current([0.1], [0.5])

    def test_raises_on_length_mismatch(self):
        """Lengths of probs and speeds must match."""
        with pytest.raises(ValueError, match="Length mismatch"):
            fit_weibull_current([0.1, 0.01], [0.5])


# ---------------------------------------------------------------------------
# Natural Frequency — MATLAB 6" jumper example
# ---------------------------------------------------------------------------

class TestJumperNaturalFrequency:
    """Natural frequency for 6" jumper example from MATLAB defaults."""

    def test_fn_positive(self, jumper_input):
        calc = SpanNaturalFrequency(jumper_input)
        assert calc.fn_IL() > 0
        assert calc.fn_CF() > 0

    def test_fn_order_of_magnitude(self, jumper_input):
        """6" pipe, L=30 m → fn should be roughly 0.5-3 Hz range."""
        calc = SpanNaturalFrequency(jumper_input)
        fn = calc.fn_IL()
        assert 0.1 < fn < 10.0, f"fn_IL={fn:.3f} Hz seems out of range"

    def test_seabed_gap_large_gives_ca_one(self, jumper_input):
        """e/D = 2.63/0.1683 = 15.6 >> 0.8 → Ca = 1.0 (no proximity effect)."""
        e_over_D = jumper_input.seabed_gap_m / jumper_input.od_m
        assert e_over_D > 0.8
        ca = _added_mass_coefficient(e_over_D)
        assert ca == 1.0

    def test_effective_mass_includes_contents(self, jumper_input):
        """Effective mass includes pipe steel + contents + added mass."""
        calc = SpanNaturalFrequency(jumper_input)
        result = calc.compute()
        # Steel area
        ri = (jumper_input.od_m - 2 * jumper_input.wt_m) / 2
        ro = jumper_input.od_m / 2
        A_steel = math.pi * (ro**2 - ri**2)
        m_steel = A_steel * jumper_input.steel_density_kgm3
        # Contents area
        A_contents = math.pi * ri**2
        m_contents = A_contents * jumper_input.content_density_kgm3
        # Effective mass must exceed dry mass
        assert result.m_effective_kgm > m_steel + m_contents


# ---------------------------------------------------------------------------
# Onset Screening — MATLAB 6" jumper at 1.0 m/s
# ---------------------------------------------------------------------------

class TestJumperOnsetScreening:
    """Onset screening for 6" jumper at Uc = 1.0 m/s."""

    def _build(self, inp):
        freq = SpanNaturalFrequency(inp).compute()
        return SpanOnsetScreening(
            inp, freq.fn_IL_hz, freq.fn_CF_hz, freq.m_effective_kgm
        )

    def test_stability_parameter_positive(self, jumper_input):
        scr = self._build(jumper_input)
        Ks = scr.stability_parameter()
        assert Ks > 0

    def test_cf_onset_at_1ms(self, jumper_input):
        """At 1.0 m/s, CF VIV onset should be triggered for 6" jumper."""
        scr = self._build(jumper_input)
        flags = scr.screening_flags()
        # CF onset velocity threshold for e/D >> 0.8 and Low safety:
        # Vr_onset_CF = 3.0 / 1.3 ≈ 2.31
        # Ur = 1.0 / (fn * 0.1683)
        # If fn ~ 1.5 Hz, Ur ~ 1.0/(1.5*0.1683) ~ 3.96 > 2.31 → onset
        assert flags.cf_viv_onset is True

    def test_cf_onset_velocity_matches_f105_sec4_4_6(self, jumper_input):
        """CF onset: Vr_onset = 3 * psi_prox / gamma_on_CF.

        For e/D > 0.8: psi_prox = 1.0 → Vr_onset = 3.0 / 1.3 ≈ 2.308.
        """
        scr = self._build(jumper_input)
        Vr_cf = scr.cf_onset_velocity()
        expected = 3.0 / jumper_input.gamma_on_CF  # 2.308
        assert abs(Vr_cf - expected) < 0.01, (
            f"CF onset Vr={Vr_cf:.3f}, expected {expected:.3f}"
        )


# ---------------------------------------------------------------------------
# VIV Amplitude — MATLAB 6" jumper
# ---------------------------------------------------------------------------

class TestJumperVIVAmplitude:

    def _build(self, inp):
        freq = SpanNaturalFrequency(inp).compute()
        Ks = SpanOnsetScreening(
            inp, freq.fn_IL_hz, freq.fn_CF_hz, freq.m_effective_kgm
        ).stability_parameter()
        return SpanVIVAmplitude(
            inp, Ks, freq.fn_IL_hz, freq.fn_CF_hz,
            freq.EI_Nm2, freq.m_effective_kgm,
        )

    def test_cf_amplitude_bounded(self, jumper_input):
        """CF A/D must be between 0 and 1.5 (F105 physical bound)."""
        amp = self._build(jumper_input)
        cf_A = amp.cf_amplitude_over_D()
        assert 0.0 <= cf_A <= 1.5

    def test_il_amplitude_bounded(self, jumper_input):
        """IL A/D must be between 0 and 0.25 (F105 physical bound)."""
        amp = self._build(jumper_input)
        il_A = amp.il_amplitude_over_D()
        assert 0.0 <= il_A <= 0.25


# ---------------------------------------------------------------------------
# Fatigue — MATLAB S-N curve parameters
# ---------------------------------------------------------------------------

class TestJumperFatigue:
    """Fatigue using MATLAB example S-N curve: A1=5.808e11, k1=3."""

    def test_fatigue_life_positive(self, jumper_input):
        """At 1.0 m/s, stress should produce finite fatigue life."""
        freq = SpanNaturalFrequency(jumper_input).compute()
        Ks = SpanOnsetScreening(
            jumper_input, freq.fn_IL_hz, freq.fn_CF_hz,
            freq.m_effective_kgm,
        ).stability_parameter()
        amp = SpanVIVAmplitude(
            jumper_input, Ks, freq.fn_IL_hz, freq.fn_CF_hz,
            freq.EI_Nm2, freq.m_effective_kgm,
        )
        cf_A = amp.cf_amplitude_over_D()
        cf_sigma = amp.stress_from_amplitude(cf_A, freq.fn_CF_hz, mode="CF")
        if cf_sigma > 0:
            fat = SpanFatigueDamage(jumper_input, freq.fn_CF_hz, cf_sigma)
            life = fat.fatigue_life_years()
            assert life > 0


# ---------------------------------------------------------------------------
# Full integration — FreespanVIVFatigue facade with MATLAB inputs
# ---------------------------------------------------------------------------

class TestJumperIntegration:
    """End-to-end assessment using MATLAB example 6" jumper inputs."""

    def test_assess_returns_valid_result(self, jumper_input):
        """Full assessment should complete without errors."""
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        result = facade.assess()
        assert result.fn_IL_hz > 0
        assert result.fn_CF_hz > 0
        assert result.Ks > 0
        assert result.allowable_span_m > 0

    def test_utilization_ratio(self, jumper_input):
        """Utilization = span_length / allowable_span."""
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        result = facade.assess()
        expected = result.span_length_m / result.allowable_span_m
        assert abs(result.span_utilization - expected) < 1e-9

    def test_screening_factors_match_low_safety(self, jumper_input):
        """Low safety class: gamma_on_IL=1.1, gamma_on_CF=1.3, gamma_k=1.0.

        These match the MATLAB ObtainParams defaults for 'Low' safety class.
        """
        assert jumper_input.gamma_on_IL == 1.1
        assert jumper_input.gamma_on_CF == 1.3
        assert jumper_input.gamma_k == 1.0

    def test_current_probability_driven_damage(self, jumper_input):
        """Compare damage at max current (1.0 m/s) vs low current (0.04 m/s).

        The MATLAB code weights damage by probability:
            D_total = sum(D_i * prob_i)
        At 0.04 m/s (prob=0.80), damage should be negligible.
        At 1.0 m/s (prob=0.01), damage per unit time is much higher.
        """
        from dataclasses import replace
        # High current case
        inp_high = replace(jumper_input, current_velocity_ms=1.0)
        r_high = FreespanVIVFatigue(inp_high, submerged_weight_N_m=850.0).assess()
        # Low current case
        inp_low = replace(jumper_input, current_velocity_ms=0.04)
        r_low = FreespanVIVFatigue(inp_low, submerged_weight_N_m=850.0).assess()
        # High current should give more damage (or equal if both below onset)
        assert r_high.damage_per_year >= r_low.damage_per_year

    def test_bilinear_sn_curve_parameters(self, jumper_input):
        """Verify MATLAB S-N parameters match standard DNV values.

        MATLAB uses: A1=5.808e11, k1=3, A2=4.03645e15, k2=5
        This is the DNV-RP-C203 D-class in seawater with CP:
            Slope 1: N = 5.808e11 * S^(-3) for S > transfer stress
            Slope 2: N = 4.03645e15 * S^(-5) for S < transfer stress
            Transfer at N = 1e6 cycles.
        """
        A1 = 5.808e11
        k1 = 3
        A2 = 4.03645e15
        k2 = 5
        N_transfer = 1.0e6
        # Transfer stress from slope 2: S = (A2/N)^(1/k2)
        S_transfer = (A2 / N_transfer) ** (1.0 / k2)
        # For these D-class parameters: S_transfer ≈ 83.4 MPa
        assert 70 < S_transfer < 100, f"Transfer stress = {S_transfer:.1f} MPa"


# ---------------------------------------------------------------------------
# Safety factor table validation (DNV-RP-F105 Table 2-4)
# ---------------------------------------------------------------------------

class TestSafetyFactorConsistency:
    """Verify safety factor values match DNV-RP-F105 Table 2-4."""

    @pytest.mark.parametrize("safety_class,gamma_k,eta", [
        ("Low", 1.0, 1.0),
        ("Normal", 1.15, 0.5),
        ("High", 1.3, 0.25),
    ])
    def test_gamma_k_by_safety_class(self, safety_class, gamma_k, eta):
        """Table 2-4: gamma_k and eta by safety class.

        These values are from DNV-RP-F105 and the MATLAB ObtainParams function.
        Low:    gamma_k=1.0,  eta=1.0
        Normal: gamma_k=1.15, eta=0.5
        High:   gamma_k=1.3,  eta=0.25
        """
        # This is a reference-data test — just assert the standard values
        assert gamma_k in (1.0, 1.15, 1.3)
        assert eta in (1.0, 0.5, 0.25)

    def test_onset_safety_factors_match_matlab(self):
        """MATLAB defaults: gamma_on_CF=1.1, gamma_on_IL=1.3.

        Note: The MATLAB code swaps CF and IL naming relative to typical
        convention. In the MATLAB ObtainParams function:
            onsetSafetyFactor_CF = 1.1
            onsetSafetyFactor_IL = 1.3
        But our Python follows DNV convention:
            gamma_on_IL = 1.1  (IL onset more sensitive)
            gamma_on_CF = 1.3  (CF onset less sensitive)
        """
        # Document the MATLAB→Python mapping
        matlab_cf = 1.1
        matlab_il = 1.3
        # In our Python code, these are named per DNV convention:
        python_il = 1.1   # gamma_on_IL
        python_cf = 1.3   # gamma_on_CF
        assert python_il == matlab_cf
        assert python_cf == matlab_il

    def test_screening_factors_gamma_cf_gamma_il(self):
        """MATLAB: crossflowScreeningFactor = inlineScreeningFactor = 1.4."""
        # Both are 1.4 in the MATLAB code — used in screening criteria
        assert 1.4 == 1.4  # Documenting the value

    def test_stress_safety_factor(self):
        """MATLAB: stressSafetyFactor = 1.3 (gamma_s)."""
        gamma_s = 1.3
        assert gamma_s == 1.3


# ---------------------------------------------------------------------------
# Reduction factor tests (DNV-RP-F105 Sec 4.3.6)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Multi-current probability-weighted damage (MATLAB approach)
# ---------------------------------------------------------------------------

class TestMultiCurrentDamage:
    """Tests for assess_multi_current() — probability-weighted fatigue."""

    @pytest.fixture
    def matlab_bins(self):
        """5-bin current profile from MATLAB sample input."""
        return [
            (0.04, 0.80),
            (0.20, 0.10),
            (0.40, 0.05),
            (0.60, 0.04),
            (1.00, 0.01),
        ]

    def test_returns_valid_result(self, jumper_input, matlab_bins):
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        result = facade.assess_multi_current(matlab_bins)
        assert result.fn_IL_hz > 0
        assert result.damage_per_year >= 0

    def test_weighted_damage_less_than_peak_bin(self, jumper_input, matlab_bins):
        """Weighted damage < damage at peak-response current speed.

        VIV amplitude is piecewise — the worst bin is NOT necessarily the
        max current.  For this jumper (fn≈0.4 Hz, D=0.1683 m), peak CF
        response occurs around Ur≈7–8 (Uc≈0.5–0.6 m/s).  The weighted
        damage should be less than 100% at the worst single bin.
        """
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        r_weighted = facade.assess_multi_current(matlab_bins)
        # Find worst single-bin damage
        from dataclasses import replace
        max_single = max(
            FreespanVIVFatigue(
                replace(jumper_input, current_velocity_ms=speed),
                submerged_weight_N_m=850.0,
            ).assess().damage_per_year
            for speed, _ in matlab_bins
        )
        assert r_weighted.damage_per_year < max_single

    def test_weighted_damage_greater_than_min(self, jumper_input, matlab_bins):
        """Weighted damage > damage at min current (some bins have onset)."""
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        r_weighted = facade.assess_multi_current(matlab_bins)
        from dataclasses import replace
        inp_min = replace(jumper_input, current_velocity_ms=0.04)
        r_min = FreespanVIVFatigue(inp_min, submerged_weight_N_m=850.0).assess()
        assert r_weighted.damage_per_year >= r_min.damage_per_year

    def test_single_bin_equals_single_assess(self, jumper_input):
        """Single bin with prob=1.0 should match single assess()."""
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        r_single = facade.assess()
        r_multi = facade.assess_multi_current([(jumper_input.current_velocity_ms, 1.0)])
        assert abs(r_multi.damage_per_year - r_single.damage_per_year) < 1e-12

    def test_weighted_life_longer_than_worst_bin(self, jumper_input, matlab_bins):
        """Probability weighting → longer life than worst single bin."""
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        r_weighted = facade.assess_multi_current(matlab_bins)
        from dataclasses import replace
        # Find shortest life from any single bin
        min_life = min(
            FreespanVIVFatigue(
                replace(jumper_input, current_velocity_ms=speed),
                submerged_weight_N_m=850.0,
            ).assess().fatigue_life_years
            for speed, _ in matlab_bins
        )
        if math.isfinite(r_weighted.fatigue_life_years) and math.isfinite(min_life):
            assert r_weighted.fatigue_life_years > min_life

    def test_raises_on_empty_bins(self, jumper_input):
        facade = FreespanVIVFatigue(jumper_input, submerged_weight_N_m=850.0)
        with pytest.raises(ValueError, match="must not be empty"):
            facade.assess_multi_current([])

    def test_probabilities_sum_to_one(self, matlab_bins):
        """Verify test fixture probabilities sum to 1.0."""
        total = sum(p for _, p in matlab_bins)
        assert abs(total - 1.0) < 1e-10


class TestReductionFactors:
    """Turbulence intensity and flow angle reduction factors."""

    def test_reduction_factor_r1_default_turbulence(self):
        """R1 at Ic=0.05, theta=90° → R1 = 1 - π²(0.05-0.03)(π/2 - √2·π/2).

        From MATLAB ObtainParams:
            reduction1 = 1 - π²*(Ic - 0.03)*(π/2 - √2*theta_rel)
        At theta_rel = π/2 (90°):
            π/2 - √2·π/2 = π/2(1 - √2) ≈ -0.6685
            R1 = 1 - π²·0.02·(-0.6685) ≈ 1 + 0.1319 → clamp to 1.0
        """
        Ic = 0.05
        theta = math.pi / 2
        R1 = 1.0 - math.pi**2 * (Ic - 0.03) * (math.pi / 2 - math.sqrt(2) * theta)
        R1 = max(0.0, min(1.0, R1))  # clamp [0, 1]
        assert 0.0 <= R1 <= 1.0

    def test_reduction_factor_r2_default_turbulence(self):
        """R2 at Ic=0.05: R2 = 1 - (0.05 - 0.03)/0.17 ≈ 0.882."""
        Ic = 0.05
        R2 = 1.0 - (Ic - 0.03) / 0.17
        R2 = max(0.0, min(1.0, R2))
        expected = 1.0 - 0.02 / 0.17
        assert abs(R2 - expected) < 1e-6
        assert 0.8 < R2 < 1.0
