"""Assemble one Python module per workbook from detected patterns.

Groups functions by sheet, adds imports, docstring, and main block.
Constraint: output module must be <500 lines.
"""

from __future__ import annotations

import re
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from loop_collapse_generator import generate_function_from_pattern
from formula_to_python import can_translate


def _safe_func_name(pattern: str, idx: int) -> str:
    """Generate a safe Python function name from pattern index."""
    return f"calc_{idx:03d}"


def _collect_inputs_for_pattern(
    cells: list[dict], classification: dict,
) -> list[str]:
    """Find input refs used by cells in this pattern group."""
    input_set = set(classification.get("inputs", []))
    refs = set()
    for cell in cells:
        for r in cell.get("references", []):
            clean = r.replace("$", "")
            if clean in input_set or r in input_set:
                refs.add(r)
    return sorted(refs)


def _build_var_map(classification: dict) -> dict:
    """Build simple var_map from classification inputs."""
    var_map = {}
    for ref in classification.get("inputs", []):
        clean = ref.replace("$", "").lower()
        var_map[ref] = clean
    return var_map


def assemble_module(
    stem: str,
    patterns: dict[str, list[dict]],
    classification: dict,
    named_ranges: list,
    domain: str,
) -> str:
    """Assemble a complete Python module from pattern groups.

    Args:
        stem: Workbook stem name (used in docstring).
        patterns: Canonical formula → list of cells.
        classification: Dict with inputs, outputs, chain.
        named_ranges: List of named range dicts.
        domain: Engineering domain string.

    Returns:
        Complete Python module as a string.
    """
    var_map = _build_var_map(classification)

    # Module header
    lines = [
        f'"""Auto-generated calculations from {stem}.',
        f"",
        f"Domain: {domain}",
        f"Patterns: {len(patterns)} unique",
        f"Generated by xlsx-poc-v2 pipeline.",
        f'"""',
        f"",
        f"import math",
        f"",
        f"",
    ]

    # Group patterns by sheet
    sheet_patterns: dict[str, list[tuple]] = {}
    for idx, (canonical, cells) in enumerate(patterns.items()):
        sheet = cells[0]["sheet"] if cells else "Unknown"
        if sheet not in sheet_patterns:
            sheet_patterns[sheet] = []
        sheet_patterns[sheet].append((idx, canonical, cells))

    # Generate functions grouped by sheet
    func_idx = 0
    for sheet, pat_list in sheet_patterns.items():
        lines.append(f"# --- Sheet: {sheet} ---")
        lines.append("")

        for idx, canonical, cells in pat_list:
            inputs = _collect_inputs_for_pattern(cells, classification)
            func_name = _safe_func_name(canonical, func_idx)
            func_code = generate_function_from_pattern(
                name=func_name,
                pattern=canonical,
                cells=cells,
                var_map=var_map,
                inputs=inputs,
            )
            lines.append(func_code)
            lines.append("")
            lines.append("")
            func_idx += 1

    # Main block
    lines.append('if __name__ == "__main__":')
    lines.append(f'    print("Module: {stem}")')
    lines.append(f'    print("Functions: {func_idx}")')
    lines.append(f'    print("Domain: {domain}")')
    lines.append("")

    return "\n".join(lines)
