"""Run formula extraction POC on 10 selected XLSX files (WRK-1247 Step 11).

Run with: uv run python scripts/data/doc_intelligence/run_poc_extraction.py
(from workspace-hub root, NOT --no-project — needs .venv with networkx)
"""

import json
import os
import sys
import time
import traceback
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

# Ensure networkx is importable for graph classification
try:
    import networkx  # noqa: F401
    _HAS_NETWORKX = True
except ImportError:
    _HAS_NETWORKX = False
    print("WARNING: networkx not available — graph classification disabled, running manual fallback", file=sys.stderr)

from scripts.data.doc_intelligence.parsers.formula_xlsx import FormulaXlsxParser
from scripts.data.doc_intelligence.schema import CellFormula, FormulaPayload

POC_LIST = REPO_ROOT / "knowledge" / "dark-intelligence" / "xlsx-poc" / "poc-file-list.yaml"
OUTPUT_DIR = REPO_ROOT / "knowledge" / "dark-intelligence" / "xlsx-poc"

# Limit file size to avoid memory issues on large files
MAX_SIZE_MB = 15


def sanitize_stem(filename: str) -> str:
    """Create a safe directory name from filename."""
    stem = Path(filename).stem
    # Replace spaces and special chars with hyphens
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in stem)
    return safe[:60].strip("-").lower()


def formula_payload_to_dict(fp: FormulaPayload) -> dict:
    """Serialize FormulaPayload to a plain dict."""
    return {
        "formulas": [
            {
                "cell_ref": f.cell_ref,
                "sheet": f.sheet,
                "formula": f.formula,
                "cached_value": f.cached_value,
                "cache_status": f.cache_status,
                "references": f.references,
            }
            for f in fp.formulas
        ],
        "named_ranges": [
            {"name": nr.name, "cell_ref": nr.cell_ref, "scope": nr.scope}
            for nr in fp.named_ranges
        ],
        "input_cells": [
            {"cell_ref": c.cell_ref, "sheet": c.sheet, "cached_value": c.cached_value}
            for c in fp.input_cells
        ],
        "output_cells": [
            {
                "cell_ref": c.cell_ref,
                "sheet": c.sheet,
                "formula": c.formula,
                "cached_value": c.cached_value,
                "cache_status": c.cache_status,
            }
            for c in fp.output_cells
        ],
        "calculation_chain": fp.calculation_chain[:50],  # Limit for readability
        "vba_modules": [
            {
                "filename": v.filename,
                "block_type": v.block_type,
                "signatures": v.signatures,
                "code_lines": len(v.code.splitlines()) if v.code else 0,
            }
            for v in fp.vba_modules
        ],
        "cache_quality": fp.cache_quality,
    }


def _get_output_cells(fp: FormulaPayload) -> list:
    """Get output cells — use graph classification if available, else fallback."""
    if fp.output_cells:
        return fp.output_cells
    # Fallback: output cells = formula cells not referenced by any other formula
    all_refs = set()
    for cell in fp.formulas:
        for ref in cell.references:
            all_refs.add(ref)
    return [c for c in fp.formulas if c.cell_ref not in all_refs]


def generate_test_stubs(fp: FormulaPayload, stem: str) -> str:
    """Generate pytest test stubs from output cells with cached values."""
    lines = [
        f'"""Auto-generated tests from XLSX extraction — {stem}."""',
        "",
        "import pytest",
        "",
        f"# Source: {stem}",
        f"# Extraction date: auto-generated by WRK-1247 POC",
        "",
    ]

    output_cells = _get_output_cells(fp)
    test_count = 0
    for cell in output_cells:
        if cell.cache_status != "cached_ok" or cell.cached_value is None:
            continue
        safe_ref = cell.cell_ref.replace("$", "").lower()
        safe_sheet = "".join(c if c.isalnum() else "_" for c in cell.sheet).lower()
        func_name = f"test_{safe_sheet}_{safe_ref}_from_xlsx"

        lines.append(f"def {func_name}():")
        extracted_label = f"Extracted: {cell.sheet}!{cell.cell_ref} = {cell.formula}"
        if '"' in cell.formula:
            # Use comment to avoid triple-quote docstring breakage
            lines.append(f"    # {extracted_label}")
        else:
            lines.append(f'    """{extracted_label}"""')

        if isinstance(cell.cached_value, (int, float)):
            lines.append(f"    expected = {cell.cached_value}")
            lines.append(f"    # result = <function>(<inputs>)  # TODO: wire implementation")
            lines.append(f"    # assert result == pytest.approx(expected, rel=1e-6)")
        else:
            lines.append(f"    expected = {cell.cached_value!r}")
            lines.append(f"    # result = <function>(<inputs>)  # TODO: wire implementation")
            lines.append(f"    # assert result == expected")
        lines.append(f"    assert expected is not None  # placeholder until implementation")
        lines.append("")
        test_count += 1

    if test_count == 0:
        lines.append("def test_no_cached_outputs_available():")
        lines.append('    """No output cells with cached values found."""')
        lines.append("    pytest.skip('No cached output values in source XLSX')")
        lines.append("")

    return "\n".join(lines), test_count


def generate_archive_yaml(fp: FormulaPayload, entry: dict, stem: str) -> dict:
    """Generate dark-intelligence archive YAML from extraction results."""
    # Build name map from named ranges
    name_map = {}
    for nr in fp.named_ranges:
        name_map[nr.cell_ref] = nr.name

    archive = {
        "source_type": "excel",
        "source_description": f"Engineering calculation spreadsheet ({entry.get('domain', 'unknown')} domain)",
        "extracted_date": time.strftime("%Y-%m-%d"),
        "legal_scan_passed": False,
        "category": entry.get("domain", "unknown"),
        "subcategory": stem,
        "equations": [],
        "inputs": [],
        "outputs": [],
        "worked_examples": [],
        "assumptions": [],
        "references": [],
        "notes": f"Auto-extracted by WRK-1247 POC. Cache quality: {fp.cache_quality}",
    }

    for cell in fp.input_cells:
        cell_id = f"{cell.sheet}!{cell.cell_ref}"
        name = name_map.get(cell.cell_ref, cell.cell_ref)
        archive["inputs"].append({
            "name": name,
            "symbol": name,
            "unit": "",
            "test_value": cell.cached_value,
        })

    for cell in fp.formulas:
        cell_id = f"{cell.sheet}!{cell.cell_ref}"
        # Skip input cells
        if any(ic.cell_ref == cell.cell_ref and ic.sheet == cell.sheet for ic in fp.input_cells):
            continue
        name = name_map.get(cell.cell_ref, cell.cell_ref)
        archive["equations"].append({
            "name": name,
            "excel_formula": cell.formula,
            "latex": "",
            "description": f"Cell {cell.cell_ref} in {cell.sheet}",
        })

    for cell in _get_output_cells(fp):
        if cell.cache_status != "cached_ok" or cell.cached_value is None:
            continue
        name = name_map.get(cell.cell_ref, cell.cell_ref)
        archive["outputs"].append({
            "name": name,
            "symbol": name,
            "unit": "",
            "test_expected": cell.cached_value,
            "tolerance": 1e-6,
        })

    return archive


def process_file(entry: dict, parser: FormulaXlsxParser) -> dict:
    """Process a single XLSX file and return results."""
    filepath = entry["path"]
    filename = entry["filename"]
    stem = sanitize_stem(filename)
    domain = entry.get("domain", "unknown")
    size_mb = entry.get("size_mb", 0)

    result = {
        "filename": filename,
        "stem": stem,
        "domain": domain,
        "size_mb": size_mb,
        "status": "pending",
    }

    # Skip very large files
    if size_mb > MAX_SIZE_MB:
        result["status"] = "skipped"
        result["reason"] = f"File too large ({size_mb:.1f} MB > {MAX_SIZE_MB} MB limit)"
        return result

    # Check file exists
    if not Path(filepath).exists():
        result["status"] = "skipped"
        result["reason"] = f"File not found: {filepath}"
        return result

    try:
        t0 = time.time()
        manifest = parser.parse(filepath, domain)
        elapsed = time.time() - t0

        fp = manifest.formula_payload
        if fp is None:
            result["status"] = "error"
            result["reason"] = "No formula payload in manifest"
            return result

        result["extraction_time_s"] = round(elapsed, 2)
        result["cache_quality"] = fp.cache_quality
        result["formulas_found"] = len(fp.formulas)
        result["named_ranges_found"] = len(fp.named_ranges)
        result["input_cells"] = len(fp.input_cells)
        result["output_cells"] = len(_get_output_cells(fp))
        result["chain_length"] = len(fp.calculation_chain)
        result["vba_modules"] = len(fp.vba_modules)

        # Write outputs
        file_dir = OUTPUT_DIR / stem
        file_dir.mkdir(parents=True, exist_ok=True)

        # 1. Formula manifest YAML
        fp_dict = formula_payload_to_dict(fp)
        with open(file_dir / "formulas.yaml", "w") as f:
            yaml.dump(fp_dict, f, default_flow_style=False, sort_keys=False)

        # 2. Archive YAML
        archive = generate_archive_yaml(fp, entry, stem)
        with open(file_dir / "archive.yaml", "w") as f:
            yaml.dump(archive, f, default_flow_style=False, sort_keys=False)

        # 3. Test stubs
        tests_dir = file_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        test_code, test_count = generate_test_stubs(fp, stem)
        with open(tests_dir / f"test_{stem}.py", "w") as f:
            f.write(test_code)
        result["tests_generated"] = test_count

        result["status"] = "success"

    except Exception as exc:
        result["status"] = "error"
        result["reason"] = str(exc)
        result["traceback"] = traceback.format_exc()

    return result


def main():
    print("=" * 70)
    print("WRK-1247: XLSX Formula Extraction POC — Step 11")
    print("=" * 70)

    with open(POC_LIST) as f:
        poc = yaml.safe_load(f)

    files = poc.get("selected_files", [])
    print(f"\nProcessing {len(files)} files...\n")

    parser = FormulaXlsxParser()
    results = []

    for i, entry in enumerate(files, 1):
        print(f"[{i:2d}/{len(files)}] {entry['filename'][:60]}...")
        result = process_file(entry, parser)
        results.append(result)

        status = result["status"]
        if status == "success":
            cq = result.get("cache_quality", {})
            print(f"        OK: {result['formulas_found']} formulas, "
                  f"{result['named_ranges_found']} named ranges, "
                  f"{result['tests_generated']} tests, "
                  f"cache: {cq.get('cached_ok', 0)}/{cq.get('total_formulas', 0)} ok "
                  f"({result['extraction_time_s']}s)")
        elif status == "skipped":
            print(f"        SKIP: {result['reason']}")
        else:
            print(f"        ERROR: {result.get('reason', 'unknown')}")

    # Write yield report
    report = {
        "wrk_id": "WRK-1247",
        "stage": "POC Extraction",
        "date": time.strftime("%Y-%m-%d"),
        "files_processed": len(results),
        "success": sum(1 for r in results if r["status"] == "success"),
        "skipped": sum(1 for r in results if r["status"] == "skipped"),
        "errors": sum(1 for r in results if r["status"] == "error"),
        "total_formulas": sum(r.get("formulas_found", 0) for r in results),
        "total_named_ranges": sum(r.get("named_ranges_found", 0) for r in results),
        "total_tests": sum(r.get("tests_generated", 0) for r in results),
        "results": results,
    }

    report_path = OUTPUT_DIR / "yield-report.yaml"
    with open(report_path, "w") as f:
        yaml.dump(report, f, default_flow_style=False, sort_keys=False)

    print(f"\n{'=' * 70}")
    print(f"YIELD REPORT")
    print(f"{'=' * 70}")
    print(f"Files: {report['success']} success, {report['skipped']} skipped, {report['errors']} errors")
    print(f"Total formulas: {report['total_formulas']}")
    print(f"Total named ranges: {report['total_named_ranges']}")
    print(f"Total tests generated: {report['total_tests']}")
    print(f"\nReport: {report_path}")


if __name__ == "__main__":
    main()
