#!/usr/bin/env python3
"""check_config_drift.py — Agent harness file drift detector (WRK-1094).

Checks that CLAUDE.md, AGENTS.md, CODEX.md, GEMINI.md in each repo:
  - Exist (FAIL for required files, WARN for optional)
  - Stay within the 20-line limit (FAIL for new regressions, WARN for known debt)
  - AGENTS.md contains valid YAML frontmatter with required fields (FAIL if absent)

Usage:
    uv run --no-project python scripts/quality/check_config_drift.py [OPTIONS]

Options:
    --repo <name>        Restrict to one repo (e.g. assethold)
    --update-baseline    Write current violations to baseline file
    --format text|json   Output format (default: text)
"""

from __future__ import annotations

import argparse
import datetime
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Constants / config
LINE_LIMIT = 20

# Files required (absence → FAIL) vs optional (absence → WARN)
REQUIRED_FILES = ["CLAUDE.md", "AGENTS.md"]
OPTIONAL_FILES = ["CODEX.md", "GEMINI.md"]
HARNESS_FILES = REQUIRED_FILES + OPTIONAL_FILES

AGENTS_REQUIRED_FIELDS = [
    "purpose",
    "entry_points",
    "test_command",
    "depends_on",
    "maturity",
]

REPO_MAP: dict[str, str] = {
    "workspace-hub": "",
    "assetutilities": "assetutilities",
    "digitalmodel": "digitalmodel",
    "worldenergydata": "worldenergydata",
    "assethold": "assethold",
    "OGManufacturing": "OGManufacturing",
}

DEFAULT_BASELINE = Path("config/quality/config-drift-baseline.yaml")


# ---------------------------------------------------------------------------
# Data types
@dataclass
class Finding:
    repo: str
    file: str
    rule: str
    severity: str  # "FAIL" | "WARN"
    detail: str


# ---------------------------------------------------------------------------
# Baseline helpers
# ---------------------------------------------------------------------------


def load_baseline(path: Path) -> dict:
    """Load baseline YAML; return empty dict if file absent."""
    if not path.exists():
        return {}
    try:
        data = yaml.safe_load(path.read_text()) or {}
        return data
    except yaml.YAMLError as exc:
        print(f"WARNING: could not parse baseline {path}: {exc}", file=sys.stderr)
        return {}


def _is_in_baseline(baseline: dict, repo: str, file: str, rule: str) -> bool:
    """Return True if the (repo, file, rule) triple exists in the baseline violations list."""
    for entry in baseline.get("violations", []):
        if (
            entry.get("repo") == repo
            and entry.get("file") == file
            and entry.get("rule") == rule
        ):
            return True
    return False


def write_baseline(findings: list[Finding], path: Path) -> None:
    """Write current violations to the baseline file."""
    violations = [
        {"repo": f.repo, "file": f.file, "rule": f.rule}
        for f in findings
        if f.rule == "line_limit"
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# auto-generated by check_config_drift.py --update-baseline",
        f'generated_at: "{ts}"',
        "violations:",
    ]
    for v in violations:
        lines += [f"  - repo: {v['repo']}", f"    file: {v['file']}", f"    rule: {v['rule']}"]
    path.write_text("\n".join(lines) + "\n")
    print(f"Baseline written to {path} ({len(violations)} violations)")


# ---------------------------------------------------------------------------
# Check functions
# ---------------------------------------------------------------------------


def check_line_limit(path: Path, repo: str, baseline: dict) -> list[Finding]:
    """Return findings for files exceeding LINE_LIMIT."""
    try:
        line_count = len(path.read_text().splitlines())
    except OSError as exc:
        return [
            Finding(
                repo=repo,
                file=path.name,
                rule="file_unreadable",
                severity="WARN",
                detail=f"Could not read file: {exc}",
            )
        ]

    if line_count <= LINE_LIMIT:
        return []

    filename = path.name
    in_base = _is_in_baseline(baseline, repo, filename, "line_limit")
    severity = "WARN" if in_base else "FAIL"
    debt_note = " (known debt)" if in_base else " (new regression)"
    detail = f"{line_count} lines (limit {LINE_LIMIT}{debt_note})"
    return [Finding(repo=repo, file=filename, rule="line_limit", severity=severity, detail=detail)]


def _extract_frontmatter(text: str) -> tuple[bool, str]:
    """Return (found, frontmatter_body) for YAML frontmatter block."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return False, ""
    end = -1
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
    if end == -1:
        return False, ""
    body = "\n".join(lines[1:end])
    return True, body


def check_agents_frontmatter(path: Path, repo: str) -> list[Finding]:
    """Check AGENTS.md has valid YAML frontmatter with required fields."""
    try:
        text = path.read_text()
    except OSError as exc:
        return [
            Finding(
                repo=repo,
                file="AGENTS.md",
                rule="file_unreadable",
                severity="WARN",
                detail=f"Could not read file: {exc}",
            )
        ]

    found, body = _extract_frontmatter(text)
    if not found:
        return [
            Finding(
                repo=repo,
                file="AGENTS.md",
                rule="frontmatter_missing",
                severity="FAIL",
                detail="No YAML frontmatter block found",
            )
        ]

    try:
        data = yaml.safe_load(body) or {}
    except yaml.YAMLError as exc:
        return [
            Finding(
                repo=repo,
                file="AGENTS.md",
                rule="frontmatter_invalid_yaml",
                severity="FAIL",
                detail=f"YAML parse error: {exc}",
            )
        ]

    findings: list[Finding] = []
    missing = [f for f in AGENTS_REQUIRED_FIELDS if f not in data]
    if missing:
        findings.append(
            Finding(
                repo=repo,
                file="AGENTS.md",
                rule="frontmatter_missing_fields",
                severity="WARN",
                detail=f"Missing required fields: {', '.join(missing)}",
            )
        )
    return findings


def check_missing_files(repo_path: Path, repo: str) -> list[Finding]:
    """Check for missing harness files; FAIL for required, WARN for optional."""
    findings: list[Finding] = []
    for filename in REQUIRED_FILES:
        if not (repo_path / filename).is_file():
            findings.append(
                Finding(
                    repo=repo,
                    file=filename,
                    rule="file_missing",
                    severity="FAIL",
                    detail=f"{filename} is required but not found",
                )
            )
    for filename in OPTIONAL_FILES:
        if not (repo_path / filename).is_file():
            findings.append(
                Finding(
                    repo=repo,
                    file=filename,
                    rule="file_missing",
                    severity="WARN",
                    detail=f"{filename} is not yet required but absent",
                )
            )
    return findings


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------


def generate_report(findings: list[Finding], output_dir: Path) -> Path:
    """Write YAML report to output_dir; also create a -latest copy."""
    output_dir.mkdir(parents=True, exist_ok=True)

    datestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d")
    report_path = output_dir / f"config-drift-{datestamp}.yaml"
    latest_path = output_dir / "config-drift-latest.yaml"

    fail_count = sum(1 for f in findings if f.severity == "FAIL")
    warn_count = sum(1 for f in findings if f.severity == "WARN")

    data = {
        "generated_at": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "summary": {
            "total": len(findings),
            "fail": fail_count,
            "warn": warn_count,
        },
        "findings": [
            {
                "repo": f.repo,
                "file": f.file,
                "rule": f.rule,
                "severity": f.severity,
                "detail": f.detail,
            }
            for f in findings
        ],
    }

    report_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))
    shutil.copy2(report_path, latest_path)
    return report_path


# ---------------------------------------------------------------------------
# Repo-level orchestration
# ---------------------------------------------------------------------------


def _get_repo_root() -> Path:
    """Return workspace root via git or fallback to script location."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except (subprocess.SubprocessError, OSError):
        pass
    # Fallback: two levels up from this script
    return Path(__file__).parent.parent.parent


def run_checks(
    repos: list[str],
    baseline: dict,
    repo_root: Path,
) -> list[Finding]:
    """Run all checks across specified repos; return combined findings list."""
    all_findings: list[Finding] = []

    for repo_name in repos:
        rel_path = REPO_MAP.get(repo_name, repo_name)
        repo_path = repo_root / rel_path if rel_path else repo_root

        if not repo_path.is_dir():
            all_findings.append(
                Finding(
                    repo=repo_name,
                    file="(repo)",
                    rule="repo_missing",
                    severity="WARN",
                    detail="Repo directory absent/uninitialized — skipping checks",
                )
            )
            continue

        # 1. Missing file checks
        all_findings.extend(check_missing_files(repo_path, repo_name))

        # 2. Line limit checks (only for existing harness files)
        for filename in HARNESS_FILES:
            file_path = repo_path / filename
            if file_path.is_file():
                all_findings.extend(check_line_limit(file_path, repo_name, baseline))

        # 3. AGENTS.md frontmatter (only for submodule repos, not workspace-hub root)
        agents_path = repo_path / "AGENTS.md"
        if agents_path.is_file() and repo_name != "workspace-hub":
            all_findings.extend(check_agents_frontmatter(agents_path, repo_name))

    return all_findings


# ---------------------------------------------------------------------------
# Output formatters
# ---------------------------------------------------------------------------


def _print_text(findings: list[Finding]) -> None:
    if not findings:
        print("OK: no config drift findings")
        return
    for f in findings:
        print(f"[{f.severity}] {f.repo}/{f.file} — {f.rule}: {f.detail}")


def _print_json(findings: list[Finding]) -> None:
    items = [
        {
            "repo": f.repo,
            "file": f.file,
            "rule": f.rule,
            "severity": f.severity,
            "detail": f.detail,
        }
        for f in findings
    ]
    print(json.dumps(items, indent=2))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="Agent harness file drift detector (WRK-1094)")
    parser.add_argument("--repo", metavar="NAME", help="Restrict to one repo")
    parser.add_argument("--update-baseline", action="store_true",
                        help="Write current violations to baseline")
    parser.add_argument("--format", choices=["text", "json"], default="text",
                        help="Output format (default: text)")
    args = parser.parse_args()

    repo_root = _get_repo_root()
    baseline_path = repo_root / DEFAULT_BASELINE
    baseline = load_baseline(baseline_path)

    if args.repo:
        repos = [args.repo]
    else:
        repos = list(REPO_MAP.keys())

    findings = run_checks(repos, baseline, repo_root)

    if args.format == "json":
        _print_json(findings)
    else:
        _print_text(findings)

    if args.update_baseline:
        write_baseline(findings, baseline_path)

    # Write report
    logs_dir = repo_root / "logs" / "quality"
    generate_report(findings, logs_dir)

    fail_findings = [f for f in findings if f.severity == "FAIL"]
    return 1 if fail_findings else 0


if __name__ == "__main__":
    sys.exit(main())
