#!/usr/bin/env python3
"""llm-wiki.py — LLM Wiki CLI for building and maintaining persistent knowledge bases.

Based on Karpathy's LLM Wiki pattern: https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f

Usage:
    uv run scripts/knowledge/llm_wiki.py init <domain>
    uv run scripts/knowledge/llm_wiki.py ingest <file> --wiki <domain>
    uv run scripts/knowledge/llm_wiki.py query "<question>" --wiki <domain>
    uv run scripts/knowledge/llm_wiki.py lint --wiki <domain>
    uv run scripts/knowledge/llm_wiki.py status --wiki <domain>
"""

import argparse
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parents[2]  # workspace-hub root
WIKIS_DIR = REPO_ROOT / "knowledge" / "wikis"


# ──────────────────────────────────────────────────────
# Init: scaffold a new domain wiki
# ──────────────────────────────────────────────────────

INIT_DIRS = [
    "raw/papers",
    "raw/standards",
    "raw/articles",
    "raw/assets",
    "wiki/entities",
    "wiki/concepts",
    "wiki/sources",
    "wiki/comparisons",
    "wiki/visualizations",
]

SCHEMA_TEMPLATE = """# Wiki Schema: {domain}

> Auto-generated by `llm-wiki init` on {date}
> Edit this file to customize wiki conventions for your domain.

## Directory Structure

```
raw/          # Immutable source documents (LLM reads, never modifies)
  papers/     # Academic papers
  standards/  # Standards documents (API, DNV, ISO, etc.)
  articles/   # Web articles, blog posts
  assets/     # Images and figures extracted from sources
wiki/         # LLM-maintained markdown pages
  index.md    # Content catalog — every page listed with link + 1-line summary
  log.md      # Chronological timeline of ingests, queries, lint passes
  overview.md # High-level domain synthesis
  entities/   # Entity pages (specific things: CALM Buoy, FPSO, etc.)
  concepts/   # Concept pages (abstract ideas: VIV, fatigue, catenary)
  sources/    # Source summary pages (one per ingested document)
  comparisons/# Filed query outputs (tables, analyses, comparisons)
  visualizations/ # matplotlib plots, Marp slide decks
```

## Conventions

### Page format
- Title in YAML frontmatter
- Tags for categorization
- Cross-references as markdown links: `[[entity-name]]` or `[text](../concepts/topic.md)`

### Index format (index.md)
```yaml
---
last_updated: YYYY-MM-DD
page_count: N
source_count: N
---

## Entities

| Page | Summary | Last Updated |
|------|---------|-------------|
| [[Page Name]](path) | 1-line summary | YYYY-MM-DD |

## Concepts

...

## Sources

...
```

### Log format (log.md)
Each entry starts with a consistent prefix for easy grep:
```
## [YYYY-MM-DD] ingest | Source Title
- Processed: source_file.pdf
- Pages updated: index.md, entities/entity1.md, concepts/concept1.md
- Notes: <brief notes>

## [YYYY-MM-DD] query | Question text
- Pages consulted: entities/...
- Answer filed: comparisons/...
```

## Ingest Workflow

1. Read source document
2. Extract key entities, concepts, facts
3. Create/update source summary in wiki/sources/
4. Update/create entity pages in wiki/entities/
5. Update/create concept pages in wiki/concepts/
6. Update wiki/index.md with new entries
7. Append entry to wiki/log.md

## Lint Workflow

Check for:
1. Contradictions between pages
2. Stale claims superseded by newer sources
3. Orphan pages (no inbound links)
4. Missing cross-references
5. Concepts mentioned but lacking their own page
6. Data gaps fillable by external sources

## Notes

Edit this file as your wiki conventions evolve. This is the configuration that
makes the LLM a disciplined wiki maintainer rather than a generic chatbot.
"""

INIT_PLACEHOLDER = """# {title}

> Auto-generated by llm-wiki init on {date}

This page serves as a placeholder. Replace with LLM-maintained content.
"""


def cmd_init(args: argparse.Namespace) -> int:
    """Scaffold a new domain wiki directory structure."""
    domain = args.domain.replace(" ", "-").lower()

    wiki_root = WIKIS_DIR / domain
    if wiki_root.exists():
        print(f"[ERROR] Wiki already exists at: {wiki_root}")
        print("Remove it first or choose a different domain name.")
        return 1

    created = []
    for d in INIT_DIRS:
        path = wiki_root / d
        path.mkdir(parents=True, exist_ok=True)
        created.append(str(path.relative_to(REPO_ROOT)))

    # Create empty marker files
    (wiki_root / "raw" / ".gitkeep").touch()
    (wiki_root / "wiki" / ".gitkeep").touch()

    # Create schema file
    schema_path = wiki_root / "CLAUDE.md"
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    schema_content = SCHEMA_TEMPLATE.format(domain=domain, date=now)
    schema_path.write_text(schema_content)
    created.append(str(schema_path.relative_to(REPO_ROOT)))

    # Create index.md
    index_path = wiki_root / "wiki" / "index.md"
    index_content = f"""---
domain: {domain}
created: {now}
last_updated: {now}
page_count: 0
source_count: 0
---

# Knowledge Index: {domain}

*Auto-generated. Updated automatically by llm-wiki ingest.*

## Entities

_No entity pages yet. Ingest a source to begin._

## Concepts

_No concept pages yet._

## Sources

_No sources ingested yet._

## Comparisons

_No query outputs filed yet._
"""
    index_path.write_text(index_content)
    created.append(str(index_path.relative_to(REPO_ROOT)))

    # Create log.md
    log_path = wiki_root / "wiki" / "log.md"
    log_content = f"""# Wiki Log: {domain}

> Auto-generated by llm-wiki init on {now}
> Chronological record of all wiki operations.
> Format: ## [YYYY-MM-DD] operation | Title
"""
    log_path.write_text(log_content)
    created.append(str(log_path.relative_to(REPO_ROOT)))

    # Create overview.md
    overview_path = wiki_root / "wiki" / "overview.md"
    overview_content = INIT_PLACEHOLDER.format(title=f"Overview: {domain.replace('-', ' ').title()}", date=now)
    overview_path.write_text(overview_content)
    created.append(str(overview_path.relative_to(REPO_ROOT)))

    print(f"[OK] Wiki scaffolded: {wiki_root.relative_to(REPO_ROOT)}")
    for p in created:
        print(f"  [created] {p}")
    print()
    print(f"Ready for ingestion. Next step:")
    print(f"  uv run scripts/knowledge/llm_wiki.py ingest <file> --wiki {domain}")
    return 0


# ──────────────────────────────────────────────────────
# Status: report wiki statistics
# ──────────────────────────────────────────────────────


def cmd_status(args: argparse.Namespace) -> int:
    """Report wiki statistics."""
    domain = args.wiki
    wiki_root = WIKIS_DIR / domain

    if not wiki_root.exists():
        available = []
        if WIKIS_DIR.exists():
            available = [d.name for d in WIKIS_DIR.iterdir() if d.is_dir()]
        print(f"[ERROR] Wiki not found: {domain}")
        if available:
            print(f"Available wikis: {', '.join(available)}")
        else:
            print("  (no wikis exist yet)")
        return 1

    # Count files
    counts = {}
    total_wiki_files = 0
    for sub in ["entities", "concepts", "sources", "comparisons", "visualizations"]:
        subdir = wiki_root / "wiki" / sub
        count = len(list(subdir.glob("*.md"))) if subdir.exists() else 0
        counts[sub] = count
        total_wiki_files += count

    # Add root wiki markdown files
    other_count = 0
    if (wiki_root / "wiki").exists():
        other_count = len([f for f in (wiki_root / "wiki").iterdir()
                         if f.suffix == ".md" and f.name not in ("index.md", "log.md")])
        counts["other"] = other_count
        total_wiki_files += other_count
    else:
        counts["other"] = 0

    # Total source files
    total_sources = 0
    if (wiki_root / "raw").exists():
        total_sources = len(list(p for p in (wiki_root / "raw").rglob("*") if not p.name.startswith(".")))

    # Log entries
    log_path = wiki_root / "wiki" / "log.md"
    log_entries = 0
    last_ingest = None
    if log_path.exists():
        text = log_path.read_text()
        log_lines = [l for l in text.splitlines() if l.startswith("## [")]
        log_entries = len(log_lines)
        for line in reversed(log_lines):
            if "ingest" in line.lower():
                parts = line.split("]")[0].replace("## [", "")
                last_ingest = parts
                break

    # Index metadata
    index_path = wiki_root / "wiki" / "index.md"
    index_updated = None
    if index_path.exists():
        text = index_path.read_text()
        for line in text.splitlines():
            if line.startswith("last_updated:"):
                index_updated = line.split(":", 1)[1].strip()
                break

    print(f"=== Wiki Status: {domain} ===")
    print()
    print(f"Location: {wiki_root.relative_to(REPO_ROOT)}")
    print()
    print("Page Counts:")
    for key, val in counts.items():
        print(f"  {key:20s} {val:5d} pages")
    print(f"  {'TOTAL WIKI PAGES':20s} {total_wiki_files:5d}")
    print(f"  {'RAW SOURCE FILES':20s} {total_sources:5d}")
    print()
    print("Index:")
    print(f"  Last updated:       {index_updated or 'never'}")
    print(f"  Log entries:        {log_entries}")
    print(f"  Last ingest:        {last_ingest or 'never'}")

    # Link density analysis
    total_links = 0
    for sub in ["entities", "concepts", "sources", "comparisons"]:
        subdir = wiki_root / "wiki" / sub
        if subdir.exists():
            for f in subdir.glob("*.md"):
                content = f.read_text()
                links = content.count("](")
                total_links += links

    if total_wiki_files > 0:
        avg_links = total_links / total_wiki_files
        print(f"  Total cross-refs:   {total_links}")
        print(f"  Links per page:     {avg_links:.1f}")

    return 0


# ──────────────────────────────────────────────────────
# Ingest: add a source to the wiki (agent-directed)
# ──────────────────────────────────────────────────────


def cmd_ingest(args: argparse.Namespace) -> int:
    """Ingest a source file into the wiki.

    This command prepares the work for the LLM agent to process.
    It copies the source into raw/, and provides structured
    instructions for LLM processing.
    """
    source_path = Path(args.file)
    domain = args.wiki
    wiki_root = WIKIS_DIR / domain

    if not wiki_root.exists():
        print(f"[ERROR] Wiki not found: {domain}")
        print(f"Create it first: llm-wiki init {domain}")
        return 1

    if not source_path.exists():
        print(f"[ERROR] Source file not found: {source_path}")
        return 1

    # Determine target directory based on extension
    ext = source_path.suffix.lower()
    target_dir = wiki_root / "raw" / "papers"

    target_path = target_dir / source_path.name
    if target_path.exists():
        print(f"[WARN] Source already exists in wiki: {target_path}")
        print("Skipping. Use --force to overwrite.")
        if not args.force:
            return 1

    # Copy the source
    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, target_path)
    print(f"[OK] Source copied: {source_path} -> {target_path.relative_to(REPO_ROOT)}")

    # Prepare ingest instructions for the LLM
    size_kb = source_path.stat().st_size / 1024
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    instructions = f"""
## Ingest Request

**File:** {source_path.name}
**Size:** {size_kb:,.0f} KB
**Type:** {ext.lstrip('.')}
**Wiki:** {domain}
**Timestamp:** {now}

### Instructions for the LLM

1. **Read** the source file at `{target_path.relative_to(REPO_ROOT)}`
2. **Extract** the following:
   - Key entities (specific things: equipment, locations, organizations)
   - Key concepts (abstract ideas: methodologies, principles)
   - Key facts, data points, formulas
   - Cross-references to other standards or papers
3. **Create or update** wiki pages:
   - Source summary: `wiki/sources/{source_path.stem}.md`
   - Entity pages: `wiki/entities/<name>.md` (one per key entity)
   - Concept pages: `wiki/concepts/<name>.md` (one per key concept)
4. **Update** `wiki/index.md` with all new page entries
5. **Append** to `wiki/log.md`:
   ```
   ## [{now}] ingest | {source_path.name}
   - File: {source_path.name} ({size_kb:,.0f} KB)
   - Entities extracted: <count>
   - Concepts extracted: <count>
   - Pages created/updated: <list>
   - Notes: <brief notes>
   ```

### Existing Wiki State

{get_wiki_snapshot(wiki_root)}
"""

    print()
    print(instructions)
    return 0


def get_wiki_snapshot(wiki_root: Path) -> str:
    """Generate a brief snapshot of existing wiki pages for context."""
    snapshot_lines = []
    for subdir_name in ["entities", "concepts", "sources"]:
        subdir = wiki_root / "wiki" / subdir_name
        if subdir.exists():
            pages = sorted(subdir.glob("*.md"))
            if pages:
                snapshot_lines.append(f"  {subdir_name}/: {[p.stem for p in pages]}")

    index_path = wiki_root / "wiki" / "index.md"
    if index_path.exists():
        text = index_path.read_text()
        if text.strip():
            snapshot_lines.append("  index.md: [exists with content]")

    if snapshot_lines:
        return "Existing wiki pages:\n" + "\n".join(snapshot_lines)
    return "  (empty wiki - no pages yet)"


# ──────────────────────────────────────────────────────
# Query: ask questions against the wiki
# ──────────────────────────────────────────────────────


def cmd_query(args: argparse.Namespace) -> int:
    """Query the wiki by question.

    Reads index.md to find relevant pages, then synthesizes an answer.
    For a CLI tool without LLM access, this performs a keyword search
    across wiki pages and returns matching results.
    """
    domain = args.wiki
    wiki_root = WIKIS_DIR / domain

    if not wiki_root.exists():
        print(f"[ERROR] Wiki not found: {domain}")
        return 1

    query_text = " ".join(args.question).lower()
    query_words = [w for w in query_text.split() if len(w) > 2]

    if not query_words:
        print("[ERROR] Query too short. Provide meaningful keywords.")
        return 1

    # Search across wiki markdown files
    results = []
    wiki_dir = wiki_root / "wiki"

    for category in ["entities", "concepts", "sources", "comparisons"]:
        subdir = wiki_dir / category
        if not subdir.exists():
            continue

        for md_file in subdir.glob("*.md"):
            content = md_file.read_text()
            matches = sum(1 for word in query_words if word in content.lower())
            if matches > 0:
                results.append({
                    "path": str(md_file.relative_to(REPO_ROOT)),
                    "matches": matches,
                    "content_snippet": content[:300],
                })

    # Sort by relevance
    results.sort(key=lambda x: x["matches"], reverse=True)

    print(f"=== Query: {' '.join(args.question)} ===")
    print(f"    Wiki: {domain}")
    print(f"    Found {len(results)} matching pages")
    print()

    if not results:
        print("No matching pages found.")
        print()
        print("Possible actions:")
        print(f"  - Ingest more sources: ingest <file> --wiki {domain}")
        print(f"  - Check index: status --wiki {domain}")
        return 0

    for i, result in enumerate(results, 1):
        print(f"[{i}] {result['path']}")
        print(f"    Matches: {result['matches']} keywords")
        snippet = result["content_snippet"].strip()
        # Show first non-frontmatter line
        for line in snippet.splitlines():
            line = line.strip()
            if line and not line.startswith("---") and not line.startswith(">:") and not line.startswith("created:") and not line.startswith("last_updated:"):
                print(f"    {line}")
                break
        print()

    if args.file_back:
        output_path = wiki_root / "wiki" / "comparisons" / f"q_auto.md"
        print(f"Would save query results to: {output_path.relative_to(REPO_ROOT)}")

    return 0


# ──────────────────────────────────────────────────────
# Lint: health-check the wiki
# ──────────────────────────────────────────────────────


def cmd_lint(args: argparse.Namespace) -> int:
    """Health-check the wiki and report issues."""
    domain = args.wiki
    wiki_root = WIKIS_DIR / domain

    if not wiki_root.exists():
        print(f"[ERROR] Wiki not found: {domain}")
        return 1

    issues = []

    # 1. Orphan pages (no inbound links from other wiki pages)
    orphan_count = _check_orphan_pages(wiki_root, issues)

    # 2. Check for empty pages
    empty_count = _check_empty_pages(wiki_root, issues)

    # 3. Check index.md consistency
    index_issues = _check_index_consistency(wiki_root, issues)

    # 4. Check log.md format
    log_issues = _check_log_format(wiki_root, issues)

    # 5. Check cross-reference density
    link_density = _check_link_density(wiki_root, issues)

    # Report
    print(f"=== Wiki Lint: {domain} ===")
    print()

    if not issues:
        print("[OK] No issues found. Wiki is healthy!")
        return 0

    print(f"Found {len(issues)} issue(s):")
    print()
    for issue in issues:
        severity = issue["severity"].upper()
        print(f"  [{severity}] {issue['category']}: {issue['message']}")

    print()
    print("Summary:")
    print(f"  Orphan pages:     {orphan_count}")
    print(f"  Empty pages:      {empty_count}")
    print(f"  Index issues:     {index_issues}")
    print(f"  Log issues:       {log_issues}")
    print(f"  Link density:     {link_density:.1f} avg per page")

    return 1 if issues else 0


def _check_orphan_pages(wiki_root: Path, issues: list) -> int:
    """Find pages that no other wiki page links to."""
    wiki_dir = wiki_root / "wiki"
    if not wiki_dir.exists():
        return 0

    # Get all wiki markdown file names
    all_pages = {}
    for category in ["entities", "concepts", "sources", "comparisons"]:
        subdir = wiki_dir / category
        if subdir.exists():
            for md_file in subdir.glob("*.md"):
                all_pages[md_file.name] = md_file

    if not all_pages:
        return 0

    # Build link graph
    linked_to = set()
    MD_LINK_RE = re.compile(r'\]\(([^)]+\.md[^)]*)\)')
    for md_file in all_pages.values():
        content = md_file.read_text()
        links = MD_LINK_RE.findall(content)
        for link in links:
            linked_name = os.path.basename(link)
            linked_to.add(linked_name)

    # Also check index.md
    index_path = wiki_dir / "index.md"
    if index_path.exists():
        content = index_path.read_text()
        links = MD_LINK_RE.findall(content)
        for link in links:
            linked_name = os.path.basename(link)
            linked_to.add(linked_name)

    orphans = set(all_pages.keys()) - linked_to
    orphan_pages = sorted(orphans)

    for page in orphan_pages[:3]:
        issues.append({
            "severity": "warning",
            "category": "orphan",
            "message": f"Page '{page}' has no inbound links from other wiki pages",
        })
    if len(orphan_pages) > 3:
        issues.append({
            "severity": "warning",
            "category": "orphan",
            "message": f"... and {len(orphan_pages) - 3} more orphan pages",
        })

    return len(orphans)


def _check_empty_pages(wiki_root: Path, issues: list) -> int:
    """Find pages that are essentially empty (placeholder only)."""
    wiki_dir = wiki_root / "wiki"
    if not wiki_dir.exists():
        return 0

    empty_count = 0
    for category in ["entities", "concepts", "sources", "comparisons"]:
        subdir = wiki_dir / category
        if not subdir.exists():
            continue
        for md_file in subdir.glob("*.md"):
            content = md_file.read_text()
            lines = [l for l in content.splitlines()
                    if l.strip() and not l.startswith("---")
                    and not l.startswith(">")
                    and not l.startswith("#")
                    and "auto-generated" not in l.lower()
                    and "placeholder" not in l.lower()]
            if len(lines) <= 2:
                empty_count += 1
                issues.append({
                    "severity": "info",
                    "category": "empty",
                    "message": f"Page '{md_file.name}' appears to be a placeholder",
                })

    return empty_count


def _check_index_consistency(wiki_root: Path, issues: list) -> int:
    """Check if index.md exists and has required structure."""
    index_path = wiki_root / "wiki" / "index.md"
    if not index_path.exists():
        issues.append({
            "severity": "critical",
            "category": "index",
            "message": "index.md does not exist",
        })
        return 1

    content = index_path.read_text()
    issue_count = 0

    if not content.startswith("---"):
        issues.append({
            "severity": "warning",
            "category": "index",
            "message": "index.md is missing YAML frontmatter",
        })
        issue_count += 1

    return issue_count


def _check_log_format(wiki_root: Path, issues: list) -> int:
    """Check if log.md exists and has consistent format."""
    log_path = wiki_root / "wiki" / "log.md"
    if not log_path.exists():
        issues.append({
            "severity": "critical",
            "category": "log",
            "message": "log.md does not exist",
        })
        return 1

    content = log_path.read_text()
    issue_count = 0
    entries = re.findall(r'## \[', content)
    if not entries:
        issues.append({
            "severity": "info",
            "category": "log",
            "message": "log.md exists but has no structured entries",
        })
        issue_count += 1

    return issue_count


MD_LINK_RE = re.compile(r'\]\(')

def _check_link_density(wiki_root: Path, issues: list) -> float:
    """Average number of markdown links per wiki page."""
    wiki_dir = wiki_root / "wiki"
    if not wiki_dir.exists():
        return 0.0

    total_links = 0
    total_pages = 0

    for md_file in wiki_dir.rglob("*.md"):
        content = md_file.read_text()
        links = len(MD_LINK_RE.findall(content))
        total_links += links
        total_pages += 1

    avg = total_links / total_pages if total_pages > 0 else 0.0

    if avg < 1.0 and total_pages > 3:
        issues.append({
            "severity": "warning",
            "category": "cross-refs",
            "message": f"Low link density ({avg:.1f} avg/page)",
        })

    return avg


# ──────────────────────────────────────────────────────
# CLI entry point
# ──────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        prog="llm-wiki",
        description="LLM Wiki - Build and maintain persistent knowledge bases using LLMs",
        epilog="See https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f",
    )
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # init
    init_p = subparsers.add_parser("init", help="Scaffold a new domain wiki")
    init_p.add_argument("domain", help="Domain name (e.g., marine-engineering)")

    # status
    status_p = subparsers.add_parser("status", help="Report wiki statistics")
    status_p.add_argument("--wiki", "-w", required=True, help="Wiki domain name")

    # ingest
    ingest_p = subparsers.add_parser("ingest", help="Ingest a source file into the wiki")
    ingest_p.add_argument("file", help="Source file to ingest")
    ingest_p.add_argument("--wiki", "-w", required=True, help="Wiki domain name")
    ingest_p.add_argument("--force", "-f", action="store_true", help="Overwrite existing")

    # query
    query_p = subparsers.add_parser("query", help="Query the wiki")
    query_p.add_argument("question", nargs="*", help="Question to ask")
    query_p.add_argument("--wiki", "-w", required=True, help="Wiki domain name")
    query_p.add_argument("--file-back", action="store_true", help="Save answer to wiki")

    # lint
    lint_p = subparsers.add_parser("lint", help="Health-check the wiki")
    lint_p.add_argument("--wiki", "-w", required=True, help="Wiki domain name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    commands = {
        "init": cmd_init,
        "status": cmd_status,
        "ingest": cmd_ingest,
        "query": cmd_query,
        "lint": cmd_lint,
    }

    handler = commands.get(args.command)
    if handler:
        return handler(args)
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
