module:
  name: marine-structural-analysis
  version: "1.0.0"
  description: "Marine structural analysis module for hull stress calculations"
  type: engineering_calculation
  engineering_discipline: "marine"

execution:
  memory_limit_mb: 8192
  timeout_seconds: 600  # 10 minutes
  max_retries: 2
  numerical_precision: 1e-6
  max_iterations: 10000

inputs:
  required:
    - name: hull_geometry
      type: file
      description: "Hull geometry data with frames, stiffeners, and plates"
      validation: "validate_geometry_file"
      format: csv
      units:
        length: "meters"
        area: "square_meters"
      example: "data/sample_hull_geometry.csv"

    - name: material_properties
      type: file
      description: "Material properties for steel and aluminum"
      validation: "validate_materials"
      format: csv
      units:
        stress: "megapascals"
        strain: "dimensionless"
        modulus: "gigapascals"

    - name: loading_scenario
      type: file
      description: "Loading conditions (still water, wave loads, cargo)"
      validation: "validate_loads"
      format: csv
      units:
        force: "kilonewtons"
        moment: "kilonewton_meters"
        pressure: "kilopascals"

  optional:
    - name: analysis_type
      type: string
      default: "linear_static"
      choices: ["linear_static", "nonlinear_static", "fatigue", "buckling"]
      description: "Type of structural analysis to perform"

    - name: mesh_density
      type: string
      default: "medium"
      choices: ["coarse", "medium", "fine", "very_fine"]
      description: "Finite element mesh density"

    - name: classification_society
      type: string
      default: "ABS"
      choices: ["ABS", "DNV", "Lloyd's Register", "BV"]
      description: "Classification society rules to apply"

outputs:
  primary:
    - name: analysis_report
      type: file
      format: html
      path: "reports/marine-structural-analysis/analysis_report.html"
      description: "Interactive HTML report with stress visualizations"

    - name: results_data
      type: file
      format: json
      path: "data/results/marine-structural-analysis/results.json"
      description: "Complete calculation results in JSON format"

    - name: summary_statistics
      type: file
      format: csv
      path: "data/results/marine-structural-analysis/summary.csv"
      description: "Summary of key metrics"

  secondary:
    - name: stress_plots
      type: directory
      path: "reports/marine-structural-analysis/stress_plots/"
      description: "Interactive 3D stress distribution plots"

    - name: deformation_plots
      type: directory
      path: "reports/marine-structural-analysis/deformation_plots/"
      description: "Deformation shape visualizations"

    - name: validation_report
      type: file
      format: html
      path: "reports/marine-structural-analysis/validation.html"
      description: "Classification society rule validation results"

    - name: calculation_log
      type: file
      format: txt
      path: "logs/marine-structural-analysis_calculations.log"
      description: "Detailed calculation trail for audit"

validation:
  engineering_standards:
    - "ABS Rules for Building and Classing Steel Vessels"
    - "DNV Classification Notes No. 30.1"
    - "SNAME T&R Bulletin 5-5A"

  safety_factors:
    - type: "ultimate_strength"
      value: 1.5
      description: "Ultimate strength load factor"

    - type: "fatigue"
      value: 1.0
      description: "Fatigue design factor"

  result_checks:
    - name: "longitudinal_strength"
      condition: "section_modulus >= required_section_modulus"
      critical: true
      standard_reference: "ABS Part 3, Chapter 2, Section 3"

    - name: "local_strength"
      condition: "plate_thickness >= required_thickness"
      critical: true
      standard_reference: "ABS Part 3, Chapter 2, Section 4"

    - name: "buckling_check"
      condition: "buckling_factor >= 1.0"
      critical: true
      standard_reference: "ABS Part 3, Chapter 2, Section 5"

    - name: "deflection_limits"
      condition: "max_deflection < L/500"
      critical: false
      description: "Serviceability check for deflection"

calculations:
  numerical_methods:
    - "finite_element_method"
    - "matrix_structural_analysis"
    - "beam_theory"

  convergence_criteria:
    relative_tolerance: 1e-6
    absolute_tolerance: 1e-9
    max_iterations: 10000
    convergence_norm: "L2"

  verification:
    - method: "hand_calculations"
      description: "Verify critical sections with hand calculations"

    - method: "benchmark_problems"
      description: "Compare against known analytical solutions"

    - method: "commercial_software"
      description: "Cross-check with ANSYS/NASTRAN results"
      tolerance: 0.02  # 2% difference acceptable

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"
  handlers:
    console:
      enabled: true
      level: INFO
    file:
      enabled: true
      path: "logs/marine-structural-analysis.log"
      level: DEBUG
      max_bytes: 10485760  # 10MB
      backup_count: 5
    calculation_log:
      enabled: true
      path: "logs/marine-structural-analysis_calculations.log"
      level: DEBUG
      format: "%(asctime)s - CALC - %(message)s"
    error_file:
      enabled: true
      path: "logs/marine-structural-analysis_errors.log"
      level: ERROR

performance:
  benchmarks:
    - metric: calculation_time
      threshold_seconds: 600  # 10 minutes max
      action_on_exceed: log_warning
      measurement: "wall_clock_time"

    - metric: memory_usage
      threshold_mb: 4096  # 4GB max
      action_on_exceed: log_warning
      measurement: "peak_memory"

    - metric: convergence_iterations
      threshold: 5000
      action_on_exceed: log_warning
      description: "FEM solver iterations"

  optimization:
    sparse_matrix: true
    parallel_processing: true
    max_workers: 4

error_handling:
  strategy: fail_fast
  on_error:
    - log_error_with_inputs
    - save_intermediate_results
    - generate_error_report
    - cleanup_resources
    - notify_user

  retry_conditions:
    - error_type: "ConvergenceError"
      max_retries: 2
      strategy: "increase_iterations"

    - error_type: "MemoryError"
      max_retries: 1
      strategy: "reduce_mesh_density"

quality_assurance:
  peer_review_required: true
  reviewer_qualifications: "Licensed Marine Engineer"
  independent_verification: true
  documentation_required: true
  audit_trail: true

units:
  system: "SI"
  length: "meters"
  force: "kilonewtons"
  stress: "megapascals"
  moment: "kilonewton_meters"
  pressure: "kilopascals"
  temperature: "celsius"

metadata:
  author: "Engineering Team"
  created: "2025-10-22"
  classification_society: "ABS"
  vessel_type: "cargo_ship"
  project_number: "MS-2025-001"
  revision: "A"

data_sources:
  geometry: "data/raw/hull_geometry.csv"
  materials: "data/raw/material_properties.csv"
  loads: "data/raw/loading_scenarios.csv"
  reference_results: "data/reference/commercial_software_results.csv"
