"""Release scan WRK generator — YAML state I/O, version comparison, WRK creation.

Called by nightly-release-scan.sh. Compares installed CLI versions against
config/ai-tools/release-scan-state.yaml and creates a WRK item when upgrades
are detected.

Usage:
    python release_scan_wrk.py --workspace-root /path --versions claude=2.1.74,codex=0.112.0 [--dry-run]
"""

import argparse
import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

PROVIDERS = ("claude", "codex", "gemini")

STATE_REL = Path("config") / "ai-tools" / "release-scan-state.yaml"
PENDING_REL = Path(".claude") / "work-queue" / "pending"
INDEX_SCRIPT_REL = Path(".claude") / "work-queue" / "scripts" / "generate-index.py"
NEXT_ID_REL = Path("scripts") / "work-queue" / "next-id.sh"


def parse_state(state_path: Path) -> dict[str, str]:
    """Read last_seen_version from state YAML. Returns {provider: version}."""
    defaults = {p: "" for p in PROVIDERS}
    if not state_path.exists():
        return defaults
    data = yaml.safe_load(state_path.read_text()) or {}
    versions = data.get("last_seen_version", {}) or {}
    for p in PROVIDERS:
        defaults[p] = str(versions.get(p, "") or "")
    return defaults


def _version_tuple(v: str) -> tuple[int, ...]:
    """Parse '2.1.74' into (2, 1, 74) for comparison."""
    parts = []
    for segment in v.split("."):
        try:
            parts.append(int(segment))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def detect_changes(
    old: dict[str, str], current: dict[str, str]
) -> list[dict[str, str]]:
    """Compare old vs current versions. Return list of upgrade changes.

    Skips: same version, downgrades, and providers with empty current version.
    """
    changes = []
    for provider in PROVIDERS:
        old_v = old.get(provider, "")
        cur_v = current.get(provider, "")
        if not cur_v:
            continue
        if not old_v:
            # First scan for this provider
            changes.append({"provider": provider, "old": "(first scan)", "new": cur_v})
            continue
        if _version_tuple(cur_v) > _version_tuple(old_v):
            changes.append({"provider": provider, "old": old_v, "new": cur_v})
    return changes


def generate_wrk_content(
    wrk_id: str,
    changes: list[dict[str, str]],
    computer: str | None = None,
) -> str:
    """Generate WRK markdown content for detected version changes."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    providers_changed = ", ".join(c["provider"] for c in changes)
    title = f"Release notes review: {providers_changed}"
    host = computer or platform.node() or "unknown"

    # Build version table
    rows = []
    for c in changes:
        rows.append(f"| {c['provider']} | {c['old']} | {c['new']} |")
    table = "\n".join(rows)

    return f"""---
id: {wrk_id}
title: "{title}"
status: pending
priority: medium
complexity: simple
category: harness
subcategory: tooling
target_repos: [workspace-hub]
created_at: "{now}"
computer: {host}
provider: claude
---

# {title}

Nightly release scan detected version changes:

| Provider | Previous | Current |
|----------|----------|---------|
{table}

## Action

Run `/release-notes-adoption` next session to review release notes and
capture any relevant WRK items for new features or breaking changes.

---
*Auto-generated by nightly-release-scan.sh (WRK-1140)*
"""


def update_state(state_path: Path, changes: list[dict[str, str]]) -> None:
    """Update state file with new versions and timestamp."""
    if state_path.exists():
        data = yaml.safe_load(state_path.read_text()) or {}
    else:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        data = {}
    versions = data.get("last_seen_version", {}) or {}
    for c in changes:
        versions[c["provider"]] = c["new"]
    data["last_seen_version"] = versions
    data["last_scan_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    data["last_scan_by"] = "nightly"
    state_path.write_text(yaml.dump(data, default_flow_style=False))


def _touch_scan_timestamp(state_path: Path) -> None:
    """Update last_scan_at/last_scan_by without changing versions."""
    if not state_path.exists():
        return
    data = yaml.safe_load(state_path.read_text()) or {}
    data["last_scan_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    data["last_scan_by"] = "nightly"
    state_path.write_text(yaml.dump(data, default_flow_style=False))


def _get_next_id(workspace_root: Path) -> str:
    """Call next-id.sh to get atomic WRK ID."""
    script = workspace_root / NEXT_ID_REL
    result = subprocess.run(
        ["bash", str(script)],
        capture_output=True,
        text=True,
        cwd=str(workspace_root),
        env={**os.environ, "WORKSPACE_ROOT": str(workspace_root)},
    )
    if result.returncode != 0:
        print(f"ERROR: next-id.sh failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return f"WRK-{result.stdout.strip()}"


def _rebuild_index(workspace_root: Path) -> None:
    """Call generate-index.py to rebuild INDEX.md."""
    script = workspace_root / INDEX_SCRIPT_REL
    if not script.exists():
        return
    subprocess.run(
        ["uv", "run", "--no-project", "python", str(script)],
        cwd=str(workspace_root),
        capture_output=True,
    )


def run_scan(
    workspace_root: Path,
    current_versions: dict[str, str],
    dry_run: bool = False,
    providers: list[str] | None = None,
) -> list[dict[str, str]]:
    """Main scan logic. Returns list of changes detected.

    If dry_run, prints changes but writes nothing.
    """
    state_path = workspace_root / STATE_REL
    old_versions = parse_state(state_path)

    # Filter to requested providers
    if providers:
        filtered_old = {p: old_versions.get(p, "") for p in providers}
        filtered_cur = {p: current_versions.get(p, "") for p in providers}
    else:
        filtered_old = old_versions
        filtered_cur = current_versions

    changes = detect_changes(filtered_old, filtered_cur)

    if not changes:
        print("No version changes detected.")
        if not dry_run:
            # Persist scan timestamp even on no-op so cron health is auditable
            _touch_scan_timestamp(state_path)
        return []

    if dry_run:
        print("DRY RUN — changes detected but not written:")
        for c in changes:
            print(f"  {c['provider']}: {c['old']} -> {c['new']}")
        return changes

    # Get next WRK ID and write file
    wrk_id = _get_next_id(workspace_root)
    content = generate_wrk_content(wrk_id, changes)
    wrk_path = workspace_root / PENDING_REL / f"{wrk_id}.md"
    wrk_path.parent.mkdir(parents=True, exist_ok=True)
    wrk_path.write_text(content)
    print(f"Created {wrk_path}")

    # Update state
    update_state(state_path, changes)
    print(f"Updated {state_path}")

    # Rebuild index
    _rebuild_index(workspace_root)

    return changes


def main() -> None:
    parser = argparse.ArgumentParser(description="Release scan WRK generator")
    parser.add_argument("--workspace-root", required=True, type=Path)
    parser.add_argument("--versions", required=True,
                        help="Comma-separated provider=version pairs")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--providers", default="all",
                        help="Comma-separated providers or 'all'")
    args = parser.parse_args()

    # Parse versions string
    current = {p: "" for p in PROVIDERS}
    for pair in args.versions.split(","):
        pair = pair.strip()
        if "=" in pair:
            k, v = pair.split("=", 1)
            if k.strip() in current:
                current[k.strip()] = v.strip()

    providers = None
    if args.providers != "all":
        providers = [p.strip() for p in args.providers.split(",")]

    run_scan(args.workspace_root, current, dry_run=args.dry_run, providers=providers)


if __name__ == "__main__":
    main()
