#!/usr/bin/env bash
# create-skills.sh - Auto-skill creation from patterns
# Part of RAGS loop: STORE phase with action

set -euo pipefail

# Auto-detect workspace root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
# Path: .claude/skills/coordination/workspace/claude-reflect/scripts - go up 6 levels
WORKSPACE_ROOT="${WORKSPACE_ROOT:-$(dirname "$(dirname "$(dirname "$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")")")")}"
# Fallback detection
if [[ ! -d "${WORKSPACE_ROOT}/.claude" ]]; then
    [[ -d "/mnt/github/workspace-hub" ]] && WORKSPACE_ROOT="/mnt/github/workspace-hub"
    [[ -d "/d/workspace-hub" ]] && WORKSPACE_ROOT="/d/workspace-hub"
fi

# State directory: prefer workspace-hub, fallback to home
if [[ -d "${WORKSPACE_ROOT}/.claude/state" ]]; then
    STATE_DIR="${WORKSPACE_STATE_DIR:-${WORKSPACE_ROOT}/.claude/state}"
else
    STATE_DIR="${WORKSPACE_STATE_DIR:-${HOME}/.claude/state}"
fi

PATTERNS_DIR="${STATE_DIR}/patterns"
SKILLS_BASE="${SKILLS_BASE:-${WORKSPACE_ROOT}/.claude/skills}"
SKILLS_OUTPUT="${SKILLS_BASE}/workspace-hub/auto-generated"
MEMORY_DIR="${STATE_DIR}/memory/patterns"

mkdir -p "$SKILLS_OUTPUT" "$MEMORY_DIR"

# Scoring thresholds
THRESHOLD_CREATE=0.8    # Create new skill
THRESHOLD_ENHANCE=0.6   # Enhance existing
DRY_RUN="${DRY_RUN:-false}"

# Get latest pattern file
PATTERN_FILE="${1:-$(ls -t "$PATTERNS_DIR"/patterns_*.json 2>/dev/null | head -1)}"

if [[ ! -f "$PATTERN_FILE" ]]; then
    echo "Error: No pattern file found" >&2
    exit 1
fi

echo "Processing patterns from: $PATTERN_FILE"
echo "Dry run: $DRY_RUN"
echo ""

# Score a pattern (0.0 - 1.0)
score_pattern() {
    local repos="$1"
    local count="$2"
    local message="$3"

    # Frequency score (based on occurrence count)
    local freq_score=$(echo "scale=2; if ($count > 10) 1.0 else $count / 10" | bc)

    # Cross-repo score (based on number of repos)
    local repo_score=$(echo "scale=2; if ($repos > 10) 1.0 else $repos / 10" | bc)

    # Complexity score (longer messages = more complex patterns)
    local msg_len=${#message}
    local complexity_score=$(echo "scale=2; if ($msg_len > 50) 0.8 else $msg_len / 62.5" | bc)

    # Time savings estimate (cross-repo = high savings)
    local savings_score=$(echo "scale=2; if ($repos > 5) 0.9 else $repos / 5.5" | bc)

    # Weighted final score
    local final=$(echo "scale=2; ($freq_score * 0.3) + ($repo_score * 0.3) + ($complexity_score * 0.2) + ($savings_score * 0.2)" | bc)

    echo "$final"
}

# Create a skill from a pattern
create_skill() {
    local pattern_name="$1"
    local pattern_desc="$2"
    local repos="$3"
    local score="$4"

    # Generate skill name from pattern
    local skill_name=$(echo "$pattern_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | cut -c1-30)
    local skill_dir="${SKILLS_OUTPUT}/${skill_name}"

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would create skill: $skill_name (score: $score)"
        return
    fi

    mkdir -p "$skill_dir"

    cat > "${skill_dir}/SKILL.md" << EOF
---
name: ${skill_name}
description: Auto-generated skill from cross-repo pattern - ${pattern_desc}
version: 1.0.0
category: workspace-hub/auto-generated
type: skill
auto_generated: true
source_pattern: "${pattern_name}"
creation_date: $(date -Iseconds)
score: ${score}
source_repos:
$(echo "$repos" | tr ',' '\n' | sed 's/^/  - /')
---

# ${pattern_name}

> Auto-generated skill from recurring cross-repository pattern

## Pattern Details

**Description:** ${pattern_desc}

**Score:** ${score}

**Detected in repositories:**
$(echo "$repos" | tr ',' '\n' | sed 's/^/- /')

## When to Use

This skill was auto-generated because the pattern "${pattern_name}" was detected across multiple repositories. Use this when performing similar operations.

## Implementation

Based on the detected pattern, this skill captures:

1. The workflow or code pattern identified
2. Common implementation approach
3. Cross-repository applicability

## Examples

*Examples extracted from commit history:*

\`\`\`
Pattern: ${pattern_name}
Repos: ${repos}
\`\`\`

---

*Auto-generated by claude-reflect on $(date "+%Y-%m-%d")*
EOF

    echo "Created skill: $skill_dir"
}

# Store pattern in memory (for patterns below threshold)
store_learning() {
    local pattern="$1"
    local repos="$2"
    local score="$3"

    local memory_file="${MEMORY_DIR}/learnings.yaml"

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would store learning: $pattern (score: $score)"
        return
    fi

    # Append to learnings file
    cat >> "$memory_file" << EOF

- pattern: "${pattern}"
  repos: "${repos}"
  score: ${score}
  date: $(date -Iseconds)
EOF

    echo "Stored learning: $pattern"
}

# Create a skill with an embedded script
create_script_skill() {
    local pattern="$1"
    local examples="$2"
    local repos="$3"
    local score="$4"
    local skill_type="$5"

    # Generate skill name from pattern
    local skill_name=$(echo "$pattern" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/<[^>]*>//g' | cut -c1-30)
    [[ -z "$skill_name" ]] && skill_name="auto-script-$(date +%s)"
    local skill_dir="${SKILLS_OUTPUT}/${skill_name}"

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would create script skill: $skill_name (score: $score)"
        return
    fi

    mkdir -p "$skill_dir"

    # Create SKILL.md
    cat > "${skill_dir}/SKILL.md" << EOF
---
name: ${skill_name}
description: Auto-generated script skill from session patterns
version: 1.0.0
category: workspace-hub/auto-generated
type: script-skill
auto_generated: true
skill_type: ${skill_type}
source_pattern: "${pattern}"
creation_date: $(date -Iseconds)
score: ${score}
source_repos:
$(echo "$repos" | tr ',' '\n' | sed 's/^/  - /')
---

# ${skill_name}

> Auto-generated script skill from repeated command patterns

## Pattern Details

**Type:** ${skill_type}
**Score:** ${score}

**Detected in repositories:**
$(echo "$repos" | tr ',' '\n' | sed 's/^/- /')

## Command Pattern

\`\`\`bash
${pattern}
\`\`\`

## Examples from Sessions

\`\`\`bash
${examples}
\`\`\`

## Script

See \`run.sh\` for the automation script.

---

*Auto-generated by claude-reflect on $(date "+%Y-%m-%d")*
EOF

    # Create a basic run.sh script
    cat > "${skill_dir}/run.sh" << 'SCRIPT_EOF'
#!/usr/bin/env bash
# Auto-generated script from session pattern
# Pattern: PATTERN_PLACEHOLDER
set -euo pipefail

# Cross-platform detection
detect_workspace_hub() {
    case "$(uname -s)" in
        Linux*) for d in "/mnt/github/workspace-hub" "$HOME/github/workspace-hub"; do [[ -d "$d" ]] && echo "$d" && return; done ;;
        Darwin*) for d in "$HOME/github/workspace-hub"; do [[ -d "$d" ]] && echo "$d" && return; done ;;
        MINGW*|MSYS*|CYGWIN*) for d in "/c/github/workspace-hub" "$HOME/github/workspace-hub"; do [[ -d "$d" ]] && echo "$d" && return; done ;;
    esac
    echo "$HOME"
}

WORKSPACE_HUB="$(detect_workspace_hub)"

# TODO: Implement pattern logic here
# Based on pattern: PATTERN_PLACEHOLDER
echo "Script skill: SKILL_NAME_PLACEHOLDER"
echo "Edit this script to implement the pattern."
SCRIPT_EOF

    # Replace placeholders
    sed -i "s|PATTERN_PLACEHOLDER|${pattern}|g" "${skill_dir}/run.sh" 2>/dev/null || \
    sed -i '' "s|PATTERN_PLACEHOLDER|${pattern}|g" "${skill_dir}/run.sh" 2>/dev/null || true
    sed -i "s|SKILL_NAME_PLACEHOLDER|${skill_name}|g" "${skill_dir}/run.sh" 2>/dev/null || \
    sed -i '' "s|SKILL_NAME_PLACEHOLDER|${skill_name}|g" "${skill_dir}/run.sh" 2>/dev/null || true

    chmod +x "${skill_dir}/run.sh"

    echo "Created script skill: $skill_dir"
}

# Enhance existing skill with new script or pattern
enhance_skill() {
    local skill_dir="$1"
    local pattern="$2"
    local examples="$3"
    local score="$4"

    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would enhance skill: $skill_dir"
        return
    fi

    local enhancement_file="${skill_dir}/ENHANCEMENTS.md"

    cat >> "$enhancement_file" << EOF

## Enhancement $(date "+%Y-%m-%d")

**Pattern:** ${pattern}
**Score:** ${score}

\`\`\`bash
${examples}
\`\`\`

EOF

    echo "Enhanced skill: $skill_dir"
}

# Process script ideas if available
process_script_ideas() {
    local script_ideas_file="${PATTERNS_DIR}/script-ideas_*.json"
    local latest_ideas=$(ls -t $script_ideas_file 2>/dev/null | head -1)

    if [[ ! -f "$latest_ideas" ]]; then
        echo "No script ideas file found, skipping script-based skill creation"
        return
    fi

    echo ""
    echo "=== Processing Script Ideas ==="
    echo ""

    local scripts_created=0

    while IFS='|' read -r pattern examples repos score skill_type; do
        [[ -z "$pattern" ]] && continue

        echo "Script Idea: \"${pattern:0:40}...\""
        echo "  Type: $skill_type | Score: $score"

        if (( $(echo "$score >= $THRESHOLD_CREATE" | bc -l) )); then
            echo "  Action: CREATE SCRIPT SKILL ⭐⭐⭐"
            create_script_skill "$pattern" "$examples" "$repos" "$score" "$skill_type"
            ((scripts_created++)) || true
        elif (( $(echo "$score >= $THRESHOLD_ENHANCE" | bc -l) )); then
            echo "  Action: STORE FOR ENHANCEMENT ⭐⭐"
            store_learning "$pattern" "$repos" "$score"
        else
            echo "  Action: STORE LEARNING ⭐"
            store_learning "$pattern" "$repos" "$score"
        fi
        echo ""
    done < <(jq -r '.skill_candidates[] | "\(.pattern)|\(.examples | join("; "))|\(.repos | join(","))|\(.score)|\(.skill_type)"' "$latest_ideas" 2>/dev/null)

    echo "Script skills created: $scripts_created"
    SKILLS_CREATED=$((SKILLS_CREATED + scripts_created))
}

# Process patterns
echo "=== Processing Cross-Repo Patterns ==="
echo ""

SKILLS_CREATED=0
SKILLS_ENHANCED=0
LEARNINGS_STORED=0

# Extract and process each cross-repo pattern
# Using process substitution to avoid subshell (so counters persist)
while IFS='|' read -r message repos count; do
    repo_count=$(echo "$repos" | tr ',' '\n' | wc -l)
    score=$(score_pattern "$repo_count" "$count" "$message")

    # Truncate message for display
    short_msg="${message:0:50}"

    echo "Pattern: \"$short_msg...\""
    echo "  Repos: $repo_count | Count: $count | Score: $score"

    # Determine action based on score
    if (( $(echo "$score >= $THRESHOLD_CREATE" | bc -l) )); then
        echo "  Action: CREATE SKILL ⭐⭐⭐"
        create_skill "$message" "Pattern detected in $repo_count repositories" "$repos" "$score"
        ((SKILLS_CREATED++)) || true
    elif (( $(echo "$score >= $THRESHOLD_ENHANCE" | bc -l) )); then
        echo "  Action: ENHANCE EXISTING ⭐⭐"
        store_learning "$message" "$repos" "$score"
        ((SKILLS_ENHANCED++)) || true
    else
        echo "  Action: STORE LEARNING ⭐"
        store_learning "$message" "$repos" "$score"
        ((LEARNINGS_STORED++)) || true
    fi
    echo ""
done < <(jq -r '.cross_repo_patterns[] | "\(.message)|\(.repos | join(","))|\(.count)"' "$PATTERN_FILE")

# Update state file
STATE_FILE="${STATE_DIR}/reflect-state.yaml"
if [[ -f "$STATE_FILE" ]] && [[ "$DRY_RUN" != "true" ]]; then
    cat >> "$STATE_FILE" << EOF
last_skill_creation: $(date -Iseconds)
actions_taken:
  skills_created: $SKILLS_CREATED
  skills_enhanced: $SKILLS_ENHANCED
  learnings_stored: $LEARNINGS_STORED
EOF
fi

# Process script ideas for script-based skills
process_script_ideas

echo "=== Summary ==="
echo "Skills Created: $SKILLS_CREATED"
echo "Skills Enhanced: $SKILLS_ENHANCED"
echo "Learnings Stored: $LEARNINGS_STORED"
