#!/usr/bin/env bash
# daily-reflect.sh — Phase 2: Summarise yesterday's git commits across all repos
# Usage: daily-reflect.sh [--workspace DIR] [--date YYYY-MM-DD] [--dry-run]
# WRK-1102 Fix 4: standalone Phase 2 script for comprehensive-learning.sh
set -euo pipefail

WORKSPACE="${WORKSPACE_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || echo ".")}"
DATE="${REFLECT_DATE:-$(date -d yesterday +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)}"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --workspace) WORKSPACE="$2"; shift 2 ;;
        --date)      DATE="$2"; shift 2 ;;
        --dry-run)   DRY_RUN=true; shift ;;
        --help|-h)   echo "Usage: $0 [--workspace DIR] [--date YYYY-MM-DD] [--dry-run]"; exit 0 ;;
        *) shift ;;
    esac
done

REFLECT_DIR="${WORKSPACE}/state/reflect-history"
REPORT_FILE="${REFLECT_DIR}/${DATE}.md"

[[ "$DRY_RUN" == "true" ]] && { echo "daily-reflect: dry-run mode — no writes"; exit 0; }

mkdir -p "$REFLECT_DIR"

# Already ran today — idempotent
if [[ -f "$REPORT_FILE" ]]; then
    echo "daily-reflect: report for ${DATE} already exists — skipping"
    exit 0
fi

{
    echo "# Daily Reflect — ${DATE}"
    echo ""
    echo "Generated by daily-reflect.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    # Summarise commits across hub and known submodule directories
    for repo_dir in "$WORKSPACE" "${WORKSPACE}/digitalmodel" "${WORKSPACE}/assetutilities" \
                    "${WORKSPACE}/worldenergydata" "${WORKSPACE}/assethold" "${WORKSPACE}/ogmanufacturing"; do
        [[ -d "${repo_dir}/.git" ]] || continue
        repo_name=$(basename "$repo_dir")
        commits=$(git -C "$repo_dir" log \
            --after="${DATE} 00:00:00" \
            --before="${DATE} 23:59:59" \
            --oneline --no-merges 2>/dev/null || true)
        if [[ -n "$commits" ]]; then
            echo "## ${repo_name}"
            echo "$commits" | head -20
            echo ""
        fi
    done

} > "$REPORT_FILE"

echo "daily-reflect: wrote ${REPORT_FILE}"
