#!/usr/bin/env bash
# ABOUTME: Weekly audit of installed Claude plugins — version currency, skill overlaps, deprecations.
# ABOUTME: Writes report to docs/reports/claude-plugin-audit-latest.md and commits if changes found.
# Exit 0 = audit ran successfully; Exit 1 = operational failure.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
REPORT="$REPO_ROOT/docs/reports/claude-plugin-audit-latest.md"
PLUGINS_JSON="$HOME/.claude/plugins/installed_plugins.json"
MARKETPLACE="$HOME/.claude/plugins/marketplaces/claude-plugins-official"
DATE=$(date +%Y-%m-%d)

die() { echo "ERROR: $*" >&2; exit 1; }

[ -f "$PLUGINS_JSON" ] || die "installed_plugins.json not found"
[ -d "$MARKETPLACE" ] || die "marketplace directory not found"

# ── Collect installed plugin data ──────────────────────────────────────────

echo "[$DATE] Starting Claude plugin audit..."

INSTALLED_PLUGINS=$(uv run --no-project python - "$PLUGINS_JSON" <<'PY' 2>/dev/null
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
for name, entries in sorted(data.get('plugins', {}).items()):
    for e in entries:
        print(f"{name}|{e.get('version','unknown')}|{e.get('scope','unknown')}|{e.get('gitCommitSha','unknown')[:8]}|{e.get('lastUpdated','unknown')[:10]}")
PY
) || die "Failed to parse installed_plugins.json"

# ── Collect marketplace data ───────────────────────────────────────────────

MARKETPLACE_SHA=""
[ -f "$MARKETPLACE/.gcs-sha" ] && MARKETPLACE_SHA=$(cat "$MARKETPLACE/.gcs-sha" | head -c 12)

AVAILABLE_PLUGINS=$(ls "$MARKETPLACE/plugins/" 2>/dev/null | sort)
AVAILABLE_COUNT=$(echo "$AVAILABLE_PLUGINS" | wc -l)

# ── Check superpowers version specifically ─────────────────────────────────

SP_VERSION="unknown"
SP_CHANGELOG=""
for dir in $(ls -d "$HOME/.claude/plugins/cache/claude-plugins-official/superpowers/"*/ 2>/dev/null | sort -V); do
    ver=$(basename "$dir")
    if [[ "$ver" =~ ^[0-9] ]]; then
        SP_VERSION="$ver"
        if [ -f "$dir/CHANGELOG.md" ]; then
            SP_CHANGELOG=$(head -20 "$dir/CHANGELOG.md")
        fi
    fi
done

# ── Check for deprecated superpowers skills ────────────────────────────────

DEPRECATED_SKILLS=""
SP_CACHE="$HOME/.claude/plugins/cache/claude-plugins-official/superpowers/$SP_VERSION"
if [ -d "$SP_CACHE/skills" ]; then
    while IFS= read -r skill_dir; do
        skill_name=$(basename "$skill_dir")
        if grep -qi 'deprecated' "$skill_dir/SKILL.md" 2>/dev/null; then
            DEPRECATED_SKILLS="$DEPRECATED_SKILLS $skill_name"
        fi
    done < <(find "$SP_CACHE/skills" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
fi

# ── Check custom skill overlaps ────────────────────────────────────────────

CUSTOM_SKILLS_DIR="$REPO_ROOT/.claude/skills"
OVERLAP_COUNT=0
OVERLAPS=""
if [ -d "$CUSTOM_SKILLS_DIR" ]; then
    for pattern in frontend-design code-review skill-creator systematic-debugging writing-plans subagent-driven verification-loop tdd-obra; do
        matches=$(find "$CUSTOM_SKILLS_DIR" -name 'SKILL.md' -path "*/$pattern/*" -not -path '*/_archive/*' 2>/dev/null)
        if [ -n "$matches" ]; then
            OVERLAP_COUNT=$((OVERLAP_COUNT + 1))
            OVERLAPS="$OVERLAPS\n- $pattern: $matches"
        fi
    done
fi

# ── Check for version: unknown plugins ─────────────────────────────────────

UNKNOWN_COUNT=$(echo "$INSTALLED_PLUGINS" | grep '|unknown|' | wc -l)
INSTALLED_COUNT=$(echo "$INSTALLED_PLUGINS" | sort -u -t'|' -k1,1 | wc -l)

# ── Write report ───────────────────────────────────────────────────────────

cat > "$REPORT" << REPORT_EOF
# Claude Plugin Audit — $DATE

Auto-generated by \`scripts/maintenance/claude-plugin-audit.sh\`

## Summary

- **Installed plugins:** $INSTALLED_COUNT
- **Marketplace plugins available:** $AVAILABLE_COUNT
- **Marketplace SHA:** $MARKETPLACE_SHA
- **Plugins with unknown version:** $UNKNOWN_COUNT
- **Custom skill overlaps:** $OVERLAP_COUNT
- **Superpowers version:** $SP_VERSION

## Installed Plugins

| Plugin | Version | Scope | Commit SHA | Last Updated |
|---|---|---|---|---|
$(echo "$INSTALLED_PLUGINS" | sort -u -t'|' -k1,1 | while IFS='|' read -r name ver scope sha updated; do
    echo "| $name | $ver | $scope | \`$sha\` | $updated |"
done)

## Version Alerts

$(if [ "$UNKNOWN_COUNT" -gt 0 ]; then
    echo "**$UNKNOWN_COUNT plugins report \`Version: unknown\`.** These auto-update via marketplace SHA but lack semver tracking."
    echo ""
    echo "$INSTALLED_PLUGINS" | grep '|unknown|' | sort -u -t'|' -k1,1 | while IFS='|' read -r name _ _ _ _; do
        echo "- $name"
    done
else
    echo "All plugins have tracked versions."
fi)

## Superpowers Status

- **Installed version:** $SP_VERSION
$(if [ -n "$DEPRECATED_SKILLS" ]; then
    echo "- **Deprecated skills:**$DEPRECATED_SKILLS"
else
    echo "- **No deprecated skills detected in SKILL.md frontmatter**"
    echo "- **Known deprecated redirects:** brainstorm→brainstorming, write-plan→writing-plans, execute-plan→executing-plans"
fi)

## Custom Skill Overlaps

$(if [ "$OVERLAP_COUNT" -gt 0 ]; then
    echo "$OVERLAP_COUNT custom skills overlap with plugin skills:"
    echo -e "$OVERLAPS"
else
    echo "No overlaps detected."
fi)

## Available but Not Installed

$(comm -23 <(echo "$AVAILABLE_PLUGINS") <(echo "$INSTALLED_PLUGINS" | cut -d'|' -f1 | sed 's/@.*//' | sort -u) | while read -r plugin; do
    echo "- $plugin"
done)
REPORT_EOF

echo "[$DATE] Report written to $REPORT"

# ── Commit if changed ─────────────────────────────────────────────────────

cd "$REPO_ROOT"
if ! git diff --quiet "$REPORT" 2>/dev/null; then
    git add "$REPORT"
    git commit -m "docs(#1473): weekly plugin audit — $DATE" --no-gpg-sign 2>/dev/null || true
    echo "[$DATE] Changes committed"
else
    echo "[$DATE] No changes since last audit"
fi
