#!/usr/bin/env bash
# apply.sh — Phase 5: Generate content via API and write to ecosystem files
# 40% shell, 60% API

phase_apply() {
    local guarded="${IMPROVE_WORKDIR}/guarded.json"
    local api_enhance="${IMPROVE_API_ENHANCE:-false}"

    [[ "$DRY_RUN" == "true" ]] && { echo "improve/apply: dry-run mode, skipping writes"; return 0; }

    local count
    count=$(jq 'length' "$guarded" 2>/dev/null || echo "0")
    [[ "$count" -eq 0 ]] && { echo "improve/apply: no improvements to apply"; return 0; }

    local applied=0

    # Process each accepted improvement
    jq -c '.[]' "$guarded" | while IFS= read -r item; do
        local target target_file action content
        target=$(echo "$item" | jq -r '.target // ""')
        target_file=$(echo "$item" | jq -r '.target_file // ""')
        action=$(echo "$item" | jq -r '.action // ""')
        content=$(echo "$item" | jq -r '.content // ""')

        [[ -z "$target_file" || -z "$content" ]] && continue

        local full_path="${WORKSPACE_HUB}/.claude/${target_file}"

        case "$action" in
            append)
                # Ensure parent directory exists
                mkdir -p "$(dirname "$full_path")" 2>/dev/null
                if [[ -f "$full_path" ]]; then
                    # Append with blank line separator
                    {
                        echo ""
                        echo "<!-- improve: ${DATE_TAG} -->"
                        echo "$content"
                    } >> "$full_path"
                    applied=$((applied + 1))
                    echo "improve/apply: appended to ${target_file}"
                fi
                ;;
            enhance)
                if [[ -f "$full_path" ]]; then
                    if false; then
                        # REMOVED (WRK-1102 Fix 7): api_enhance path deleted — no LLM in nightly pipeline.
                        # IMPROVE_API_ENHANCE=true is no longer supported; all enhance actions
                        # fall through to the deterministic append path below.
                        true
                    else
                        {
                            echo ""
                            echo "<!-- improve: ${DATE_TAG} -->"
                            echo "$content"
                        } >> "$full_path"
                        applied=$((applied + 1))
                        echo "improve/apply: enhanced ${target_file}"
                    fi
                fi
                ;;
            create)
                # Only create if file doesn't exist
                if [[ ! -f "$full_path" ]]; then
                    mkdir -p "$(dirname "$full_path")" 2>/dev/null
                    {
                        echo "<!-- Auto-generated by improve.sh ${DATE_TAG} -->"
                        echo ""
                        echo "$content"
                    } > "$full_path"
                    applied=$((applied + 1))
                    echo "improve/apply: created ${target_file}"
                else
                    echo "improve/apply: skipped create for existing ${target_file}"
                fi
                ;;
        esac
    done

    echo "$applied" > "${IMPROVE_WORKDIR}/changes_count"
    echo "improve/apply: ${applied} changes written"
    return 0
}
