#!/usr/bin/env bash
# log.sh — Phase 6: Record changes to improve-changelog.yaml
# 100% shell, 0% API

phase_log() {
    local guarded="${IMPROVE_WORKDIR}/guarded.json"
    local metrics="${IMPROVE_WORKDIR}/ecosystem_metrics.json"
    local changes_count
    changes_count=$(cat "${IMPROVE_WORKDIR}/changes_count" 2>/dev/null || echo "0")
    local signal_count
    signal_count=$(cat "${IMPROVE_WORKDIR}/signal_count" 2>/dev/null || echo "0")

    # Ensure changelog exists
    if [[ ! -f "$CHANGELOG" ]]; then
        echo "# improve-changelog.yaml" > "$CHANGELOG"
        echo "# Auto-generated by scripts/improve/improve.sh" >> "$CHANGELOG"
        echo "entries: []" >> "$CHANGELOG"
    fi

    # Build change list
    local changes_list=""
    if [[ -f "$guarded" ]] && [[ "$(jq 'length' "$guarded" 2>/dev/null)" -gt 0 ]]; then
        changes_list=$(jq -r '.[] | "    - file: \(.target_file) action: \(.action) reason: \(.reason // "n/a")"' "$guarded" 2>/dev/null)
    fi

    # Get ecosystem metrics
    local total_skills memory_lines warnings
    total_skills=$(jq -r '.total_skills // 0' "$metrics" 2>/dev/null || echo "0")
    memory_lines=$(jq -r '.memory_lines // 0' "$metrics" 2>/dev/null || echo "0")
    warnings=$(jq -r '.warnings | length' "$metrics" 2>/dev/null || echo "0")

    # Append entry (simple YAML append)
    cat >> "$CHANGELOG" <<EOF

- timestamp: "${TIMESTAMP}"
  mode: $(if [[ "$QUICK_MODE" == "true" ]]; then echo "quick"; elif [[ "$DRY_RUN" == "true" ]]; then echo "dry_run"; else echo "full"; fi)
  signals_processed: ${signal_count}
  changes_applied: ${changes_count}
  ecosystem:
    total_skills: ${total_skills}
    memory_lines: ${memory_lines}
    warnings: ${warnings}
${changes_list:+  changes:
$changes_list}
EOF

    echo "improve/log: changelog updated (${changes_count} changes, ${signal_count} signals)"
    return 0
}
