#!/usr/bin/env bash
# Enforce canonical drive paths in tracked drive-index YAML/JSON configs.

set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SELF_DIR" rev-parse --show-toplevel 2>/dev/null || echo "$SELF_DIR")"
DEFAULT_BASELINE="${REPO_ROOT}/config/quality/canonical-drive-paths-baseline.txt"

BASELINE=""
BASELINE_EXPLICIT=0
UPDATE_BASELINE=0
declare -a POSITIONAL=()

while (( $# > 0 )); do
  case "$1" in
    --baseline=*)      BASELINE="${1#*=}"; BASELINE_EXPLICIT=1; shift ;;
    --baseline)        BASELINE="${2:?--baseline requires a path}"; BASELINE_EXPLICIT=1; shift 2 ;;
    --update-baseline) UPDATE_BASELINE=1; shift ;;
    --no-baseline)     BASELINE=""; BASELINE_EXPLICIT=1; shift ;;
    --)                shift; POSITIONAL+=("$@"); break ;;
    -*)                echo "check-canonical-drive-paths: unknown flag: $1" >&2; exit 2 ;;
    *)                 POSITIONAL+=("$1"); shift ;;
  esac
done

if (( ${#POSITIONAL[@]} == 0 )) && (( BASELINE_EXPLICIT == 0 )); then
  BASELINE="$DEFAULT_BASELINE"
fi

declare -a TARGETS=()
if (( ${#POSITIONAL[@]} == 0 )); then
  while IFS= read -r f; do
    case "$f" in
      scripts/data/*.yml|scripts/data/*.yaml|config/drive-index-registry.yml|data/document-index/*.yaml|data/document-index/*.json)
        TARGETS+=("$REPO_ROOT/$f")
        ;;
    esac
  done < <(cd "$REPO_ROOT" && git ls-files)
else
  for arg in "${POSITIONAL[@]}"; do
    if [[ -d "$arg" ]]; then
      while IFS= read -r f; do TARGETS+=("$f"); done < <(find "$arg" -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.json' \))
    elif [[ -f "$arg" ]]; then
      TARGETS+=("$arg")
    else
      echo "check-canonical-drive-paths: path not found: $arg" >&2
      exit 2
    fi
  done
fi

declare -A BASELINE_SET=()
if [[ -n "$BASELINE" && -f "$BASELINE" ]]; then
  while IFS= read -r entry; do
    [[ -z "$entry" || "$entry" == \#* ]] && continue
    BASELINE_SET["$entry"]=1
  done < "$BASELINE"
fi

to_repo_relative() {
  realpath -m --relative-to="$REPO_ROOT" "$1" 2>/dev/null || echo "$1"
}

has_violation() {
  local line="$1"
  local ace_data_re="/mnt/ace-data($|/|[[:space:]\"'])"  # abs-path-allowed
  [[ "$line" == *"/mnt/remote/"* ]] || [[ "$line" =~ $ace_data_re ]]  # abs-path-allowed
}

declare -a NEW_VIOLATIONS=()
declare -a ALL_VIOLATIONS=()

for file in "${TARGETS[@]}"; do
  rel="$(to_repo_relative "$file")"
  line_no=0
  in_alias_block=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line_no=$((line_no + 1))

    if [[ "$rel" == "config/drive-index-registry.yml" ]]; then
      if [[ "$line" =~ ^canonical_aliases:[[:space:]]*$ ]]; then
        in_alias_block=1
        continue
      fi
      if (( in_alias_block == 1 )) && [[ "$line" =~ ^[A-Za-z0-9_-]+:[[:space:]]* ]]; then
        in_alias_block=0
      fi
      (( in_alias_block == 1 )) && continue
    fi

    [[ "$line" == *'# transport-path-allowed' ]] && continue
    if has_violation "$line"; then
      key="${rel}:${line_no}"
      ALL_VIOLATIONS+=("$key")
      if (( UPDATE_BASELINE == 0 )) && [[ -n "${BASELINE_SET[$key]:-}" ]]; then
        continue
      fi
      printf '%s:%d: %s\n' "$rel" "$line_no" "$line"
      NEW_VIOLATIONS+=("$key")
    fi
  done < "$file"
done

if (( UPDATE_BASELINE == 1 )); then
  target="${BASELINE:-$DEFAULT_BASELINE}"
  mkdir -p "$(dirname "$target")"
  {
    echo "# canonical-drive-paths-baseline — regenerated by scripts/enforcement/check-canonical-drive-paths.sh --update-baseline"
    echo "# Each line: <repo-relative-path>:<line>"
    echo "# JSON files cannot carry '# transport-path-allowed'; baseline is their only escape hatch."
    echo "#"
    echo "# Total entries: ${#ALL_VIOLATIONS[@]}"
    printf '%s\n' "${ALL_VIOLATIONS[@]}" | LC_ALL=C sort -u
  } > "$target"
  echo "check-canonical-drive-paths: wrote ${#ALL_VIOLATIONS[@]} baseline entries to $target" >&2
  exit 0
fi

if (( ${#NEW_VIOLATIONS[@]} > 0 )); then
  if [[ "${ALLOW_TRANSPORT_PATHS:-0}" == "1" ]]; then
    echo "check-canonical-drive-paths: ${#NEW_VIOLATIONS[@]} new violation(s); ALLOW_TRANSPORT_PATHS=1 bypass in effect" >&2
    exit 0
  fi
  echo "" >&2
  echo "check-canonical-drive-paths: ${#NEW_VIOLATIONS[@]} NEW violation(s) (not in baseline)." >&2
  echo "  Use canonical /mnt/<drive> paths instead of transport or symlink aliases." >&2  # abs-path-allowed
  echo "  Trailing '# transport-path-allowed' exempts YAML lines; JSON requires baseline entries." >&2
  echo "  Baseline: ${BASELINE:-<none>}" >&2
  exit 1
fi
