"""Synthetic shell-caller contracts; these do not qualify native Claude loading."""
import os
from pathlib import Path
import subprocess

import pytest

from test_soul_auto_load import bash_executable

ROOT = Path(__file__).resolve().parents[2]


def run_shell(script, tmp_path, state="BLOCKED"):
    tools = tmp_path / "bin"
    tools.mkdir(exist_ok=True)
    stub = tools / "uv"
    stub.write_text('#!/usr/bin/env bash\nprintf "%s\\n" "$FIXTURE_STATE"\n'
                    '[[ "$FIXTURE_STATE" == LEGACY || "$FIXTURE_STATE" == NATIVE_VERIFIED ]]\n',
                    encoding="utf-8")
    stub.chmod(0o755)
    env = os.environ.copy()
    env.update(HOME=tmp_path.as_posix(), FIXTURE_STATE=state)
    env["PATH"] = tools.as_posix() + os.pathsep + str(Path(bash_executable()).parent) + os.pathsep + env["PATH"]
    return subprocess.run([bash_executable(), "-c", script], env=env, cwd=tmp_path,
                          capture_output=True, encoding="utf-8", timeout=30)


@pytest.mark.parametrize("state,expected", [("LEGACY", "WARN"), ("NATIVE_VERIFIED", "PASS"),
                                         ("DUAL_VERIFIED", "FAIL"), ("BLOCKED", "FAIL")])
def test_status_separates_legacy_from_verified_native(tmp_path, state, expected):
    script = f'source "{(ROOT / "scripts/setup/lib/emit-machine-status.sh").as_posix()}"\ncheck_dimension_claude_global_pointer'
    result = run_shell(script, tmp_path, state)
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == expected


def test_bootstrap_preserves_generated_legacy_bytes(tmp_path):
    legacy = tmp_path / ".claude/CLAUDE.md"
    legacy.parent.mkdir()
    legacy.write_bytes(b"Generated by scripts/memory/bootstrap-machine.sh\nUnique instructions\n")
    before = legacy.read_bytes()
    source = (ROOT / "scripts/memory/bootstrap-machine.sh").read_text(encoding="utf-8")
    # Execute only the Claude retirement/preservation phase, excluding unrelated
    # machine setup. Markers bound the actual production block, not a copied body.
    block = source[source.index("# 1."):source.index("# 2. Windows-specific")]
    result = run_shell('CLAUDE_DIR="$HOME/.claude"\n' + block, tmp_path)
    assert result.returncode == 0, result.stderr
    assert legacy.read_bytes() == before


def test_drift_fails_admission_before_content_check(tmp_path):
    env = os.environ.copy()
    for key in list(env):
        if key.startswith("GIT_"):
            env.pop(key)
    subprocess.run(["git", "-c", "init.templateDir=", "init", "-q", str(tmp_path)],
                   check=True, env=env, capture_output=True)
    target = tmp_path / "scripts/agents/claude_runtime_state.py"
    target.parent.mkdir(parents=True)
    target.write_text("# Synthetic stub; intercepted by the uv fixture.\n")
    script = f'"{(ROOT / "scripts/enforcement/check-soul-deployment-drift.sh").as_posix()}" --no-fetch'
    result = run_shell(script, tmp_path)
    assert result.returncode == 1, result.stdout + result.stderr
    assert "BLOCKED" in result.stdout
    assert "runtime admission failed" in result.stdout


def test_drift_real_legacy_helper_reads_origin_blob_and_prints_valid_path(tmp_path):
    """Real helper + Git Bash + symlink; synthetic contents, no provider launch."""
    repo, user_root = tmp_path / "repo with spaces", tmp_path / "user with spaces"
    repo.mkdir()
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    env.update(HOME=user_root.as_posix(), PYTHONUTF8="1")
    env["PATH"] = str(Path(bash_executable()).parent) + os.pathsep + env["PATH"]
    subprocess.run(["git", "-c", "init.templateDir=", "init", "-q", str(repo)],
                   check=True, env=env, capture_output=True)
    for relative in ["scripts/agents/claude_runtime_state.py",
                     "scripts/enforcement/check-soul-deployment-drift.sh"]:
        target = repo / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes((ROOT / relative).read_bytes())
    source = repo / "config/agents/claude/SOUL.runtime.md"
    source.parent.mkdir(parents=True)
    source.write_bytes(b"Synthetic immutable origin runtime\n")
    link = user_root / ".claude/CLAUDE.md"
    link.parent.mkdir(parents=True)
    link.symlink_to(source)
    for args in [["add", "config/agents/claude/SOUL.runtime.md"],
                 ["-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
                  "-c", "core.hooksPath=" + (tmp_path / "no-hooks").as_posix(),
                  "-c", "commit.gpgsign=false", "commit", "-qm", "Synthetic fixture"],
                 ["update-ref", "refs/remotes/origin/main", "HEAD"]]:
        subprocess.run(["git", "-C", str(repo), *args], check=True, env=env,
                       capture_output=True)
    command = [bash_executable(), "scripts/enforcement/check-soul-deployment-drift.sh", "--no-fetch"]
    result = subprocess.run(command, cwd=repo, env=env, capture_output=True,
                            encoding="utf-8", timeout=30)
    assert result.returncode == 0, result.stdout + result.stderr
    claude = next(line for line in result.stdout.splitlines() if line.startswith("claude "))
    assert "CURRENT" in claude and "symlink" in claude
    assert claude.split(maxsplit=3)[3] == link.as_posix()
    source.write_bytes(b"Synthetic dirty working tree runtime\n")
    stale = subprocess.run(command, cwd=repo, env=env, capture_output=True,
                           encoding="utf-8", timeout=30)
    assert stale.returncode == 1, stale.stdout + stale.stderr
    claude = next(line for line in stale.stdout.splitlines() if line.startswith("claude "))
    assert "STALE" in claude
    assert not any(" checkout " in line for line in stale.stdout.splitlines()
                   if line.lstrip().startswith("git "))
    assert "pending" in stale.stdout.lower()
