# Agent References Configuration
# This file declares which external agents this repository uses

meta:
  repository: REPO_NAME
  last_updated: "YYYY-MM-DD"
  description: "Agent dependencies for this repository"

universal_agents:
  # From workspace-hub (Tier 1)
  # These are general-purpose agents used across all repositories
  source: "@workspace-hub/.claude/agents/universal/"
  agents:
    # Core development agents
    - coder
    - reviewer
    - tester
    - planner
    - researcher

    # SPARC methodology agents
    - specification
    - pseudocode
    - architecture
    - refinement

    # Visualization agents (for HTML reporting)
    - plotly-visualization-agent
    # - bokeh-dashboard-agent
    # - altair-analysis-agent
    # - d3js-custom-viz-agent

    # Quality agents
    # - code-review-swarm
    # - security-manager

domain_agents:
  # Domain-specific agents from specialized hubs (Tier 2)

  # Engineering agents (from digitalmodel hub)
  # - source: "@digitalmodel/.claude/agents/"
  #   agents:
  #     - orcaflex
  #     - aqwa
  #     - freecad
  #     - gmsh
  #     - cad-engineering-specialist

  # Energy agents (from worldenergydata hub)
  # - source: "@worldenergydata/.claude/agents/"
  #   agents:
  #     - drilling-expert
  #     - oil-and-gas-expert
  #     - financial-analysis

  # Finance agents (from assetutilities hub)
  # - source: "@assetutilities/.claude/agents/"
  #   agents:
  #     - finance-analytics
  #     - workflow-automation

local_agents:
  # Repository-specific agents (Tier 3)
  # These are unique to this repository and not shared

  # - project-specific-workflow
  # - custom-tooling-agent

orchestration:
  # How agents are accessed
  method: "symlink"  # symlink | copy | api | orchestrator

  # Automatic synchronization
  auto_sync: true
  sync_schedule: "daily"  # daily | weekly | manual

  # Agent resolution order
  resolution_order:
    - local     # Check local agents first
    - external  # Then domain agents
    - universal # Finally universal agents

  # Caching
  cache_enabled: true
  cache_ttl_hours: 24

preferences:
  # Default agent selections for task types
  code_generation: "coder"
  code_review: "reviewer"
  testing: "tester"
  documentation: "planner"
  visualization: "plotly-visualization-agent"

  # Complexity-based selection
  simple_tasks: "coder"
  moderate_tasks: "coder"
  complex_tasks: "coder"  # Could use specialized agents

configuration:
  # Agent-specific configurations
  agents: {}
    # Example:
    # orcaflex:
    #   config_file: "config/orcaflex.yaml"
    #   timeout_seconds: 300

notes: |
  Additional notes about agent usage in this repository.

  Usage examples:
  - Via symlink: claude-flow agent run <agent-name>
  - Via orchestrator: agent_orchestrator.sh --agent <name> --description "..."
