# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Build the workspace-hub static GitHub Pages site (stdlib only).

Renders an EXPLICIT ALLOWLIST of public-safe tracked docs — README, the repo
mission/portfolio map, and the skills index. The allowlist is deliberate: the
working tree contains untracked local artifacts (.env, memory/, drafts) and
issue-data dashboards that must never be published; this generator reads only
the named files below, never globs the repo.

Run:  python3 scripts/build_pages.py   (writes public/, gitignored)
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
ASSETS = PUBLIC / "assets"

# slug -> (source file, nav title). Explicit allowlist; nothing else is read.
PAGES = {
    "index": ("README.md", "Overview"),
    "portfolio": ("docs/REPO_MISSION_PORTFOLIO.md", "Repo Portfolio"),
    "skills": ("docs/SKILLS_INDEX.md", "Skills Index"),
}

# Pre-rendered standalone HTML pages copied verbatim into public/ (not markdown).
# slug -> (source html, nav title). Explicit allowlist — public-safe by review:
# the equality matrix exposes only abstract machine role-slugs + verdict enums
# (no hostnames, IPs, paths, or client data). Generated by
# scripts/readiness/build-equality-matrix.py.
# The issue-lifecycle flowchart is a self-contained Mermaid diagram of the
# canonical GitHub-issue workflow method (plan/review/implement/publish/close) —
# no hostnames, IPs, or client data; tracks issue #3237.
# The model-generation pipeline work-review summarizes public OSS engineering in
# vamseeachanta/digitalmodel (MIT) — pipeline diagram, status matrix, merged-PR
# list, and the no-silent-assumptions design note; no hostnames, IPs, or client
# data (all PR/issue references are to the public digitalmodel repo).
# The Deckhand API-reposition work-review summarizes the PUBLIC API-centric
# reposition (POST /api/run → report_url contract, public read tier, website
# API-first reframe, determinism/honesty posture with a live-vs-roadmap table);
# it references only public repos (aceengineer-website, deckhand-sandbox,
# digitalmodel, worldenergydata), refers to the private Deckhand engine
# generically, and contains no client codenames, hostnames, IPs, paths, private
# PR numbers, or secrets.
# The casing-design work-review summarizes public OSS engineering in
# vamseeachanta/digitalmodel (MIT): a public EPA-workshop presentation (Hansen,
# Devon Energy, 2011) turned into the well/tubulars casing design-check layer,
# capabilities explorer and llm-wiki notes; only public repo/issue/PR
# references, no hostnames, IPs, or client data.
HTML_PAGES = {
    "machine-equality-matrix": ("docs/reports/machine-equality-matrix.html", "Machine Equality"),
    "issue-workflow-lifecycle": ("docs/reports/issue-workflow-lifecycle.html", "Issue Lifecycle"),
    "orcaflex-pipeline-worklog": ("docs/reports/orcaflex-pipeline-worklog.html", "Model-Gen Pipeline"),
    "deckhand-api-reposition": ("docs/reports/deckhand-api-reposition-worklog.html", "Deckhand API"),
    "casing-design-worklog": ("docs/reports/casing-design-worklog.html", "Casing Design"),
}

_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_CODE = re.compile(r"`([^`]+)`")


def _inline(t: str) -> str:
    t = _CODE.sub(lambda m: f"<code>{html.escape(m.group(1))}</code>", t)
    t = _BOLD.sub(r"<strong>\1</strong>", t)
    t = _LINK.sub(r'<a href="\2">\1</a>', t)
    return t


def md_to_html(md: str) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i, n = 0, len(lines)
    para: list[str] = []

    def flush():
        if para:
            out.append(f"<p>{_inline(' '.join(para))}</p>")
            para.clear()

    while i < n:
        s = lines[i].strip()
        if s.startswith("```"):
            flush(); i += 1; code = []
            while i < n and not lines[i].strip().startswith("```"):
                code.append(html.escape(lines[i])); i += 1
            i += 1
            out.append("<pre>" + "\n".join(code) + "</pre>"); continue
        if s.startswith("|") and i + 1 < n and re.match(r"^\s*\|[\s:\-|]+\|\s*$", lines[i + 1]):
            flush(); block = [lines[i], lines[i + 1]]; i += 2
            while i < n and lines[i].strip().startswith("|"):
                block.append(lines[i]); i += 1
            cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in block]
            head, _a, *body = cells
            t = ["<div class='tw'><table><thead><tr>"] + [f"<th>{_inline(c)}</th>" for c in head] + ["</tr></thead><tbody>"]
            for row in body:
                t.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>")
            out.append("".join(t) + "</tbody></table></div>"); continue
        m = re.match(r"^(#{1,6})\s+(.*)$", s)
        if m:
            flush(); lvl = len(m.group(1)); out.append(f"<h{lvl}>{_inline(m.group(2))}</h{lvl}>"); i += 1; continue
        if s in ("---", "***", "___"):
            flush(); out.append("<hr>"); i += 1; continue
        if re.match(r"^[-*]\s+", s):
            flush(); items = []
            while i < n and re.match(r"^[-*]\s+", lines[i].strip()):
                items.append(re.sub(r"^[-*]\s+", "", lines[i].strip())); i += 1
            out.append("<ul>" + "".join(f"<li>{_inline(it)}</li>" for it in items) + "</ul>"); continue
        if not s:
            flush(); i += 1; continue
        para.append(s); i += 1
    flush()
    return "\n".join(out)


STYLE = (ROOT / "docs" / "assets" / "brand.css").read_text(encoding="utf-8")


# Per-session review pages (#3298) publish from an enumerated manifest, never a
# glob: build_session_review.py writes docs/reports/sessions/manifest.json listing
# exactly the pages to copy. Pages are sanitized at generation time (public-safe
# by construction), so this builder copies them verbatim — stdlib only here.
SESSIONS_SRC = ROOT / "docs/reports/sessions"


def nav_html() -> str:
    items = [(f"{slug}.html", title) for slug, (_f, title) in PAGES.items()]
    items += [(f"{slug}.html", title) for slug, (_f, title) in HTML_PAGES.items()]
    if (SESSIONS_SRC / "index.html").exists():
        items.append(("sessions/index.html", "Sessions"))
    return '<nav>' + " · ".join(
        f'<a href="{href}">{title}</a>' for href, title in items
    ) + '</nav>'


def build_sessions() -> list[str]:
    """Copy the session index + each manifest-enumerated session page into
    public/sessions/. Enumeration-driven (no glob), mirroring the source tree so
    the index's relative links resolve identically when published."""
    manifest = SESSIONS_SRC / "manifest.json"
    if not manifest.exists():
        return []
    out_dir = PUBLIC / "sessions"
    out_dir.mkdir(parents=True, exist_ok=True)
    built: list[str] = []
    idx = SESSIONS_SRC / "index.html"
    if idx.exists():
        (out_dir / "index.html").write_text(idx.read_text(encoding="utf-8"), encoding="utf-8")
        built.append("sessions/index.html")
    for entry in json.loads(manifest.read_text(encoding="utf-8")):
        src = SESSIONS_SRC / entry["file"]
        if src.exists():
            (out_dir / entry["file"]).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            built.append(f"sessions/{entry['file']}")
        else:
            print(f"  WARN: manifest lists {entry['file']} but it is missing, skipping")
    return built


def shell(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} · workspace-hub</title>
<link rel="stylesheet" href="assets/style.css"></head>
<body><header class="site"><a class="home" href="index.html">workspace-hub</a>{nav_html()}</header>
<main><div class="content">{body}</div></main>
<footer class="site"><p>Multi-repo orchestration &amp; governance hub. Rendered from an explicit public-safe allowlist (README, portfolio map, skills index). <a href="https://github.com/vamseeachanta/workspace-hub">source</a></p></footer>
</body></html>"""


def build():
    PUBLIC.mkdir(exist_ok=True)
    ASSETS.mkdir(exist_ok=True)
    (ASSETS / "style.css").write_text(STYLE, encoding="utf-8")
    built = []
    for slug, (src, title) in PAGES.items():
        path = ROOT / src
        if not path.exists():
            print(f"  WARN: {src} missing, skipping")
            continue
        (PUBLIC / f"{slug}.html").write_text(
            shell(title, md_to_html(path.read_text(encoding="utf-8"))), encoding="utf-8")
        built.append(slug)
    # Pre-rendered standalone HTML: copied verbatim (keeps the matrix's own styling).
    for slug, (src, _title) in HTML_PAGES.items():
        path = ROOT / src
        if not path.exists():
            print(f"  WARN: {src} missing, skipping")
            continue
        (PUBLIC / f"{slug}.html").write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        built.append(slug)
    session_pages = build_sessions()
    print(f"Built {len(built)} pages: {', '.join(s + '.html' for s in built)}")
    if session_pages:
        print(f"Published {len(session_pages)} session page(s): {', '.join(session_pages)}")


if __name__ == "__main__":
    build()
