# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Build the workspace-hub static GitHub Pages site (stdlib only).

Renders an EXPLICIT ALLOWLIST of public-safe tracked docs — README, the repo
mission/portfolio map, and the skills index. The allowlist is deliberate: the
working tree contains untracked local artifacts (.env, memory/, drafts) and
issue-data dashboards that must never be published; this generator reads only
the named files below, never globs the repo.

Run:  python3 scripts/build_pages.py   (writes public/, gitignored)
"""
from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
ASSETS = PUBLIC / "assets"

# slug -> (source file, nav title). Explicit allowlist; nothing else is read.
PAGES = {
    "index": ("README.md", "Overview"),
    "portfolio": ("docs/REPO_MISSION_PORTFOLIO.md", "Repo Portfolio"),
    "skills": ("docs/SKILLS_INDEX.md", "Skills Index"),
}

# Pre-rendered standalone HTML pages copied verbatim into public/ (not markdown).
# slug -> (source html, nav title). Explicit allowlist — public-safe by review:
# the equality matrix exposes only abstract machine role-slugs + verdict enums
# (no hostnames, IPs, paths, or client data). Generated by
# scripts/readiness/build-equality-matrix.py.
# The issue-lifecycle flowchart is a self-contained Mermaid diagram of the
# canonical GitHub-issue workflow method (plan/review/implement/publish/close) —
# no hostnames, IPs, or client data; tracks issue #3237.
HTML_PAGES = {
    "machine-equality-matrix": ("docs/reports/machine-equality-matrix.html", "Machine Equality"),
    "issue-workflow-lifecycle": ("docs/reports/issue-workflow-lifecycle.html", "Issue Lifecycle"),
}

_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_CODE = re.compile(r"`([^`]+)`")


def _inline(t: str) -> str:
    t = _CODE.sub(lambda m: f"<code>{html.escape(m.group(1))}</code>", t)
    t = _BOLD.sub(r"<strong>\1</strong>", t)
    t = _LINK.sub(r'<a href="\2">\1</a>', t)
    return t


def md_to_html(md: str) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i, n = 0, len(lines)
    para: list[str] = []

    def flush():
        if para:
            out.append(f"<p>{_inline(' '.join(para))}</p>")
            para.clear()

    while i < n:
        s = lines[i].strip()
        if s.startswith("```"):
            flush(); i += 1; code = []
            while i < n and not lines[i].strip().startswith("```"):
                code.append(html.escape(lines[i])); i += 1
            i += 1
            out.append("<pre>" + "\n".join(code) + "</pre>"); continue
        if s.startswith("|") and i + 1 < n and re.match(r"^\s*\|[\s:\-|]+\|\s*$", lines[i + 1]):
            flush(); block = [lines[i], lines[i + 1]]; i += 2
            while i < n and lines[i].strip().startswith("|"):
                block.append(lines[i]); i += 1
            cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in block]
            head, _a, *body = cells
            t = ["<div class='tw'><table><thead><tr>"] + [f"<th>{_inline(c)}</th>" for c in head] + ["</tr></thead><tbody>"]
            for row in body:
                t.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>")
            out.append("".join(t) + "</tbody></table></div>"); continue
        m = re.match(r"^(#{1,6})\s+(.*)$", s)
        if m:
            flush(); lvl = len(m.group(1)); out.append(f"<h{lvl}>{_inline(m.group(2))}</h{lvl}>"); i += 1; continue
        if s in ("---", "***", "___"):
            flush(); out.append("<hr>"); i += 1; continue
        if re.match(r"^[-*]\s+", s):
            flush(); items = []
            while i < n and re.match(r"^[-*]\s+", lines[i].strip()):
                items.append(re.sub(r"^[-*]\s+", "", lines[i].strip())); i += 1
            out.append("<ul>" + "".join(f"<li>{_inline(it)}</li>" for it in items) + "</ul>"); continue
        if not s:
            flush(); i += 1; continue
        para.append(s); i += 1
    flush()
    return "\n".join(out)


STYLE = """:root{--fg:#1a2230;--muted:#5b6675;--bg:#f7f8fa;--card:#fff;--line:#e2e6ec;--brand:#5b3fd6}
*{box-sizing:border-box}
body{margin:0;font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--fg);background:var(--bg)}
header.site,footer.site{padding:14px 22px;background:var(--card);border-bottom:1px solid var(--line);display:flex;gap:14px;flex-wrap:wrap;align-items:center}
footer.site{border-top:1px solid var(--line);border-bottom:0;color:var(--muted);font-size:14px;margin-top:48px}
.home{color:var(--brand);font-weight:700;text-decoration:none}
nav a{color:var(--muted);text-decoration:none;font-size:14px}
nav a:hover{color:var(--brand)}
main{max-width:900px;margin:0 auto;padding:28px 22px}
h1{font-size:28px}
.content h2{margin-top:1.5em;border-bottom:1px solid var(--line);padding-bottom:.2em}
.tw{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px;background:var(--card)}
th,td{border:1px solid var(--line);padding:6px 10px;text-align:left}
th{background:#f0f3f7}
pre{background:#0f1722;color:#cfe3ff;padding:14px;border-radius:8px;overflow-x:auto;font-size:13px}
code{background:#eef1f5;padding:1px 5px;border-radius:4px}
a{color:var(--brand)}
hr{border:0;border-top:1px solid var(--line);margin:1.4em 0}
"""


def nav_html() -> str:
    items = [(slug, title) for slug, (_f, title) in PAGES.items()]
    items += [(slug, title) for slug, (_f, title) in HTML_PAGES.items()]
    return '<nav>' + " · ".join(
        f'<a href="{slug}.html">{title}</a>' for slug, title in items
    ) + '</nav>'


def shell(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} · workspace-hub</title>
<link rel="stylesheet" href="assets/style.css"></head>
<body><header class="site"><a class="home" href="index.html">workspace-hub</a>{nav_html()}</header>
<main><div class="content">{body}</div></main>
<footer class="site"><p>Multi-repo orchestration &amp; governance hub. Rendered from an explicit public-safe allowlist (README, portfolio map, skills index). <a href="https://github.com/vamseeachanta/workspace-hub">source</a></p></footer>
</body></html>"""


def build():
    PUBLIC.mkdir(exist_ok=True)
    ASSETS.mkdir(exist_ok=True)
    (ASSETS / "style.css").write_text(STYLE, encoding="utf-8")
    built = []
    for slug, (src, title) in PAGES.items():
        path = ROOT / src
        if not path.exists():
            print(f"  WARN: {src} missing, skipping")
            continue
        (PUBLIC / f"{slug}.html").write_text(
            shell(title, md_to_html(path.read_text(encoding="utf-8"))), encoding="utf-8")
        built.append(slug)
    # Pre-rendered standalone HTML: copied verbatim (keeps the matrix's own styling).
    for slug, (src, _title) in HTML_PAGES.items():
        path = ROOT / src
        if not path.exists():
            print(f"  WARN: {src} missing, skipping")
            continue
        (PUBLIC / f"{slug}.html").write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        built.append(slug)
    print(f"Built {len(built)} pages: {', '.join(s + '.html' for s in built)}")


if __name__ == "__main__":
    build()
