#!/usr/bin/env bash
# ABOUTME: Generate .claude/RESOURCE_INDEX.md — a living catalog of workspace resources
# ABOUTME: Run at session end (Stop hook) so index is fresh for next session
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$WS_ROOT/.claude/RESOURCE_INDEX.md"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- Helpers ---

count_files() {
    find "$1" -maxdepth "${2:-1}" -type f -name "${3:-*}" 2>/dev/null | wc -l | tr -d ' '
}

section() {
    echo ""
    echo "## $1"
    echo ""
}

# --- Collect data ---

# Scripts by category
declare -A script_counts
for dir in "$WS_ROOT"/scripts/*/; do
    [[ -d "$dir" ]] || continue
    name=$(basename "$dir")
    [[ "$name" == _* ]] && continue
    cnt=$(find "$dir" -type f -name "*.sh" 2>/dev/null | wc -l | tr -d ' ')
    (( cnt > 0 )) && script_counts[$name]=$cnt
done

# Config files
config_files=()
while IFS= read -r f; do
    config_files+=("${f#"$WS_ROOT/"}")
done < <(find "$WS_ROOT/config" -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) 2>/dev/null | sort)

# Hooks
hook_files=()
while IFS= read -r f; do
    hook_files+=("${f#"$WS_ROOT/"}")
done < <(find "$WS_ROOT/.claude/hooks" -type f -name "*.sh" 2>/dev/null | sort)

# Skills (top-level categories)
declare -A skill_counts
for dir in "$WS_ROOT"/.claude/skills/*/; do
    [[ -d "$dir" ]] || continue
    name=$(basename "$dir")
    [[ "$name" == _* ]] && continue
    cnt=$(find "$dir" -type f -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
    (( cnt > 0 )) && skill_counts[$name]=$cnt
done

# Agent library
declare -A agent_counts
for dir in "$WS_ROOT"/.claude/agent-library/*/; do
    [[ -d "$dir" ]] || continue
    name=$(basename "$dir")
    cnt=$(find "$dir" -maxdepth 1 -type f -name "*.md" ! -name "README.md" 2>/dev/null | wc -l | tr -d ' ')
    (( cnt > 0 )) && agent_counts[$name]=$cnt
done

# Submodules
submodules=()
while IFS= read -r line; do
    [[ -n "$line" ]] && submodules+=("$line")
done < <(git -C "$WS_ROOT" submodule status 2>/dev/null | awk '{print $2}')

# Key data paths
data_paths=()
for dir in "$WS_ROOT"/data/*/; do
    [[ -d "$dir" ]] || continue
    name=$(basename "$dir")
    cnt=$(find "$dir" -type f 2>/dev/null | wc -l | tr -d ' ')
    data_paths+=("$name ($cnt files)")
done

# Python environment
py_version=$(uv run --no-project --quiet python --version 2>/dev/null | awk '{print $2}' || echo "n/a")
pytest_version=$(uv run --no-project --quiet python -m pytest --version 2>/dev/null | head -1 | awk '{print $2}' || echo "n/a")

# Quota cache age
quota_cache="${HOME}/.cache/agent-quota.json"
quota_age="n/a"
if [[ -f "$quota_cache" ]]; then
    age_sec=$(( $(date +%s) - $(stat -c %Y "$quota_cache" 2>/dev/null || echo 0) ))
    if (( age_sec < 60 )); then
        quota_age="${age_sec}s ago"
    elif (( age_sec < 3600 )); then
        quota_age="$(( age_sec / 60 ))m ago"
    else
        quota_age="$(( age_sec / 3600 ))h ago"
    fi
fi

# --- Generate markdown ---

{
    cat <<HEADER
<!-- AUTO-GENERATED by scripts/generate-resource-index.sh — do not edit -->
<!-- Generated: $TIMESTAMP -->

# Resource Index

> Auto-generated catalog of workspace resources. Regenerated at session end.
> Last built: $TIMESTAMP

HEADER

    section "Quick Reference"
    cat <<'QREF'
| Task | Command |
|------|---------|
| Run tests | `PYTHONPATH="src:../assetutilities/src" uv run --no-project python -m pytest <path> -v --tb=short --noconftest` |
| Query AI quota | `./scripts/ai/assessment/query-quota.sh` |
| Sync usage | `./scripts/ai/assessment/auto-sync-usage.sh` |
| Log usage | `./scripts/ai/assessment/log-usage.sh` |
| Legal scan | `./scripts/legal/legal-sanity-scan.sh --repo=<name>` |
| Repo sync | `./scripts/repository_sync` |
| Work queue index | `uv run --no-project python .claude/work-queue/scripts/generate-index.py` |
| Resource index | `./scripts/generate-resource-index.sh` |
QREF

    section "Scripts"
    echo "| Category | Shell Scripts |"
    echo "|----------|-------------|"
    for cat in $(echo "${!script_counts[@]}" | tr ' ' '\n' | sort); do
        echo "| \`scripts/$cat/\` | ${script_counts[$cat]} |"
    done

    # Key scripts with descriptions (from ABOUTME lines)
    echo ""
    echo "### Key Scripts"
    echo ""
    echo "| Script | Description |"
    echo "|--------|-------------|"
    while IFS= read -r f; do
        rel="${f#"$WS_ROOT/"}"
        desc=$(grep -m1 '^# ABOUTME:' "$f" 2>/dev/null | sed 's/^# ABOUTME: //' || true)
        [[ -n "$desc" ]] && echo "| \`$rel\` | $desc |"
    done < <(find "$WS_ROOT/scripts" -maxdepth 3 -type f -name "*.sh" 2>/dev/null | sort)

    section "Configuration"
    echo "| File | Purpose |"
    echo "|------|---------|"
    for f in "${config_files[@]}"; do
        desc=$(head -3 "$WS_ROOT/$f" 2>/dev/null | grep -oP '(?<=# ABOUTME: ).*' || true)
        [[ -z "$desc" ]] && desc=$(head -3 "$WS_ROOT/$f" 2>/dev/null | grep -oP '(?<=# ).*' | head -1 || true)
        echo "| \`$f\` | ${desc:--} |"
    done

    section "Hooks"
    echo "| Hook | Description |"
    echo "|------|-------------|"
    for f in "${hook_files[@]}"; do
        desc=$(grep -m1 '^# ABOUTME:' "$WS_ROOT/$f" 2>/dev/null | sed 's/^# ABOUTME: //' || true)
        [[ -z "$desc" ]] && desc=$(head -5 "$WS_ROOT/$f" 2>/dev/null | grep -oP '(?<=^# )(?!ABOUTME|!).*' | head -1 || true)
        echo "| \`$f\` | ${desc:--} |"
    done

    section "Skills"
    echo "| Category | Count |"
    echo "|----------|-------|"
    for cat in $(echo "${!skill_counts[@]}" | tr ' ' '\n' | sort); do
        echo "| \`$cat\` | ${skill_counts[$cat]} |"
    done

    section "Agent Library"
    echo "| Category | Agents |"
    echo "|----------|--------|"
    for cat in $(echo "${!agent_counts[@]}" | tr ' ' '\n' | sort); do
        echo "| \`$cat\` | ${agent_counts[$cat]} |"
    done

    section "Submodules"
    echo "| Repository | Status |"
    echo "|-----------|--------|"
    for sub in "${submodules[@]}"; do
        if [[ -d "$WS_ROOT/$sub/.git" || -f "$WS_ROOT/$sub/.git" ]]; then
            branch=$(git -C "$WS_ROOT/$sub" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached")
            echo "| \`$sub\` | $branch |"
        else
            echo "| \`$sub\` | not initialized |"
        fi
    done

    section "Data Directories"
    for entry in "${data_paths[@]}"; do
        echo "- \`data/$entry\`"
    done

    section "AI Agent Quota"
    echo "- **Cache**: \`$quota_cache\` ($quota_age)"
    echo "- **Refresh**: statusline auto-refreshes when cache >15min old"
    echo "- **Manual**: \`./scripts/ai/assessment/query-quota.sh --refresh\`"
    echo ""
    if [[ -f "$quota_cache" ]]; then
        echo "| Provider | Week % | Hours to Reset |"
        echo "|----------|--------|----------------|"
        for p in claude codex gemini; do
            wpct=$(jq -r --arg p "$p" '.agents[] | select(.provider == $p) | .week_pct // "-"' "$quota_cache" 2>/dev/null)
            hrs=$(jq -r --arg p "$p" '.agents[] | select(.provider == $p) | .hours_to_reset // "-"' "$quota_cache" 2>/dev/null)
            echo "| $p | ${wpct}% | $hrs |"
        done
    fi

    section "Environment"
    echo "- **Python**: $py_version"
    echo "- **pytest**: $pytest_version"
    echo "- **PYTHONPATH**: \`src:../assetutilities/src\`"
    echo "- **pytest flags**: \`--noconftest\` (conftest.py py.path.local deprecation)"
    echo "- **OS**: $(uname -s) $(uname -r)"
    echo "- **Shell**: $SHELL"

} > "$OUTPUT"

echo "Generated: $OUTPUT ($(wc -l < "$OUTPUT") lines)"
