#!/usr/bin/env python3
"""
Refresh the agent work queue from GitHub label queries.

Produces a deterministic, auditable Markdown file at notes/agent-work-queue.md.
Issues are sorted by number ascending within each priority tier.

Usage:
    uv run scripts/refresh-agent-work-queue.py             # write to notes/agent-work-queue.md
    uv run scripts/refresh-agent-work-queue.py --dry-run   # print to stdout only
    uv run scripts/refresh-agent-work-queue.py --check-staleness   # check if queue file is stale
    uv run scripts/refresh-agent-work-queue.py --parity-check      # compare file vs live GitHub counts
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
QUEUE_FILE = REPO_ROOT / "notes" / "agent-work-queue.md"
REPO_SLUG = "vamseeachanta/workspace-hub"

LANES = [
    {
        "name": "Agy",
        "label": "lane:agy",
        "key": "AGY",
        "role": "Research / Prep / Large-Doc Ingestion",
    },
    {
        "name": "Claude",
        "label": "lane:claude",
        "key": "CLAUDE",
        "role": "Implementation / Architecture / Orchestration",
    },
    {
        "name": "Codex",
        "label": "lane:codex",
        "key": "CODEX",
        "role": "Tests / Bounded Implementation / Review",
    },
]

DISPATCH_QUEUE_LABEL = "dispatch:ready"


def gh_query_issues(labels: str) -> list[dict]:
    """Query GitHub for open issues matching comma-separated labels."""
    result = subprocess.run(
        [
            "gh", "-R", REPO_SLUG, "issue", "list",
            "-L", "200",
            "--state", "open",
            "--label", labels,
            "--json", "number,title,labels",
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        print(f"Warning: gh query failed for {labels}: {result.stderr}", file=sys.stderr)
        return []
    return json.loads(result.stdout) if result.stdout.strip() else []


def _sort_issues(issues: list[dict]) -> list[dict]:
    """Sort issues by number ascending for deterministic output."""
    return sorted(issues, key=lambda i: i["number"])


def _format_issue_row(idx: int, issue: dict) -> str:
    """Format a single issue as a Markdown table row."""
    num = issue["number"]
    title = issue["title"].replace("|", "\\|")
    return f"| {idx} | #{num} | {title} |"


def _format_priority_section(
    priority: str, issues: list[dict], start_idx: int
) -> tuple[str, int]:
    """Format a priority sub-section. Returns (markdown, next_index)."""
    label = priority.capitalize()
    lines = [f"### {label} Priority", ""]
    sorted_issues = _sort_issues(issues)
    if not sorted_issues:
        lines.append("_No issues at this priority._")
        lines.append("")
        return "\n".join(lines), start_idx

    lines.append("| # | Issue | Title |")
    lines.append("|---|-------|-------|")
    idx = start_idx
    for issue in sorted_issues:
        lines.append(_format_issue_row(idx, issue))
        idx += 1
    lines.append("")
    return "\n".join(lines), idx


def generate_queue_markdown(
    query_fn: callable | None = None,
    now: datetime | None = None,
) -> str:
    """Generate the full queue Markdown.

    Args:
        query_fn: Function(labels_str) -> list[dict]. Defaults to gh_query_issues.
        now: Override timestamp for deterministic tests.

    Returns:
        Complete Markdown string.
    """
    if query_fn is None:
        query_fn = gh_query_issues
    if now is None:
        now = datetime.now(timezone.utc)

    timestamp = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    week_date = now.strftime("%Y-%m-%d")
    lane_data = _collect_lane_data(query_fn)
    lines = _queue_header(week_date)
    lines.extend(_queue_summary(lane_data))
    lines.extend(_lane_sections(lane_data))
    lines.append(
        f"*Auto-generated by refresh-agent-work-queue.py. Last refresh: {timestamp}*"
    )
    lines.append("")
    return "\n".join(lines)

def _collect_lane_data(query_fn: callable) -> dict[str, list[dict]]:
    lane_data: dict[str, list[dict]] = {}
    for lane in LANES:
        labels = f"{DISPATCH_QUEUE_LABEL},{lane['label']}"
        lane_data[lane["key"]] = query_fn(labels)
    return lane_data


def _queue_header(week_date: str) -> list[str]:
    lines: list[str] = []
    lines.append(f"# Label Work Queue - Week of {week_date}")
    lines.append("")
    lines.append(
        "> This file is auto-generated by `scripts/refresh-agent-work-queue.py`."
    )
    lines.append(
        "> **Source of truth**: GitHub Issues with `dispatch:ready` and `lane:*` labels."
    )
    lines.append(
        "> **Refresh**: `uv run scripts/refresh-agent-work-queue.py`"
        " or `./scripts/refresh-agent-work-queue.sh`"
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    return lines


def _queue_summary(lane_data: dict[str, list[dict]]) -> list[str]:
    lines: list[str] = []
    lines.append("## Queue Summary")
    lines.append("")
    lines.append("| Lane | Ready | Label |")
    lines.append("|------|-------|-------|")
    for lane in LANES:
        ready = len(lane_data[lane["key"]])
        lines.append(f"| **{lane['key']}** | {ready} | `{lane['label']}` |")
    lines.append("")
    lines.append("---")
    lines.append("")
    return lines


def _lane_sections(lane_data: dict[str, list[dict]]) -> list[str]:
    lines: list[str] = []
    for lane in LANES:
        issues = _sort_issues(lane_data[lane["key"]])
        lines.append(f"## {lane['name']} Queue ({lane['role']})")
        lines.append("")
        if not issues:
            lines.append("_No dispatch:ready issues in this lane._")
            lines.append("")
        else:
            lines.append("| # | Issue | Title |")
            lines.append("|---|-------|-------|")
            for idx, issue in enumerate(issues, start=1):
                lines.append(_format_issue_row(idx, issue))
            lines.append("")
        lines.append("---")
        lines.append("")
    return lines


STALENESS_THRESHOLD_DAYS = 7


def check_staleness(
    queue_file: Path | None = None,
    now: datetime | None = None,
) -> dict:
    """Check whether the queue file is stale (older than STALENESS_THRESHOLD_DAYS).

    Returns:
        dict with keys: stale (bool), age_days (float|None), last_refresh (str|None),
        threshold_days (int), message (str).
    """
    queue_file = queue_file or QUEUE_FILE
    if now is None:
        now = datetime.now(timezone.utc)

    result = {
        "stale": True,
        "age_days": None,
        "last_refresh": None,
        "threshold_days": STALENESS_THRESHOLD_DAYS,
        "message": "",
    }

    if not queue_file.exists():
        result["message"] = f"Queue file not found: {queue_file}"
        return result

    ts_str = _last_refresh_timestamp(queue_file.read_text())
    if ts_str is None:
        result["message"] = "No timestamp found in queue file."
        return result
    last_refresh = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
    age = now - last_refresh
    age_days = age.total_seconds() / 86400

    result["last_refresh"] = ts_str
    result["age_days"] = round(age_days, 1)
    result["stale"] = age_days > STALENESS_THRESHOLD_DAYS
    if result["stale"]:
        result["message"] = (
            f"STALE: Queue is {result['age_days']} days old "
            f"(threshold: {STALENESS_THRESHOLD_DAYS} days). Run refresh."
        )
    else:
        result["message"] = (
            f"OK: Queue is {result['age_days']} days old "
            f"(threshold: {STALENESS_THRESHOLD_DAYS} days)."
        )
    return result


def _last_refresh_timestamp(content: str) -> str | None:
    pattern = r"Last refresh:\s*(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z?)"
    match = re.search(pattern, content)
    if not match:
        return None
    ts_str = match.group(1)
    return ts_str if ts_str.endswith("Z") else ts_str + "Z"


def parity_check(
    queue_file: Path | None = None,
    query_fn: callable | None = None,
) -> dict:
    """Compare issue counts in the existing queue file against live GitHub.

    Returns:
        dict with keys: parity (bool), drifted_agents (list[dict]), message (str).
    """
    queue_file = queue_file or QUEUE_FILE
    if query_fn is None:
        query_fn = gh_query_issues

    result = {"parity": True, "drifted_agents": [], "message": ""}

    if not queue_file.exists():
        result["parity"] = False
        result["message"] = f"Queue file not found: {queue_file}"
        return result

    content = queue_file.read_text()

    file_counts = _parse_summary_counts(content)

    # Query live counts
    for lane in LANES:
        labels = f"{DISPATCH_QUEUE_LABEL},{lane['label']}"
        live_total = len(query_fn(labels))

        file_total = file_counts.get(lane["key"], 0)
        if live_total != file_total:
            result["parity"] = False
            result["drifted_agents"].append({
                "agent": lane["key"],
                "file_count": file_total,
                "live_count": live_total,
                "delta": live_total - file_total,
            })

    if result["parity"]:
        result["message"] = "PARITY OK: File counts match live GitHub."
    else:
        drifts = ", ".join(
            f"{d['agent']}({d['file_count']}→{d['live_count']})"
            for d in result["drifted_agents"]
        )
        result["message"] = f"DRIFT DETECTED: {drifts}. Run refresh to fix."

    return result


def _parse_summary_counts(content: str) -> dict[str, int]:
    file_counts: dict[str, int] = {}
    for line in content.splitlines():
        for lane in LANES:
            if f"**{lane['key']}**" not in line:
                continue
            nums = re.findall(r"\d+", line)
            if nums:
                file_counts[lane["key"]] = int(nums[-1])
    return file_counts


def main() -> None:
    parser = argparse.ArgumentParser(description="Refresh agent work queue")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing to file",
    )
    parser.add_argument(
        "--check-staleness",
        action="store_true",
        help="Check if queue file is stale (>7 days old)",
    )
    parser.add_argument(
        "--parity-check",
        action="store_true",
        help="Compare file issue counts against live GitHub",
    )
    args = parser.parse_args()

    if args.check_staleness:
        result = check_staleness()
        print(json.dumps(result, indent=2))
        sys.exit(0 if not result["stale"] else 1)

    if args.parity_check:
        result = parity_check()
        print(json.dumps(result, indent=2))
        sys.exit(0 if result["parity"] else 1)

    content = generate_queue_markdown()

    if args.dry_run:
        print(content)
    else:
        QUEUE_FILE.parent.mkdir(parents=True, exist_ok=True)
        QUEUE_FILE.write_text(content)
        print(f"Queue written to {QUEUE_FILE}")
        print(f"Timestamp: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")


if __name__ == "__main__":
    main()
