#!/usr/bin/env bash
# setup-hooks.sh — Install git hooks for workspace-hub on any OS
#
# Works on: Windows (Git Bash / MINGW), Linux, macOS
# No symlinks required — uses core.hooksPath which git supports natively.
#
# Usage:
#   bash scripts/operations/setup-hooks.sh
#
# What it does:
#   1. Sets git config core.hooksPath to .claude/hooks/
#   2. Ensures all hook scripts in .claude/hooks/ are executable
#   3. Creates named hook entry-points (pre-commit, post-merge, post-checkout)
#      that call check-encoding.sh with the right name
#   4. Verifies python3 is available (required by check-encoding.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.claude/hooks"

cd "$REPO_ROOT"

echo "=== workspace-hub hook setup ==="
echo ""

# ── 1. Set core.hooksPath ─────────────────────────────────────────────────────
echo "Setting git core.hooksPath = .claude/hooks ..."
git config core.hooksPath .claude/hooks
echo "  OK — git will resolve hooks from .claude/hooks/ by name"
echo ""

# ── 2. Make all hook scripts executable ──────────────────────────────────────
echo "Making hook scripts executable ..."
find "$HOOKS_DIR" -name "*.sh" -exec chmod +x {} \;
echo "  OK"
echo ""

# ── 3. Create named hook entry-points ────────────────────────────────────────
# With core.hooksPath, git looks for files named 'pre-commit', 'post-merge',
# etc. directly in the hooks dir. We create thin wrappers that delegate to
# check-encoding.sh (self-identifying by $0/basename).

for hook in pre-commit post-merge post-checkout; do
    target="$HOOKS_DIR/$hook"
    if [[ ! -f "$target" ]]; then
        cat > "$target" <<HOOKEOF
#!/usr/bin/env bash
# Auto-generated by setup-hooks.sh — delegates to check-encoding.sh
exec "\$(dirname "\$0")/check-encoding.sh" "\$@"
HOOKEOF
        chmod +x "$target"
        echo "  Created: .claude/hooks/$hook"
    else
        echo "  Exists:  .claude/hooks/$hook (skipped)"
    fi
done
echo ""

# ── 4. Verify uv ─────────────────────────────────────────────────────────
echo "Checking uv availability ..."
if command -v uv >/dev/null 2>&1; then
    version=$(uv --version 2>&1)
    echo "  OK — $version"
    echo "  uv will manage Python for encoding checks (via uv run --no-project python)"
    echo "  uv cache will default to $REPO_ROOT/.claude/state/uv-cache"
else
    echo "  WARNING: uv not found!"
    echo "  The encoding check hook will be skipped until 'uv' is installed."
    echo "  Install: https://docs.astral.sh/uv/getting-started/installation/"
fi
echo ""

# ── 5. Smoke test ─────────────────────────────────────────────────────────────
echo "Running encoding check smoke test ..."
if bash "$HOOKS_DIR/check-encoding.sh" 2>&1; then
    echo "  Encoding check: PASS"
else
    echo "  Encoding check: issues found (see above)"
fi
echo ""

echo "=== Setup complete ==="
echo ""
echo "Hooks active:"
echo "  pre-commit     — blocks commits with UTF-16 / non-UTF-8 files"
echo "  post-merge     — warns after 'git pull' if bad files arrived"
echo "  post-checkout  — warns after branch switch if bad files present"
echo ""
echo "To disable:  git config --unset core.hooksPath"
echo "To re-run:   bash scripts/operations/setup-hooks.sh"
