#!/usr/bin/env python3
"""build_skill_index.py — generate config/agents/skill-index-full.yaml (#3190).

ONE flat entry per SKILL.md across the whole tree (not the 51 curated graph nodes),
so the provider-neutral router covers all skills without rescanning at dispatch.

`when_to_use` precedence (highest-fidelity first), recorded in `when_to_use_source`:
  1. `when_to_use:` frontmatter
  2. `## When to Use` section
  3. `## Trigger` section
  4. backfill: name + description + family   (auto-derived; router down-weights these)

DETERMINISTIC: sorted by id, yaml.safe_dump(sort_keys=True), static date-pinned header
(no timestamp) -> byte-stable unless a SKILL.md changes. Excludes `_archive`/`_*` families.

Usage: python3 build_skill_index.py [--skills-dir .claude/skills] [--out config/agents/skill-index-full.yaml] [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

_HEADER = (
    "# AUTO-GENERATED by scripts/ai/build_skill_index.py (#3190) — do not hand-edit.\n"
    "# Flat per-SKILL.md index for the provider-neutral skill router. Deterministic\n"
    "# (sorted by id, no timestamp). Authored when_to_use lives in each SKILL.md.\n"
)


def _frontmatter_and_body(text: str):
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    fm_lines, i = [], 1
    while i < len(lines) and lines[i].strip() != "---":
        fm_lines.append(lines[i])
        i += 1
    try:
        fm = yaml.safe_load("\n".join(fm_lines)) or {}
    except yaml.YAMLError:
        fm = {}
    body = "\n".join(lines[i + 1:])
    return (fm if isinstance(fm, dict) else {}), body


def _section(body: str, heading: str) -> str:
    # Capture text under an ATX heading at depths ##..#### whose text matches
    # <heading>, body running to the next ATX heading of any level (#3208).
    # Prefer an EXACT heading ("## When to Use") over a PREFIX one ("## When to
    # Use This Skill" / "## When To Use X vs Y") so a canonical section isn't
    # mis-bound by an earlier comparison-style heading (review r3-F1).
    h = re.escape(heading)
    for pat in (
        rf"(?im)^\s*#{{2,4}}\s+{h}\s*$(.*?)(?=^\s*#{{1,6}}\s+|\Z)",      # exact
        rf"(?im)^\s*#{{2,4}}\s+{h}\b[^\n]*$(.*?)(?=^\s*#{{1,6}}\s+|\Z)",  # prefix
    ):
        m = re.search(pat, body, re.S | re.M)
        if m:
            return " ".join(m.group(1).split()).strip()
    return ""


def _normalize(val) -> str:
    if isinstance(val, list):
        return " ".join(str(v) for v in val)
    return str(val or "").strip()


def build_entries(skills_dir) -> list[dict]:
    skills_dir = Path(skills_dir)
    entries = []
    for fam_dir in sorted(skills_dir.iterdir()):
        if not fam_dir.is_dir() or fam_dir.name.startswith("_"):
            continue  # skip _archive / _internal / _core etc.
        family = fam_dir.name
        for sk in sorted(fam_dir.rglob("SKILL.md")):
            rel = sk.relative_to(skills_dir)
            skid = str(rel.parent).replace("\\", "/")
            fm, body = _frontmatter_and_body(sk.read_text(encoding="utf-8", errors="replace"))
            name = _normalize(fm.get("name")) or skid.split("/")[-1]
            desc = _normalize(fm.get("description"))
            if fm.get("when_to_use"):
                wtu, src = _normalize(fm.get("when_to_use")), "frontmatter"
            elif _section(body, "When to Use"):
                wtu, src = _section(body, "When to Use"), "section"
            elif _section(body, "Trigger"):
                wtu, src = _section(body, "Trigger"), "trigger"
            else:
                wtu, src = " ".join(x for x in (name, desc, family) if x), "backfill"
            entries.append({
                "id": skid, "family": family, "name": name,
                "description": desc, "when_to_use": wtu, "when_to_use_source": src,
            })
    entries.sort(key=lambda e: e["id"])
    return entries


def render(entries: list[dict]) -> str:
    return _HEADER + yaml.safe_dump(
        {"skills": entries}, sort_keys=True, default_flow_style=False, allow_unicode=True, width=10000
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--skills-dir", default=".claude/skills")
    ap.add_argument("--out", default="config/agents/skill-index-full.yaml")
    ap.add_argument("--check", action="store_true", help="print to stdout, do not write")
    args = ap.parse_args()
    content = render(build_entries(args.skills_dir))
    if args.check:
        sys.stdout.write(content)
        return 0
    Path(args.out).write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
