#!/usr/bin/env bash
# Daily client team-summary refresh (workspace-hub#3967).
#
#   scripts/reports/team-summary-refresh.sh <client-slug> [--dry-run]
#
# 1. Clones llm-wiki-<client> (TEAM_SUMMARY_REF, default main) into a temp dir.
# 2. Exits quietly when the wiki has not changed since the last summary commit.
# 3. An agent (TEAM_SUMMARY_AGENT=codex|claude, default codex) updates ONLY
#    reports/team-summary/summary.yml from those changes.
# 4. Guard: any other file touched -> fail. Schema and source-existence checks run
#    in build.py; the one canonical PDF is re-rendered and committed only when the
#    facts changed, so git history stays the change history.
# 5. Pushes to the ref it cloned. --dry-run stops after the local commit.
#    TEAM_SUMMARY_SINCE=<sha> overrides the change window (testing).
#
# Owner standing authority for the daily refresh: workspace-hub#3967 (2026-10-08).
set -euo pipefail

CLIENT="${1:?usage: team-summary-refresh.sh <client-slug> [--dry-run]}"
DRY_RUN=0
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=1

HUB="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPO="vamseeachanta/llm-wiki-${CLIENT}"
REF="${TEAM_SUMMARY_REF:-main}"
AGENT="${TEAM_SUMMARY_AGENT:-codex}"
DIR="reports/team-summary"
TODAY="$(date +%F)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "[team-summary] $(date -Is) client=$CLIENT ref=$REF agent=$AGENT"
gh repo clone "$REPO" "$WORK/wiki" -- -q --branch "$REF" --depth 200
cd "$WORK/wiki"

[[ -f "$DIR/summary.yml" ]] || { echo "[team-summary] FAIL: no $DIR/summary.yml in $REPO@$REF"; exit 1; }

last="${TEAM_SUMMARY_SINCE:-$(git log -1 --format=%H -- "$DIR/summary.yml")}"  # override for testing
changes="$(git log --format='%h %ad %s' --date=short "$last"..HEAD -- . ":(exclude)$DIR")"
if [[ -z "$changes" ]]; then
  echo "[team-summary] no wiki changes since $last; summary is current"
  exit 0
fi
echo "[team-summary] wiki changes since last summary:"
echo "$changes"

prompt="$(sed -e "s|{{CLIENT}}|$CLIENT|g" -e "s|{{TODAY}}|$TODAY|g" "$HUB/tools/team_summary/refresh-prompt.md")"
prompt="${prompt/\{\{CHANGES\}\}/$changes}"

run_agent() {
  local p="$1"
  case "$AGENT" in
    codex)
      codex exec -s workspace-write --skip-git-repo-check -C "$WORK/wiki" "$p" ;;
    claude)
      claude -p "$p" --permission-mode acceptEdits --allowedTools "Read,Grep,Glob,Edit,Bash(git log:*),Bash(git show:*)" ;;
    *)
      echo "[team-summary] FAIL: unknown TEAM_SUMMARY_AGENT=$AGENT"; exit 1 ;;
  esac
}
check() {
  uv run --project "$HUB" --group dev python "$HUB/tools/team_summary/build.py" \
    --data "$DIR/summary.yml" --wiki-root . --check-sources --check-only
}

run_agent "$prompt"
if ! problems="$(check 2>&1)"; then
  echo "[team-summary] validation failed; one retry with the errors:"
  echo "$problems"
  run_agent "$prompt

The previous edit of $DIR/summary.yml failed validation. Fix exactly these problems and change nothing else:
$problems"
  if ! problems="$(check 2>&1)"; then
    echo "[team-summary] FAIL: still invalid after retry; nothing committed:"
    echo "$problems"
    exit 1
  fi
fi

touched="$(git status --porcelain | awk '{print $2}' | sort -u)"
if [[ -z "$touched" ]]; then
  echo "[team-summary] agent found nothing material to change"
  exit 0
fi
if [[ "$touched" != "$DIR/summary.yml" ]]; then
  echo "[team-summary] FAIL: agent touched files other than $DIR/summary.yml:"
  echo "$touched"
  exit 1
fi

build_args=(
  --data "$DIR/summary.yml"
  --out "$DIR/team-summary.pdf"
  --wiki-root .
  --check-sources
  --make-review-copies
)
if [[ -n "${TEAM_SUMMARY_PUBLISH_DIR:-}" ]]; then
  build_args+=(--publish-dir "$TEAM_SUMMARY_PUBLISH_DIR")
fi
uv run --project "$HUB" --group dev python "$HUB/tools/team_summary/build.py" "${build_args[@]}"

git add "$DIR/summary.yml" "$DIR/team-summary.pdf"
copies_dir="$(uv run --project "$HUB" --group dev python -c 'import sys,yaml; d=yaml.safe_load(open(sys.argv[1], encoding="utf-8")); print((d.get("review") or {}).get("copies_dir") or "")' "$DIR/summary.yml")"
if [[ -n "$copies_dir" && -d "$copies_dir" ]]; then
  while IFS= read -r -d '' copy; do
    git add "$copy"
  done < <(find "$copies_dir" -type f -name '*-review.html' -print0)
fi
git -c user.name="Vamsee Achanta" -c user.email="23155845+vamseeachanta@users.noreply.github.com" \
  commit -q -m "team-summary: daily refresh $TODAY" \
  -m "Generated by workspace-hub scripts/reports/team-summary-refresh.sh ($AGENT); facts from: $(echo "$changes" | awk '{print $1}' | paste -sd' ')"
git show --stat --format='%h %s' HEAD

if [[ "$DRY_RUN" == 1 ]]; then
  echo "[team-summary] dry run: not pushed"
  exit 0
fi
git push -q origin "HEAD:$REF"
echo "[team-summary] pushed $(git rev-parse --short HEAD) to $REPO@$REF"
