# Master Agent Registry - Workspace Hub
# Central registry for all 78+ agents across 26 repositories
# Version: 1.0.0
# Last Updated: 2025-10-05

meta:
  version: "1.0.0"
  last_updated: "2025-10-05T13:45:00Z"
  total_agents: 78
  update_frequency: "daily"
  orchestrator: "@modules/automation/agent_orchestrator.sh"
  best_practices: "@.claude/agents/BEST_PRACTICES.md"

# ==========================================
# AGENT CATEGORIES
# ==========================================

categories:
  domain_specific:
    count: 11
    description: "Specialized domain expert agents"
    agents:
      - aqwa
      - freecad
      - gmsh
      - orcaflex
      - orcawave
      - cad-engineering-specialist
      - web-test-module
      - drilling-expert
      - oil-and-gas-expert
      - financial-analysis
      - finance-analytics

  general_purpose:
    count: 54
    description: "Claude Flow MCP orchestration agents"
    platform: "claude-flow@alpha"
    registry_reference: "@modules/config/ai-agents-registry.json"
    agents:
      core_development:
        - coder
        - reviewer
        - tester
        - planner
        - researcher
      swarm_coordination:
        - hierarchical-coordinator
        - mesh-coordinator
        - adaptive-coordinator
        - collective-intelligence-coordinator
        - swarm-memory-manager
      consensus_distributed:
        - byzantine-coordinator
        - raft-manager
        - gossip-coordinator
        - consensus-builder
        - crdt-synchronizer
        - quorum-manager
        - security-manager
      performance:
        - perf-analyzer
        - performance-benchmarker
        - task-orchestrator
        - memory-coordinator
        - smart-agent
      github_integration:
        - github-modes
        - pr-manager
        - code-review-swarm
        - issue-tracker
        - release-manager
        - workflow-automation
        - project-board-sync
        - repo-architect
        - multi-repo-swarm
      sparc_methodology:
        - sparc-coord
        - sparc-coder
        - specification
        - pseudocode
        - architecture
        - refinement  # Enhanced with continuous refactoring tools (jscpd, knip)
      specialized_development:
        - backend-dev
        - mobile-dev
        - ml-developer
        - cicd-engineer
        - api-docs
        - system-architect
        - code-analyzer
        - base-template-generator
      testing_validation:
        - tdd-london-swarm
        - production-validator
      migration_planning:
        - migration-planner
        - swarm-init

  workflow_automation:
    count: 6
    description: "Shared workflow automation sub-agents"
    hub_repository: "assetutilities"
    registry_reference: "@assetutilities/agents/registry/sub-agents.yaml"
    agents:
      - workflow-automation
      - file-management-automation
      - visualization-automation
      - auth-system
      - git-workflow-automation
      - free-agent-templates

  visualization:
    count: 4
    description: "Visualization and reporting specialists"
    agents:
      - plotly-visualization-agent
      - bokeh-dashboard-agent
      - altair-analysis-agent
      - d3js-custom-viz-agent

  platform_agents:
    count: 3
    description: "Platform-specific agent implementations"
    platforms:
      - factory-ai
      - spec-kit
      - agent-os

# ==========================================
# REPOSITORY MAPPINGS
# ==========================================

repositories:
  digitalmodel:
    path: "/mnt/github/workspace-hub/digitalmodel"
    specialization: "engineering-simulation"
    agent_count: 7
    agents:
      - name: "aqwa"
        path: "agents/aqwa"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        specialization: "offshore-hydrodynamics"
        created: "2025-08-10"

      - name: "freecad"
        path: "agents/freecad"
        type: "engineering-tool"
        status: "active"
        config: "agent_config.json"
        specialization: "cad-automation"
        api_port: 8000

      - name: "gmsh"
        path: "agents/gmsh"
        type: "engineering-tool"
        status: "active"
        config: "agent_config.json"
        specialization: "mesh-generation"

      - name: "orcaflex"
        path: "agents/orcaflex"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        specialization: "mooring-riser-simulation"
        integrations: ["aqwa", "ansys-mechanical"]

      - name: "orcawave"
        path: "agents/orcawave"
        type: "engineering-tool"
        status: "active"
        config: "agent_config.json"
        specialization: "wave-analysis"

      - name: "cad-engineering-specialist"
        path: "agents/cad-engineering-specialist"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        specialization: "cad-engineering"
        created: "2025-08-14"

      - name: "web-test-module"
        path: "agents/web-test-module"
        type: "general-purpose"
        status: "active"
        config: "agent.yaml"
        specialization: "web-testing"
        created: "2025-08-10"

  worldenergydata:
    path: "/mnt/github/workspace-hub/worldenergydata"
    specialization: "energy-analysis"
    agent_count: 3
    agents:
      - name: "drilling-expert"
        path: "agents/drilling-expert"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        specialization: "drilling-operations"
        created: "2025-08-25"

      - name: "oil-and-gas-expert"
        path: "agents/oil-and-gas-expert"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        specialization: "oil-gas-industry"
        created: "2025-08-25"

      - name: "financial-analysis"
        path: "agents/financial-analysis"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        version: "3.0.0"
        specialization: "energy-finance"
        cross_repo: ["worldenergydata", "assetutilities", "digitalmodel"]

  assetutilities:
    path: "/mnt/github/workspace-hub/assetutilities"
    specialization: "financial-utilities"
    agent_count: 2
    hub_for_automation: true
    agents:
      - name: "finance-analytics"
        path: "agents/finance-analytics"
        type: "domain-expert"
        status: "active"
        config: "agent.yaml"
        version: "1.0.0"
        specialization: "financial-analysis"

      - name: "test-interactive"
        path: "agents/test-interactive"
        type: "workflow"
        status: "active"
        config: "agent.yaml"
        specialization: "interactive-testing"

  workspace_hub:
    path: "/mnt/github/workspace-hub"
    specialization: "multi-repo-orchestration"
    agent_count: 0
    central_registry: true
    provides:
      - "master agent registry"
      - "orchestration scripts"
      - "best practices documentation"
      - "centralized configurations"

# ==========================================
# AGENT SELECTION & ORCHESTRATION
# ==========================================

agent_selection:
  orchestrator:
    path: "@modules/automation/agent_orchestrator.sh"
    description: "Intelligent agent selection based on task type and complexity"

  registry:
    path: "@modules/config/ai-agents-registry.json"
    description: "Claude Flow MCP agent capability database"
    update_schedule: "daily"

  task_types:
    code-generation:
      primary: "claude-sonnet-4.5"
      alternatives: ["factory-ai-droid", "claude-flow-coder"]
      complexity:
        simple: "claude-flow-coder"
        moderate: "claude-sonnet-4.5"
        complex: "claude-sonnet-4.5"

    code-refactoring:
      primary: "sparc/refinement"
      alternatives: ["claude-flow-coder", "code-analyzer"]
      tools: ["jscpd", "knip", "eslint-react-compiler", "eslint-deprecation"]
      workflow: "continuous_improvement"
      requires_approval: true

    test-creation:
      primary: "claude-flow-tester"
      alternatives: ["tdd-london-swarm", "spec-kit-analyzer"]

    code-review:
      primary: "code-review-swarm"
      alternatives: ["claude-sonnet-4.5", "factory-ai-droid"]

    architecture-design:
      primary: "claude-flow-architect"
      alternatives: ["claude-sonnet-4.5", "system-architect"]

    spec-creation:
      primary: "spec-kit-analyzer"
      alternatives: ["agent-os-planner", "claude-sonnet-4.5"]

    requirement-analysis:
      primary: "agent-os-planner"
      alternatives: ["claude-sonnet-4.5", "researcher"]

    documentation:
      primary: "claude-flow-doc-writer"
      alternatives: ["factory-ai-droid", "api-docs"]

    bug-fixing:
      primary: "claude-sonnet-4.5"
      alternatives: ["factory-ai-droid", "claude-flow-debugger"]

    migration:
      primary: "migration-planner"
      alternatives: ["claude-sonnet-4.5", "system-architect"]

    performance-opt:
      primary: "perf-analyzer"
      alternatives: ["claude-sonnet-4.5", "performance-benchmarker"]

    security-audit:
      primary: "security-manager"
      alternatives: ["claude-sonnet-4.5", "code-review-swarm"]

# ==========================================
# CROSS-REPOSITORY INTEGRATION
# ==========================================

cross_repository_integration:
  enabled: true

  reference_formats:
    workspace_hub: "@workspace-hub/.claude/agents/{category}/{subcategory}/{agent}.yaml"
    assetutilities_hub: "@assetutilities/agents/registry/sub-agents/{sub-agent}"
    repository: "@{repo}/agents/{agent-name}"
    relative: "../{agent-name}" # Within same repository

  hub_repository:
    name: "assetutilities"
    path: "/mnt/github/workspace-hub/assetutilities"
    provides:
      - workflow-automation
      - file-management-automation
      - visualization-automation
      - auth-system
      - git-workflow-automation
      - free-agent-templates
    compatible_repo_types:
      - engineering
      - data_science
      - project_management
      - infrastructure
      - documentation

  shared_components:
    enabled: true
    sync_strategy: "hub-based"
    update_method: "automated-sync"

  agent_communication:
    methods:
      - "cross-references"
      - "shared-memory"
      - "api-integration"
      - "data-exchange"
    protocols:
      - "claude-flow-hooks"
      - "rest-api"
      - "file-based"

# ==========================================
# CONFIGURATION PATTERNS
# ==========================================

configuration_patterns:
  domain_expert_yaml:
    format: "YAML"
    template: "@.claude/agents/templates/domain-expert.yaml"
    required_fields:
      - name
      - version
      - type
      - specialization
      - domain_expertise
      - capabilities
      - processing_config
    optional_fields:
      - cross_references
      - repositories
      - integrations

  engineering_tool_json:
    format: "JSON"
    template: "@.claude/agents/templates/engineering-tool.json"
    required_fields:
      - name
      - version
      - description
      - capabilities
      - settings
    optional_fields:
      - integrations
      - api
      - performance

  mcp_registry_json:
    format: "JSON"
    template: "@modules/config/ai-agents-registry.json"
    required_fields:
      - platform
      - type
      - capabilities
      - bestFor
    optional_fields:
      - limitations
      - costTier
      - domains

# ==========================================
# BEST PRACTICES REFERENCE
# ==========================================

best_practices:
  documentation: "@.claude/agents/BEST_PRACTICES.md"

  key_principles:
    - "Semantic versioning for all agents"
    - "Clear capability declarations"
    - "Context optimization (max 16K)"
    - "Phased processing (6 phases)"
    - "Quality thresholds (0.7-0.8)"
    - "Cross-repository references with @ notation"
    - "No hardcoded secrets"
    - "Comprehensive error handling"
    - "Performance monitoring"
    - "Security-first design"

  configuration_standards:
    versioning: "semver (MAJOR.MINOR.PATCH)"
    timestamps: "ISO 8601 format"
    context_size: "16000 max"
    quality_threshold: "0.8 for validation"
    refresh_schedule: "daily (market), weekly (regulations), monthly (standards)"

  integration_standards:
    api_port: "8000 (default)"
    rate_limit: "60 requests/minute"
    cors_enabled: true
    authentication: "api_key or oauth2"
    audit_logging: true

  testing_requirements:
    unit_tests: "required"
    integration_tests: "required for cross-agent"
    performance_tests: "required for batch operations"
    validation_threshold: "0.8 minimum"

# ==========================================
# AUTOMATION & MAINTENANCE
# ==========================================

automation:
  sync_script:
    path: "@modules/automation/sync_agent_configs.sh"
    description: "Synchronize agent configs between central registry and repositories"
    operations:
      - pull: "Update central registry from repositories"
      - push: "Push central registry updates to repositories"
      - validate: "Validate all agent configurations"

  update_script:
    path: "@modules/automation/update_ai_agents_daily.sh"
    description: "Daily update of agent capabilities and registry"
    schedule: "daily at 00:00 UTC"
    operations:
      - update_capabilities
      - refresh_external_sources
      - validate_configurations
      - generate_metrics

  validation_script:
    path: "@modules/automation/validate_agent_configs.sh"
    description: "Validate agent configuration schemas and cross-references"
    checks:
      - schema_validation
      - capability_verification
      - cross_reference_check
      - performance_benchmark

  orchestrator:
    path: "@modules/automation/agent_orchestrator.sh"
    description: "Intelligent agent selection and task delegation"
    features:
      - task_type_classification
      - complexity_based_selection
      - platform_specific_commands
      - automated_review_workflow

# ==========================================
# METRICS & MONITORING
# ==========================================

metrics:
  enabled: true

  agent_usage:
    track: true
    metrics:
      - execution_count
      - success_rate
      - average_execution_time
      - token_usage
      - error_rate

  performance:
    track: true
    metrics:
      - response_time
      - throughput
      - resource_utilization
      - cache_hit_rate

  quality:
    track: true
    metrics:
      - output_quality_score
      - validation_pass_rate
      - user_satisfaction
      - improvement_rate

  reporting:
    interval: "daily"
    output_format: "json"
    dashboard_url: "http://localhost:3000/agent-metrics"

# ==========================================
# MIGRATION & ROLLBACK
# ==========================================

migration:
  strategy: "phased-rollout"

  phases:
    - phase: 1
      description: "Test with 2 repositories (digitalmodel, worldenergydata)"
      duration: "1 week"

    - phase: 2
      description: "Expand to 10 repositories"
      duration: "1 week"

    - phase: 3
      description: "Full rollout to all 26 repositories"
      duration: "2 weeks"

  backup_strategy:
    enabled: true
    backup_location: ".claude/agents/.backup/"
    retention: "30d"

  rollback_plan:
    script: "@modules/automation/rollback_agent_configs.sh"
    triggers:
      - validation_failure_rate > 10%
      - error_rate > 5%
      - manual_trigger

  validation_gates:
    - schema_validation
    - cross_reference_integrity
    - performance_benchmark
    - integration_tests

# ==========================================
# FUTURE ENHANCEMENTS
# ==========================================

roadmap:
  planned_features:
    - agent_discovery_cli: "CLI tool to search agents by capability"
    - agent_metrics_dashboard: "Real-time agent usage and performance dashboard"
    - automated_agent_versioning: "Automated version bumping and changelog generation"
    - agent_marketplace: "Shareable agent templates and configurations"
    - ml_based_selection: "Machine learning for optimal agent selection"
    - cost_optimization: "Automatic cost-tier based agent selection"

  deprecation_policy:
    notice_period: "30d"
    support_period: "90d"
    migration_guide: "required"

  version_history:
    - version: "1.0.0"
      date: "2025-10-05"
      changes:
        - "Initial master registry creation"
        - "Consolidated 78+ agents from 26 repositories"
        - "Established best practices documentation"
        - "Implemented centralized orchestration"
