"""Auto-generated calculations from 0163-cal-0001-01-surface-wellhead-sitp-calculations-draft1.

Domain: energy-economics
Patterns: 3 unique
Generated by xlsx-poc-v2 pipeline.
"""

import math


# --- Sheet: Sheet1 ---

def calc_000(d16: float) -> float | dict:
    """Excel pattern: =D16*0.3048

    Cells: 1 (Sheet1)
    """
    d17 = d16*0.3048
    return d17


def calc_001(d15: float, d18: float, d19: float) -> float | dict:
    """Excel pattern: =(-(D18*D19*D17+D15)*2)/D18

    Cells: 1 (Sheet1)
    """
    c46 = (-(d18*d19*d17+d15)*2)/d18
    return c46


def calc_002() -> float | dict:
    """Excel pattern: =SQRT(C46)

    Cells: 1 (Sheet1)
    """
    c47 = math.sqrt(c46)
    return c47


if __name__ == "__main__":
    print("Module: 0163-cal-0001-01-surface-wellhead-sitp-calculations-draft1")
    print("Functions: 3")
    print("Domain: energy-economics")
